local tips = [
	// 75 Total As Of Now
	// BS - Memes - References etc.
	"(PoV) The shadows are watching...",
	"(PoV) Some are whispering that Goblin\'s woodwork ain\'t that good...",
	"(PoV) Donkeys make for great Vatt\'gherns...",
	"(PoV) Fotn is green, PoV is blue, Their modders can only get along, when they\'re trying to screw with you... (sad snow noises)",
	"(PoV) Hey, you. You\'re finally awake.",
	"(PoV) What tangled webs we weave...",
	"(PoV) Golf India Tango - Golf Uniform Delta!",
	"(PoV) The Abyss is for looking into and The Void is to scream at...",
	"(PoV) Be kind to my mascot, or pot WILL find you.",
	"♠☺☺☺☺☺♥♥♥♥♥☺☺☺☺☺♠",
	"(PoV) Rumors say templar was drunk asf when writing these...",
	"(PoV) Yes, use breditor, and make sure to tell the Legends Devs about it...",
	"(PoV) It is said there are wise women in the south too, but they don\'t know shit about spirits and rune stones...",
	// General Advice
	"(PoV) Want some spice in your life? Try Chaos Mode...",
	"(PoV) Legendary Difficulty is supposed to be hard, so only complain if it isn\'t.",
	"(PoV) PoV has its own wiki! A condensed version with important details is in PoV\'s mod settings, and a detailed one in the github page (wip).",
	"(PoV) Most enemy factions have received some sort of buff, usually in the form of new effects, and enemies.",
	"(PoV) There are certain actions (like getting a vattghern) that you can do to trigger special events, that in turn unlock more PoV mechanics, and provide guidance.",
	"(PoV) Don\'t want to grind for a vatt\'ghern? Check out PoV\'s starting scenarios!",
	"(PoV) The enemy mutation effects are similar to the vattghern ones, there is designed counterplay for each of them.",
	"(PoV) The wrong mutations, on the wrong enemy, can easily cause you trouble, maybe even end your run.",
	"(PoV) Combat Difficulty affects many aspects of pov, including power of enemies, mutation rates, drop rates etc.",
	"(PoV) The main way to get crafting materials and mutagens is by killing shit...and dissecting their corpses.",
	"(PoV) If you do not have a Vatt\'ghern, an alternative way to making use of mutagens is to hire mutants...",
	"(PoV) Check tavern rumors if you are looking for specific settlement situations.",
	"(PoV) Enemy Champions are more likely to have multiple mutations.",
	"(PoV) Getting a Vatt\'ghern should be your priority, as many of PoV\'s mechanics are centered around this.",
	"(PoV) Do not rush to discard support backgrounds, they are more important in this mod.",
	"(PoV) Make sure to check PoV\'s settings, as there are some options for customisation, and toggleable balance patches for other mods!",
	"(PoV) PoV generally makes the game harder, but also gives you more than enough tools to deal with new and improved threats, make use of them!",
	"(PoV) There are more than 40 events added in the mod, and I like doing them. Feel free to suggest, or even help with making more!",
	"(PoV) Beware when travelling...Powerful new enemies roam the lands",
	"(PoV) Rumors say that the fire spewing weapons of the east have also found a home north. With some adaptations...",
	"(PoV) Flesh golems and their creators now roam the land, looking for more victims...",
	"(PoV) The armor system is now reworked, increasing the protection of high armor, but with a cost...",
	"(PoV) Rumors say that other vatt\'ghern roam the lands. Powerful, fearsome rogues...",
	"(PoV) Not all mercenaries are law abiding, to no one\'s surprise. Some especially powerful bands have taken to banditry...",
	"(PoV) Rogue mercenary companies now roam the land, with quite the quality selection of equipment...",
	// Specific Mechanics Advice
	"(PoV) Looking for specific crafting materials or mutations? Make sure to check out Alchemists, and Black Markets!",
	"(PoV) Your crafting options are greatly expanded with PoV, check them out!",
	"(PoV) Vatt\'ghern contracts are generally very difficult, meant for the late game. They are available if you have at least one vatt\'ghern on your group.",
	"(PoV) Vatt\'ghern contracts are are a great opportunity for rare/unique loot and rewards.",
	"(PoV) Be careful when using the trial of the grasses - especially many at once -, as it can horrify your company.",
	"(PoV) Enemy mutations inherit properties from the monsters they are inspired from. Undead mutants are weak to holy water for example!",
	"(PoV) Beware of the Enemy Hexe Mutation! A way to deal with thit is to just wait the hex off!",
	"(PoV) There are more than enough tools to help you deal with those pesky mutants...and any other oddity.",
	"(PoV) Check PoV\'s item/skill descriptions they often include tips/info on their usefulness...",
	"(PoV) Vatt\'gherns get their own new Perks! Be sure to check them out.",
	"(PoV) Many enemies are now resistant or vulnerable to fire damage. Experiment!",
	"(PoV) Many options to deal fire damage were added, which might prove very useful against mutants, undead, beasts and more!",
	"(PoV) Vatt\'gherns may not be wizards, but they can still use *some* magic in the form of \"signs\"...",
	"(PoV) \"Sign Intensity\" increase the overall power of signs. Both their damage, and their chance to inflict ailments.",
	"(PoV) Enemy Seer\'s damage scales with their initiative, so reducing that is their counter.",
	"(PoV) Enemy forsaken are always mutated, which could be used against them...",
	"(PoV) Holy water can disrupt enemy geist unique skills, and it severely weakens all undead.",
	"(PoV) The Yrden Sign can disrupt the unique abilities and buffs of most enemy mutants",
	"(PoV) Increasing your armor over a certain threshold will yield diminishing defensive returns...",
	"(PoV) When having high armor, it being damaged lowers its defensive capabilities less than it would light armors.",
	"(PoV) Heavy armors apply a scaling penalty to the wearer when heavily damaged. Light armors apply none!",
	"(PoV) The armor mechanics rework affects player and enemy *almost* equally...",
	"(PoV) Harsh Weather can be quite hindering to those who are unprepared...",
	"(PoV) During rainfall and other harsh weather, guns, flame magic and any sort of fire attacks are weaker.",
	"(PoV) There are ways to reduce the effects of harsh weather, or even ignore them",
	"(PoV) The Vatt\'ghern sword can be re-crafted into a one-handed version, and back to a two-handed one at will!",
	"(PoV) Specialist perks not only appear on some specific backgrounds, but can also appear randomly on almost anyone",
	"(PoV) Some backgrounds can appear with different specialist perks, and rarely with multiple ones",
	"(PoV) Traits are not just for the player, enemies can have them too! Good, or bad...",
	"(PoV) Many beasts with thick skin and fur are now resistant to blunt damage, but weak to fire...",
	"(PoV) Enemy beasts, spirits and undead can be champions too, dropping some unique loot!",
	"(PoV) Did you know, that somehow donkeys can wear.... accessories?",
	"(PoV) Reaching max scaling with the Vatt\'ghern trait also grants a perk point!",
	"(PoV) Most beasts, and many undead and spirits are immune to harsh weather conditions",
	// Misc
	"(PoV) I am eager to see your feedback on the mod!",
	"(PoV) Did you know that the PoV mod adds 2 new company banners?",
	"(PoV) Have a cool looking Vatt\'ghern? Come show off your fashion in our discord server!"
];
::Const.TipOfTheDay.extend(tips);
