::mods_hookExactClass("events/events/crisis/greenskins_outro_event", function(o) {
	local create = o.create;
	o.create = function() {
		create();
		foreach (s in this.m.Screens) {
			if (s.ID == "B") {
				s.Text = "[img]gfx/ui/events/event_05.png[/img]%dude% reaches for his weapon, but you shake your head. The lieutenant nods toward the mercenary.%SPEECH_ON%Best keep that dog on its leash, aye?%SPEECH_OFF%You fan your arm out, inviting the soldiers a \'passage\' they knew they already had. The soldiers gear up and the lieutenant smirks.%SPEECH_ON%I knew you\'d make the right choice. We\'re just \'aving a bit of fun, yeah? You ladies stay tight.%SPEECH_OFF%The man blows a kiss as he walks by. %dude% stands up looking like someone just socked his mother. You tell him to sit back down and he begrudgingly does so. It\'s all bullshit, these theatrics, but you\'re not one to lose your temper and get people killed over it.\n\nThe incident does make you wonder if maybe it\'s time to turn it all in. The greenskins are beaten back and you\'ve made enough money to leave the life for good, but then again you\'d hate to live out the rest of your days wondering \'what if\'...\n\n%OOC%Something burns down inside of you. Something that struggles to be free. Perhaps it is the success you have have had along the way, or the failings that you couldn\'t stop in time. Maybe there is more out there to see?%OOC_OFF%";
			}
			if (s.ID == "C") {
				s.Text = "[img]gfx/ui/events/event_05.png[/img]The soldiers\' lieutenant glares at you.%SPEECH_ON%Do as I said, sellsword, or there will be trouble.%SPEECH_OFF%Ignoring him, you give another nod to %dude%. He gets up, the blade of his weapon loudly scraping off the dirt. The soldiers turn to the mercenary. He hefts his weapon into both hands and stares back. As the lieutenant starts to talk, %dude% bluntly interrupts.%SPEECH_ON%Shush, little man. I see softness in your skin. Not a scar to be seen. Eyes as fresh as the day they were born. Hands as smooth as untouched candles. If you was of the fightin\' sort, you\'d be out there in those battles you speak of, not out here pissing into the wind. I\'ll give you two options because I\'m feeling nice. First option, are you listening? First option is this. Go where you are going and don\'t say another goddam word.%SPEECH_OFF%He pauses to hold up two fingers.%SPEECH_ON%Option two is a mystery. Speak and ye shall learn of it.%SPEECH_OFF%The lieutenant\'s eyes have gotten a little wider, and his mouth infinitely quieter. He glances at you, but all you can do is shrug. After another moment, the soldiers hurry away with determined silence.\n\n%dude% laughs it up, but the incident has you wondering if perhaps it is finally the time to retire. How many more of these cockups are in your future? How many more battles? How many more dead men will you have to bury? The company would do well standing on the foundations you\'ve built for it. But on the other hand, if you retired now, what adventures would you miss out on?\n\n%OOC%Something burns down inside of you. Something that struggles to be free. Perhaps it is the success you have have had along the way, or the failings that you couldn\'t stop in time. Maybe there is more out there to see?.%OOC_OFF%";
			}
		}
	}
})
