::mods_hookExactClass("events/events/dlc2/location/ancient_temple_enter_event", function(o) {
	local create = o.create;
	o.create = function() {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{Only half of the temple\'s entrance is visible, the rest long since sunk into the earth as though unsure whether to be coffin or mausoleum. Along a visible frieze you can see a stony relief of tables being thrown and monied men running from what looks like an armored skeleton with a whip. A few of the mercenaries seem uncomfortable with the idea of going in, but you\'ve the notion that others have felt that way as well and have thus left the place unmolested.\n\n You take out a torch and enter with a sellsword\'s spirit and robber\'s resolve. After gathering supplies, you crouch and enter the temple by slinging your legs over the earth and jumping into the steps below. The clap of your boots snickers into the marbled halls and you wave the torch before you as if to watch the echoes go. Looking back, the light between the shelf of earth and the temple top silhouetting your company as though they were a throng of sextons satisfied at their work. %volunteer% shakes %their_volunteer% head and says %they're_volunteer% coming with. The rest of the company mutually agrees to keep watch.}";
		});
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{The sides of the halls are blanketed in military mosaics so large they\'re more fit to a whole campaign than any single battle. One parcel in particular stretches seemingly forever down the hall, a scene of armored men running roughshod over what looks like a barbarian horde so thick in number they lose humanity and begin to look indiscernible from bugs. Your torch bulbs and dims in the dark, the light bringing an artist\'s battlefield to an orangish life and in the corners you find depictions of righteous torture and outrage. Between the lockstep forces and the disassembled mob, it looks like order and chaos have come to clash, and while order is surely set to win, it is chaos itself which is driving the way to victory.\n\n %volunteer% whistles. You look to see %their_volunteer% torch flaring in the distance like an ignis fatuus. You run over to find %them_volunteer% holding a vial with a strange liquid inside. The sellsword swings %their_volunteer% torch to an alcove in the wall. A marbled post hold the center and there\'s a throng of skeletons at its base.%SPEECH_ON%I found the vial on the pedestal there. And I see two more like it yonder, but they\'re behind gates.%SPEECH_OFF%You ask the sellsword why %they_volunteer% didn\'t tell you about the bodies. %They_volunteer% shrugs.%SPEECH_ON%They ain\'t breathing, then I ain\'t caring. You wanna make a try for the other two flasks or no?%SPEECH_OFF%}";
		});
		::Legends.Screens.hook(this, "G", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{The last vial is behind another gate, an unsettling one to look at just by an architectural standpoint. There are not mere stone bars here, but twisted iron spires scarred with scoria and slag, and the gate is not at chest level, but at your shins. The vial itself is on a further rise, meaning you\'d have to reach under the wall and then up again to get it. The voice returns.%SPEECH_ON%From me all comes to being, from me all shall be in the end. When man crosses the earth, I follow in his footsteps.%SPEECH_OFF%You stand in the silence and look over at %volunteer%. %They_volunteer% shrugs.}";
		});
		::Legends.Screens.hook(this, "H", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{As soon as the word leaves your lips the gate jolts up. You pensively stare at the remaining gap. %volunteer% crouches down and slings %their_volunteer% arm under the gateway\'s top and gets up at the vial. %Their_volunteer% fingers scrape its glass while the gate\'s spires rattle in their catches like a bear reluctantly letting someone brush its teeth. The %person_volunteer% finally pinches the vial between two fingers and scissor-flips it into the safe embrace of %their_volunteer% palm. %They_volunteer% stands up and hands it over.%SPEECH_ON%Simple enough, eh?%SPEECH_OFF%You nod but then turn around with your torch and yell out, demanding to know who was talking. There is no answer. A brief search in the darkness turns up no hidey-holes or dugouts, but you do find scraps and notes with drawings on them. The pages seem to indicate the vials are capable of killing wiedergangers with but a single touch of the liquid within each flask. There is also a sticky paper with a crudely drawn woman on it. Whoever was here, you don\'t care. You take the vials back out and return to the %companyname%. They draw swords at the sound of you, then sheepishly sheathe them once they see your face.%SPEECH_ON%Sorry captain, thought ya a mite dead. And walking. A walking dead man.%SPEECH_OFF%}";
		});
		::Legends.Screens.hook(this, "I", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{As soon as the word leaves your lips the gate jolts up. You pensively stare at the remaining gap. %volunteer% crouches down and slings %their_volunteer% arm under the gateway\'s top and gets up at the vial. %Their_volunteer% fingers scrape its glass while the gate\'s spires rattle in their catches. The voice suddenly booms back in.%SPEECH_ON%G-go fark myself? How about fark you, uh, pal!%SPEECH_OFF%With that, the gate\'s catch fails and its tips sink down and spear %volunteer%\'s arm. The %person_volunteer% yells out and you drop to your knees and yank the gate back up. It\'s heavier than expected and when you let go it slams with unnerving finality, a strip of the sellsword\'s arm here, a gush of %their_volunteer% veins there. You wrap the wound and help the %person_volunteer% toward the exit, all the while waving the torch around to ward off any would be ambush. However, while heading out, you pause and look at the skeleton\'s you found beside the first flask. You take a drop from the vial and touch it to your fingertips. No response. You then put your finger on one of the bones and it sizzles and smokes. %volunteer% laughs.%SPEECH_ON%That\'s why you\'re captain, sir. Intuition like that can take you far!%SPEECH_OFF%You never hear the mysterious voice again and, not wanting to sound insane, make no reference of the riddler to the %companyname%.\n\n %volunteer%\'s wounds won\'t be the end of %them_volunteer%. Tis but a small price to pay for the ancient vials.}";
		});
		::Legends.Screens.hook(this, "K", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_111.png[/img]{The man\'s eyes gleam in the dark and each glance is like an ember scattered.%SPEECH_ON%Ya mean it? I can join ya? Alright!%SPEECH_OFF%He slowly gets to his feet as though quick action might lead to even quicker reneging. He puts a hand out, which you do not shake.%SPEECH_ON%My name\'s %idiot%. I\'ve got half a brain, rest is wood and pulp. I\'m kindling, of course. Kidding. Kindling. Get it?%SPEECH_OFF%You look at %volunteer% who stabs the man in the chest. The idiot\'s face goes tense as he looks down at the sword impaling his heart.%SPEECH_ON%Hey. I think you killed me.%SPEECH_OFF%%volunteer% nods.%SPEECH_ON%Aye. I did. You got seconds. Speech?%SPEECH_OFF%The riddler thinks briefly.%SPEECH_ON%Well, I didn\'t prepare one, but... since... ya... asked...%SPEECH_OFF%He dies on the word and the blade. The sellsword cleans the blood and picks through the body, finding only musty rat bones in his pockets. When %they_volunteer% lets the corpse go it clunks the tile rather hollowly. You crouch and feel the man\'s skull and find he actually wasn\'t kidding, its half made of wood! You look at %volunteer% who shrugs.%SPEECH_ON%He could have shat gold for all I care, I ain\'t putting up with his mouth. Besides, look at his eyes! That fool was blind as a bat.%SPEECH_OFF%The riddler\'s eyes are a blank grey. Who knows how long he spent in this temple.}";
		});
	}
});