::mods_hookExactClass("events/events/aging_swordmaster_event", function(o) {
	local create = o.create;
	o.create = function() {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]You find %swordmaster% struggling to set %themselves_swordmaster% down on a tree stump. As %they_swordmaster% gingerly lowers, you see %their_swordmaster% legs quaking as though they can barely bend at all. %They_swordmaster% lets out a long sigh after %they_swordmaster% takes %their_swordmaster% seat. %Their_swordmaster% sword is beside %them_swordmaster%. It is younger than the hands that own it, a replacement of a replacement of a replacement. %They_swordmaster% shows no fondness for it, but when %they_swordmaster% touches it you sense there is a reflection in the very idea of a sword, of how a %person_swordmaster% lengthens %themselves_swordmaster% with it, and how %they_swordmaster% shortens others by its very blade. You turn to leave, hoping to give the swordmaster time to %themselves_swordmaster%, but %they_swordmaster% notices your departure and calls out.%SPEECH_ON%Hey there, captain. Didn\'t mean for you to see that.%SPEECH_OFF%";
		});
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]%They_swordmaster% leans back, rubbing one of %their_swordmaster% knees with a calloused hand. A bit of wind throws %their_swordmaster% tufts of greyed hair around.%SPEECH_ON%Old. That\'s how I\'m doing. And I don\'t mean my age. By the years, I\'ve been old for a while now. I mean I\'m old in the bones. I suppose I get by on reputation a lot more than skills these days.%SPEECH_OFF%You immediately disagree, telling %them_swordmaster% that %they're_swordmaster% one of the deadliest %people_swordmaster% you\'ve ever met.%SPEECH_ON%Save the niceties for the others, captain. My vision\'s going. You probably don\'t want to hear that, but it is. My lead foot doesn\'t step like it used to. The knee clicks, seizes up. One day that is going to cost me. My off-hand has no feeling.%SPEECH_OFF%The swordmaster clenches and unclenches his free-hand.";
		});
		::Legends.Screens.hook(this, "C", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]%SPEECH_ON%Nothing. I suppose the nerves are dying. And sometimes I forget things. I don\'t mean where I left my boots, either. I forget if there is someone standing behind me or not. My sense of my surroundings, my real blade, has been dulled. For all my speed and instinct it was time that has crept upon me, slow and steady, with no heat nor cold to give it away, it simply was and is and will be. I always thought I\'d be bested by another swordsman. Someone of talent. But I suppose I was too good for that.%SPEECH_OFF%The swordmaster grins playfully. You ask if %they_swordmaster% fears a death with no honor.%SPEECH_ON%I realized a long time ago that, when you become someone of my reputation, any route to death is going to be a disappointing one. They\'ll write it in the books how someone below my stature slew the great swordmaster. It\'s hogwash. If you want the truth I\'ll tell ya. I fear what I know is coming. That my body will betray me in the last moments. With time at its side, my body is what is going to kill me. The knee will lock, the grip will loosen, the shoulder will weaken. I don\'t fear death. I was too good for death, so death\'ll have to wait. My body is going to kill me first, then death can have what\'s left, the sorry blackened sod. The writers and historians? Piss on \'em. If I wanted eternal glory I would\'ve fought an army by myself.%SPEECH_OFF%";
		});
		::Legends.Screens.hook(this, "E", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]You hear the old swordmaster sigh as you move away. Keeping up with the rest of the company, it seems, has become a battle in and of itself for %them_swordmaster%.";
		});
	}
})
