::mods_hookExactClass("events/events/aging_swordmaster_paycut_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]%swordmaster% enters your tent. You wave %them_swordmaster% to the chair across your table. %They_swordmaster% sits so slowly and feebly that you fear %them_swordmaster% standing back up will take twice as long. The %person_swordmaster% clasps %their_swordmaster% hands together and elbows %their_swordmaster% arms onto the table, grunting and shifting, finding little comfort even in doing nothing at all. %Their_swordmaster% lips are dry, %their_swordmaster% face withered. Liver spots mottle %their_swordmaster% head and even the hairs about %their_swordmaster% nose and ears are grey.\n\n You always have time for %swordmaster% so you ask what it is %they_swordmaster% wishes to speak about.%SPEECH_ON%This might sound peculiar coming from a blade for hire, but I think it needs saying anyway, and it\'d make me sleep better at night. I\'ll be forward with you: I am not the %person_swordmaster% you hired so long ago. You know that. I know that. Some of the men know it, but they\'re respectful as good men are.%SPEECH_OFF%You agree, but don\'t nod. Instead, you ask what the %person_swordmaster% is getting at.%SPEECH_ON%I wish to lower my wage. Now don\'t be saying no, you don\'t have to bullshit me. I\'ll take a cut. Money\'s never been an issue anyhow. Those crowns could be used to help arm the men or even pay them better. God knows a young man could always use an extra crown or two.%SPEECH_OFF%Before you say another word, the %person_swordmaster% springs to %their_swordmaster% feet with surprising speed. %They_swordmaster% nods and grins playfully before yelling loudly.%SPEECH_ON%I agree with your decision, good sir. I could use a paycut!%SPEECH_OFF%You laugh as the %person_swordmaster% leaves your tent almost as soon as %they_swordmaster%\'d come in.";
		});
	}
});
