::mods_hookExactClass("events/events/aging_swordmaster_preview_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_17.png[/img]You find %swordmaster% sitting on a stump. %They're_swordmaster% looking out at the land.%SPEECH_ON%You know, I\'ve realized something as an old %person_swordmaster% who has operated far too long in this business of killing. I\'m so much wiser these days. I\'ve come to know so much, so much that I now know what I don\'t know. And I look back and think, I was such a dummy back in my youth. Then I thought, what of all the men I\'ve slain, stopping their mortal coil when it was young and so ready to spring?%SPEECH_OFF%You take a seat and shrug. %They_swordmaster% continues.%SPEECH_ON%What I\'ve realized is that I\'m a killer of wisdom. That I took a lot of old men out of this world, and with them went so much learning and knowledge. There\'s so many worlds out there that I destroyed. Worlds where those men lived and went on living and did the great things they knew not was in them. Had the first man I fought slew me down, how many lives would he have saved? How much wisdom would have been spared? I\'m sorry, I don\'t mean to drone on.%SPEECH_OFF%The %person_swordmaster% stands, patting %their_swordmaster% wobbly legs. You grab %their_swordmaster% arm.%SPEECH_ON%Have you considered that you may have also saved worlds? That some of those men you\'ve slain could have lived on to be horrible monsters?%SPEECH_OFF%%They_swordmaster% smiles, but you know %they're_swordmaster% already thought that through and doesn\'t wish to disturb you with the answer. %They_swordmaster% simply nods before going off to join the rest of the company.";
		});
	}
});
