::mods_hookExactClass("events/events/cow_tipping_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_72.png[/img]While on the march, you come across a lone cow standing in a field. Not much to it: it\'s just a cow.\n\n But then %randombrother% sidles up next to you. %They're_randombrother% gnawing on some broomstraw and twists it around as %they_randombrother% talks.%SPEECH_ON%So who do you think can do it?%SPEECH_OFF%You ask \'do what.\' %they_randombrother% smiles.%SPEECH_ON%Aw, sorry cap\'. Didn\'t realize you hadn\'t heard. We\'re gonna see if someone can knock that cow over! Say, seeing as how we can only knock it over once, how about you choose which of us has a go?%SPEECH_OFF%";
		});
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_72.png[/img]You tell the men to sort it out themselves. They quickly choose %cowtipper% who, after some badgering, agrees to give it a go.\n\n The sellsword carefully steps across the field, trying %their_other% best to avoid the cow patties. The cow itself nonchalantly looks over. It moos once before returning its short bovine attention to the grass. Snickering, the men shoo %cowtipper% onward, mouthing \'do it!\' and \'what are you waiting for?\' Finally, standing a few feet from the cow, %cowtipper% charges.%SPEECH_ON%Yaaahh!%SPEECH_OFF%%They_other% storms into the cow\'s side and %they_other% might as well have run into a house: %their_other% feet slip out from beneath %them_other% and %they_other% goes skidding beneath the animal, a glide well-oiled by fresh shit. The company bursts out laughing.%SPEECH_ON%You can\'t tip a cow ya fool! They\'re too goddam heavy!%SPEECH_OFF% %cowtipper% no doubt has a new beef with these jokers, but %their_other% \'sacrifice\' was worth the easy entertainment.";
		});
		::Legends.Screens.hook(this, "C", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_72.png[/img]You tell the men to sort it out themselves. They quickly choose %cowtipper%. The sellsword carefully steps across the field, trying %their_other% best to avoid the cow patties. The cow itself nonchalantly looks over and moos once before returning its attention to the grass. Snickering, the men shoo %cowtipper% onward, mouthing \'do it!\' and \'hurry now!\'. Finally, standing a few feet from the cow, %cowtipper% charges forward.%SPEECH_ON%Yaaahh!%SPEECH_OFF%The scream spooks the cow. She dips her withers and kicks, catching %cowtipper% with a bit of hooved heel. %They_other% violently spins on %their_other% feet and twists right into the grass. The men laugh for a moment, then realize it\'s serious. As the cow moos and trots away, the sellsword is \'rescued.\' Though badly hurt, %they_other%\'ll survive this near-bovine homicide.";
		});
		::Legends.Screens.hook(this, "Strong", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_72.png[/img]You figure the strong and burly %strong% could give the cow a good tipping. Your awkward wording alone has the men laughing, but %strong% respectfully bows.%SPEECH_ON%I am honored, sir.%SPEECH_OFF%%They_strong% rolls up %their_strong% sleeves and strolls across the field, striding over cow patties like a merchant stepping over the homeless. The cow looks over, raising a curious eyebrow. %strong% nods.%SPEECH_ON%That\'s right, I\'m coming.%SPEECH_OFF%More phrasing issues abound. Despite the laughter of the company, %strong% charges the cow. At first, %they_strong% simply presses against its side, muscled and heaving with breath. The men laugh as %their_strong% efforts get %them_strong% nowhere, but they quickly quiet down when the cow slides across the mud and grass. With a mighty roar, %strong% surges forward and the cow goes falling sideways with a confused moo.\n\n %otherbrother% stands there, slackjawed.%SPEECH_ON%It was a joke... I didn\'t think it was actually possible...%SPEECH_OFF%The company erupts in cheers for the strong man\'s incredible feat!";
		});
		::Legends.Screens.hook(this, "Cocky", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_72.png[/img]Before you can even finish your sentence, %cocky% beats %their_cocky% chest and steps forward.%SPEECH_ON%I will fell that petty cow!%SPEECH_OFF%You remind %them_cocky% that the company has no beef with the bovine creature and that this is all for fun and games. %They_cocky% stands there, arms tent-poled with %their_cocky% fists at %their_cocky% hips.%SPEECH_ON%Nonsense. The company laughs and thinks this an impossibility, but I\'m here to show them all just how wrong they are!%SPEECH_OFF%The cocksure sellsword steps into the field and immediately cuts %their_cocky% boot across a cow patty. %They_cocky% sidewinders forward, arms flailing for balance, but it\'s all for naught as %they_cocky% slams to the ground. The men burst into laughter. The cow glances over before simply walking off. %cocky% cleans %themselves_cocky% up.%SPEECH_ON%A minor misstep. But look! The cowardly cattle wants no part of me!%SPEECH_OFF%%otherbrother% laughs and points at the sellsword\'s stained garb.%SPEECH_ON%Maybe, but it looks like you got a little part of her.%SPEECH_OFF%The cocky sellsword quickly swipes the shite off %their_cocky% shirt. Despite the failure, %they_cocky% is undeterred and the men are almost passing out they\'re laughing so hard.";
		});
	}
});
