::mods_hookExactClass("contracts/contracts/hunting_lindwurms_contract", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		this.m.DescriptionTemplates = [
			"Giant, serpentine monsters are ravaging the countryside, devouring cattle and men. None appear able to stop them.",
			"A creature of nightmare and legend, the Lindwurm is a massive serpent with razor-sharp fangs and venom that burns like fire.",
			"Monstrous serpents that usually prowl the depths of the wilderness, the Lindwurm is a primal force of nature that brooks no challengers to its dominion.",
			"A monstrous serpent with a hunger that knows no bounds is terrorising the area. None dare face it.",
			"Colossal serpents with scales as hard as iron, few would ever dare to hunt such a creature.",
			"Hunt and eliminate the Lindwurm that has become a blight upon the region. Only the boldest need apply.",
		];
	}

	local createScreens = o.createScreens;
	o.createScreens = function () {
		createScreens();
		local event = this;
		::Legends.Screens.hook(this, "Task", function (_screen) {
			_screen.Title = event.m.Name;
			_screen.Text = "[img]gfx/ui/events/event_77.png[/img]{%employer% is staring into a basket when you find %them_employer%. A few peasants are off in the corner scratching themselves and looking rather tense. You ask what is going on. Your potential employer brings you over to the basket and inside you find a snake slithering about. It\'s a docile one, and the colors aren\'t arranged in a manner to suggest it carries poison in its belly. You tell %them_employer% as much. %They_employer% shrugs and closes the lid.%SPEECH_ON%Gonna kill it and eat it anyhow, take its skin for a dagger sheath. What I need you to do is go find a much larger snake than this. I\'m talking lindwurms, sellsword. Bigguns. Roaming about, eating folks in the hinterland. You the kind to see this situation sorted?%SPEECH_OFF% | You find %employer% mucking about %their_employer% personal library that\'s more cobweb than knowledge. %They_employer% seems to sense your entrance and asks if you know about lindwurms. Before you can answer %they_employer% wheels around, scroll in hand.%SPEECH_ON%I need you to go out to the hinterland. We got a couple of them monsters on our hands. They\'re killing farmers, peddlers. Hell, some of those folks were even well liked. I figure you\'d be just the man we\'d need to get these beasts off our backs. Are you interested?%SPEECH_OFF%You see %their_employer% scroll unfurl a bit to reveal a crudely drawn woman and her exposed breast. The %person_employer% hurriedly rolls it back up and stows it behind %their_employer% back. %They_employer% smiles.%SPEECH_ON%Well are ya?%SPEECH_OFF% | A line of peasants stand outside %employer%\'s door. You cut by them all and when a few protest you grab the handle of your sword. %employer% jumps out of %their_employer% door and intervenes.%SPEECH_ON%Ease up, ease up everyone. This is the mercenary I wanted to hire. Sir, please, let me explain the short tempers. Lindwurms are ravaging the countryside and we need a strapping sellsword such as yourself to slay them all. Are you interested?%SPEECH_OFF%The once angry peons now stare at you as though you were a savior.}";
		});
		::Legends.Screens.hook(this, "Banter", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_66.png[/img]{%randombrother% holds a sleeve of scaly skin at the length of %their_randombrother% weapon. %They_randombrother% wiggles it around, the shedding scratching itself in dry rasps. You tell %them_randombrother% to put it down and to be on guard. The lindwurms are no doubt close. | %randombrother% states that %they_randombrother% once heard the story of a lindwurm that killed someone without eating them.%SPEECH_ON%That\'s right. They said it spewed green water and the man just melted into his own boots. Said it looked like soup with his shins for stirring.%SPEECH_OFF%A disgusting tale, but one that hopefully keeps the men rightfully on their toes. Those lindwurms can\'t be far. | The tracks have the grass flattened in a snaking pattern with holes set to the sides. %randombrother% crouches beside the patterns.%SPEECH_ON%Either a plough with no dig or this be the critters we\'re lookin\' for.%SPEECH_OFF%You nod. The lindwurms can\'t be far.}";
		});
		::Legends.Screens.hook(this, "MerchantDistressFailure", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_60.png[/img]{The battle is over. You have half your men go about skinning the lindwurms to show %employer% when you get back. The other half sift through the remains of the merchant\'s caravan. There is nothing of note to find, not even gold. Anything of value has been smashed to pieces in the fighting. The merchant himself has been torn in half and the legs sit a way away with their pockets turned out and empty, %randombrother% squatting beside the remains. %They_randombrother% nods.%SPEECH_ON%Well, that\'s a sorry way to go. Broke and even more broke.%SPEECH_OFF%You nod back and then holler at the men to pack their things. It\'s time to return to your employer and collect your pay.}";
		});
		::Legends.Screens.hook(this, "Victory", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_130.png[/img]{Fighting the lindwurms was like taking a butterknife and jabbing it into a basket of vipers. They fought like something from another world, hissing and spewing and biting, but they were no match for the %companyname%\'s resolve and skill. You have the men scalp and skin the creatures and ready them for a return to %employer% for a well earned payday. | The lindwurms lay in well earned ruin. Your company goes about poking the corpses at a distance, making sure the bastards are truly dead. A few gargle and flip over, but that\'s about the last of their living issuances. You order the overgrown lizards scalped and skinned. %employer% will be expecting proof, after all. | You crouch beside a lindwurm and take your hand over its skin. The way you figure, the scales are long and sharp enough to cut your fingers off if jammed in between the wedges. You then stand akimbo over the head and stare into its maw, getting a measure of its teeth with your hands and its gullet with the steel of your sword. %randombrother% comes to your side and asks what they\'re to do next. You unsheathe your sword from the lindwurm\'s throat, wipe it clean, and sheathe it proper. You order the men to skin a few of the beasts and ready a return to %employer%. | The battle over, you have the lindwurms skinned and dressed for anything of value. It isn\'t long for the field to stink of the skinks, the overly large lizards being shorn of the scales that once protected them. Their sickly, glistening musculature bared for all to see, a nakedness and vulnerability is wrought upon the once and always monsters. %randombrother% snorts and runs a sleeve beneath %their_randombrother% nose. %They_randombrother% nods at %their_randombrother% handiwork.%SPEECH_ON%Nothing more than a common creature, just a shade larger than it ought to be.%SPEECH_OFF%Damn right. You order the men to collect what they\'ve got and ready a return to %employer%.}";
		});
		::Legends.Screens.hook(this, "Success", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_77.png[/img]{You enter %employer%\'s room dragging in some lindwurm flesh. %They_employer% looks up from %their_employer% desk, eyes the scales and long sleeve of reptilian skin, glances at you, then glances at %their_employer% paymaster and gives a steady nod. The paymaster takes a satchel of crowns and hands them over. %employer% returns to %their_employer% work, addressing you as %they_employer% writes with a quill.%SPEECH_ON%Good work, sellsword. Reports of the bastards have died off in total, so I wager our money here has been put to good use. Leave the skin. I\'ve a man who can fix up some mean boots with it.%SPEECH_OFF%Did the %companyname% just work to get this fool new boots? You shake your head and make your leave. | %employer% welcomes you and your booty, a long, scratchy, scaly, scraping piece of lindwurm skin. You heave it across the floor where it skitters like a stiff leather jacket. The mayor nods.%SPEECH_ON%Very, very well done, good sir! Most excellent. Your pay, as promised.%SPEECH_OFF%The %person_employer% hands you a satchel heavy with well earned crowns. | %employer% is found warming %themselves_employer% beside a fire. %They_employer% turns around in the seat to see the lindwurm flesh you have brought in with you. The mayor nods.%SPEECH_ON%Quite alright work, sellsword. I\'m curious, do the lizard bastards grow their limbs back? I\'ve heard tales of the reptilian sort carrying such tricks.%SPEECH_OFF%You shrug and state each creature was slain with as much scientific curiosity a good sword can muster. %employer% purses %their_employer% lips.%SPEECH_ON%Ah. Right. Well your pay is in the corner there, as much as agreed upon.%SPEECH_OFF%%They_employer% returns to the fire, cozying %themselves_employer% up in a blanket and sipping at the lip of a steamy mug. | %employer% is found outside and surrounded by raucous peasants. You yell over the crowd and display the lindwurm skin which you\'ve brought. The crowd quiets for a moment, whispers amongst its numbers, then returns to shouting. You purse your lips and elbow your way into the mob and demand the pay which you are owed. %employer% yells at the peons to spread out and let %them_employer% breathe. While two guards stand close, %they_employer% hands you a leather satchel.%SPEECH_ON%Good work, sellsword. If it ain\'t all there feel free to come back and kill me. I won\'t mind, not on this damned day.%SPEECH_OFF%As you take the satchel and leave, a peasant jabs his finger at the mayor.%SPEECH_ON%Tellin\' ya, that damned bastard, my supposed \'neighborly neighbor\', stole my birds and if he don\'t return them I\'mma burn his whole farm to the farkin\' ground!%SPEECH_OFF%}";
		});
		::Legends.Screens.hook(this, "Failure", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_43.png[/img]{You find %employer% in %their_employer% room and it is full of guards. Not sure what is going on, you display the lindwurm\'s flesh to the mayor and demand your pay. %Their_employer% fingers clap together before fanning forward like a lumber saw.%SPEECH_ON%I don\'t think that will be happening, sellsword. I don\'t know where you got that goddam skinsuit you\'re carrying, and trust me I can tell it\'s old as shite and not some new flay, but I\'m still getting reports of lizards tearing the hinterlands a new arshole so if you don\'t mind, please kindly leave this town before I sic a whole different predator upon ya.%SPEECH_OFF%Taking a deep breath, you eye the guards. There\'s too many to fight off. %employer% sighs.%SPEECH_ON%If it\'s your honor you\'re thinking to protect, don\'t. I already talked these folks down from ambushing your arse the second you were to walk through that door. I did that out of little respect I have left. Don\'t waste it, hm?%SPEECH_OFF%Fair enough. It is what it is and you\'ve no one else to blame but yourself anyhow. You close the door and take your leave.}";
		});
	}
});
