::mods_hookExactClass("events/events/dlc8/fake_witchhunter_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "D", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_141.png[/img]{%witchhunter% comes forward. %They_witchhunter% says the man in the black hat is a known fraud in witch hunting circles.%SPEECH_ON%We\'ve been looking for this man for some time as his lies sully the name of our profession. I\'ve long been looking for a chance to get this scalp.%SPEECH_OFF%Before you can say another word, %witchhunter% walks through the crowd and emerges on the other end with one of the peasant\'s pitchforks in hand and promptly drives it through the faux hunter\'s leg. The man bends over screaming. The faux hunter wheels up with the crossbow, but %witchhunter% catches it by the barrel and rides it upward where the shot harmlessly launches into the sky. %They_witchhunter% yanks the crossbow away, yelling that it does not belong to him, and %they_witchhunter% announces to the crowd that the man is a charlatan. %They_witchhunter% throws him to the ground, telling the crowd to do whatever it is they wish. They descend on the liar, though the extent of torture is hard to see through the excited ranks of laity. %witchhunter% returns with the crossbow, turning it one way and another. It is the most incredible weapon you\'ve seen in some time. The witch hunter explains.%SPEECH_ON%This belonged to a guildmaster in the region. We believe this fool murdered him, took his clothes, and has been walking around pretending the part ever since. If his screams disturb you, captain, just remember he has burned countless innocents and stolen countless crowns from the desperate and confused. Fark him.%SPEECH_OFF%You stare over the %person_witchhunter% and into the crowd. You can just make out the man being hoisted onto the pyre and the early smoke of fires getting their start.}";
		});
	}
});
