::mods_hookExactClass("events/events/dlc8/incense_trade_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "D", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_143.png[/img]{%bellydancer% the belly dancer steps forward, peers into the snow, and rather unexpectedly wonders aloud if that is %their_dancer% father. The crazed man comes forward, his black kites following after him like buzzards in the tailwind of the doomed, then his face lights up and the two embrace. The man is apparently %bellydancer%\'s long lost father, an incense merchant who had headed far north only to be ambushed and enslaved by the savage barbarians there whom he has since escaped. He smiles madly.%SPEECH_ON%It had been so long since I had seen good incense I could smell your wagon from miles away. My wife, your mother, %bellydancer%, how is she?%SPEECH_OFF%The belly dancer\'s smile fades. %They_dancer% mentions that she held out hope for as long as she could. The kite-kitted man nods solemnly, but also expectedly. He says it wouldn\'t be right for her to be married to a specter of what once was, and that he himself, with no hope of making a return home, moved on as well. The man pulls out an ornate weapon with a blade unlike anything you\'ve seen before. He says that it is a long held relic of the family, and that he kept it buried and safe all his years in the north.%SPEECH_ON%Best you take it and make use of it before one of the savages here eats me and uses it as a toothpick.%SPEECH_OFF%The man smiles fondly and the two embrace for a time. Curious, you ask him why the kites. He responds that they are tools of fear meant to ward off dangerous animals and the like, including the more superstitious of the barbarians. You bid the man goodbye and suggest to %bellydancer% that %they_dancer% can leave if %they_dancer% needs to as well, but %they_dancer% shakes %their_dancer% head.%SPEECH_ON%The %child_dancer% and father mustn\'t share the gilded path, for we know that we shall be together at its end as we were at its beginning.%SPEECH_OFF%%They_dancer% says a few words to %their_dancer% father in %their_dancer% native tongue, and then the two depart and that is that.}";
		});
	}
});
