::mods_hookExactClass("events/events/dlc8/shadow_dissection_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_184.png[/img]{%anatomist% the anatomist looks up from the campfire, %their_anatomist% face squirming with shadows as the flames rise and fall.%SPEECH_ON%Our shadows are but cuts upon the world which wound and mend all in one stride of black, dissecting the earth with our presence and self-same shaded presence in such a transient manner that it can\'t but be a preview of our stay here. But does the shadow think of dissecting you? Does it wish to free others which are like itself? Surely it is not alone. Surely our insides have shades. Do they cast tricks of themselves against our inner walls? What of when we sleep, are these things set against us from within or do they escape out into the world and wander? Are they the guards against our own minds, departing us in the night and leaving us to the horrors of dreamscapes which are surely present when we are awake? What distills the truth of the morning light better, than our shadow cast along the ground, and the fleeting memories of that which it has returned to ward away?%SPEECH_OFF%One of the sellswords stares at %them_anatomist%.%SPEECH_ON%What?%SPEECH_OFF%The rest of the sellswords scoff.%SPEECH_ON%Hey man, we just wanna make like dicks and slags and shite. Check this out, I\'m %anatomist%\'s shadow. Blah blah blah blah!%SPEECH_OFF%The man mimes a mouth opening and closing over and over again as the company laughs.}";
		});
		::Legends.Screens.hook(this, "C", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_03.png[/img]{%cultist% the cultist leans toward the fire, %their_cultist% face almost touching the flames. The men glance at %them_cultist% as %their_cultist% eyes go wide, the wetness drying and peeling back until blood veins grow fat on the white. %They_cultist% leans back.%SPEECH_ON%Shadows are but ambassadors of the greater dark.%SPEECH_OFF%The campfire crackles and the %person_cultist%\'s shadow blossoms against the priory wall, and for a moment the company sees something else in that black, something twisted and leaning in, an entity not at all at the behest of %cultist%\'s shape. As the fires die down, the shadow cuts to pieces and draws away into the greater night, and only the cultist\'s own shadowed self remains, flickering uncertainly against the priory walls.}";
		});
		::Legends.Screens.hook(this, "D", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_40.png[/img]{Standing up, %monk% the %monk_background_name% makes an appeal to the old gods. %They_monk% has one hand to %their_monk% chest as the other swings upward as though in a great oratory offering.%SPEECH_ON%It is not the shadows we should mind, but the fire which has produced them, for it is the flame which the gods have bestowed upon us, such that we may carry the day into the night, and make our productive habits unending, and our allegiance to that which is good unerring.%SPEECH_OFF%The men shout \'hear hear!\'}";
		});
		::Legends.Screens.hook(this, "E", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_82.png[/img]{One of the mercenaries stands up and points across the campfire and announces that %mercenary% has the scariest shadow of them all. The large sellsword looks over as if annoyed %their_mercenary% name was spoken aloud. %They_mercenary% grits %their_mercenary% teeth and slowly raises %their_mercenary% hands and the rest of the company fearfully rears back. %mercenary% laces %their_mercenary% fingers and puts the thumbs out.%SPEECH_ON%This is a chicken. See?%SPEECH_OFF%The men glance at the shadows on the wall. It looks absolutely nothing like a chicken, but nobody dares to say that. They all nod and agree.%SPEECH_ON%Frankly, %mercenary%, that is the best cock I\'ve ever seen.%SPEECH_OFF%The men roar with laughter, but %mercenary% gets to %their_mercenary% feet and the laughter stops.%SPEECH_ON%I said it was a chicken, didn\'t I?%SPEECH_OFF%The other man nods hurriedly and agrees it was indeed a chicken. Tensions settle down, but the shadow games are effectively over.}";
		});
		::Legends.Screens.hook(this, "G", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_26.png[/img]{%minstrel% the minstrel stands up, %their_minstrel% head cocked to a side, %their_minstrel% walk a shuffling amble, %their_minstrel% eyes affixed to %their_minstrel% own shadow upon the priory wall, every step %they_minstrel% takes drawing it smaller and smaller yet. %They_minstrel% stares at the shadow as though it were a body, and %their_minstrel% closing in on it was akin to that of solving who murdered it. Suddenly, %they_minstrel% bolts upright, hands to %their_minstrel% hips.%SPEECH_ON%By the gods, men, I\'ve got it figured out! My shadow is an absolute womanizer! A scapegrace smellsmock. He\'s got a big hammer in his pants, and every woman\'s a nail! A philanderer, he is! And a drunk, a pitiful sot. And...and a thief! Filching crowns from the filthy, this he cannot resist. And a little prankster, a little rat filled with devilments. Just the other day, my shadow took a shit in %othersellsword%\'s boot! I couldn\'t believe it!%SPEECH_OFF%%othersellsword% jumps to %their_otherbro% feet, knocking over the fire and spewing embers that seem to twirl and twist on the laughter of the men. %They_otherbro% comes forward.%SPEECH_ON%I knew that wasn\'t no farkin\' dogshite you bastard! What sorta man shits in another man\'s boots!%SPEECH_OFF%The sellsword slips and falls which arises applause from the company, and the minstrel delicately prances away, %their_minstrel% shadow bidding goodbye with a kiss and wave.}";
		});
		::Legends.Screens.hook(this, "H", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_51.png[/img]{As the men bandy back and forth making shadows, %killer%, the alleged killer on the run, walks up to the camp carrying armfuls of jewelry and other goods, their metals glistening with crimson sheens. %They're_killer% murmuring to %themselves_killer%, but then suddenly stops and looks at the rest of the company.%SPEECH_ON%Oh. You guys are still awake? I was just, uh, out. Doing things.%SPEECH_OFF%There\'s blood on %their_killer% face and caked under %their_killer% fingernails. Sensing %themselves_killer% in trouble, %they_killer% drops the goods.%SPEECH_ON%These are for the company, of course. I\'m just so, uh, thankful that you all took me in. Thought I\'d repay the favor, you know?%SPEECH_OFF%The men stare at the goods. You ask the %person_killer% if someone is going to come looking for those items. %They_killer% grins.%SPEECH_ON%No sir, of course not. I made sure of it. Oh captain, did I make sure of it, heh, heh, heh.%SPEECH_OFF%You tell the %person_killer% to put the goods into inventory, but to be sure to clean them up first. As %they_killer% walks away, the rest of the men quietly exchange glances. There\'s no more shadow games left to play, it seems.}";
		});
	}

	local onPrepareVariables = o.onPrepareVariables;
	o.onPrepareVariables = function( _vars ) {
		onPrepareVariables(_vars);
		_vars.push([
			"monk_background_name",
			this.m.Monk != null ? this.m.Monk.m.Background.m.Name.tolower() : ""
		]);
	}
});
