::mods_hookExactClass("events/events/dlc8/strange_scribe_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_31.png[/img]{While in %townname%, you are approached by a person you had seen around one of the noblemen in the area. %They_dude% is wearing a black cloak and %they_dude% keeps %their_dude% face deep in the cowl. %They_dude% is the definition of suspicious. Naturally, %anatomist% the anatomist sets %their_anatomist% eyes on %them_dude% as though %they_dude% were one of %their_anatomist% objects of scientific observation. The %person_dude% bows.%SPEECH_ON%I have come with great respect for the work you do, %anatomist%. We have read many of your texts.%SPEECH_OFF%You put a hand on your sword and wait to see where this is going. The %person_dude% continues.%SPEECH_ON%We would like to invite you for a meal and to discuss matters of bodily import a little more...deeply.%SPEECH_OFF%Stepping between them, you ask who this \'we\' is. The %person_dude% states that %they_dude% is with a group of scribes and scholars who study matters of the human body, as well as the bodies who have comported themselves well to the nature of their bestial tasks, which is to say they study the world\'s monsters.%SPEECH_ON%We, of course, have a particular interest in the beasts which are man himself...after he has lost what he himself is.%SPEECH_OFF%With so much intrigue flitting about, you\'re not surprised that the anatomist wishes to go with the strange scribe.}";
			local start = _screen.start;
			_screen.start = function (_event) {
				start(_event);
				local roster = this.World.getTemporaryRoster();
				_event.m.Dude = roster.create("scripts/entity/tactical/player");
				_event.m.Dude.setStartValuesEx(["minstrel_background"]);
				_event.m.Dude.getBackground().m.RawDescription = "{%name% was found deploying %their% minstrel talents in street scamming. Vouched for by a fellow minstrel, %they% joined the %companyname% to seek out a life on the road. Hopefully the charlatan-turned-sellsword will be able to \'fake it til %they% makes it\', as %they% likes to say a little too often.}";
				_event.m.Dude.getBackground().buildDescription(true);
			}
		});
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_31.png[/img]{If %anatomist% is going anywhere in this town, %they_anatomist% sure as shit isn\'t going alone. You tag along, your hand never leaving your sword. The strange %person_dude% invites you to a beautiful stone house, candlelight beaming from every window. Inside, you are quickly ushered to what should be a dinner table, but instead find slabbed across it a pale man whose skin is barely hanging on. The strange scribe bows like a chef who has delivered %their_dude% finest meal.%SPEECH_ON%We believe this is a wiederganger, a man who hath died yet walks again.%SPEECH_OFF%The strange scribe rolls up %their_dude% sleeve and holds it over the decrepit corpse. Its maw suddenly juts left to right, the jaw unhinged, its white eyes rolling. %anatomist% merely leans back and mentions that it is \'interesting.\' The two begin to talk, while you nervously finger the hilt of your sword in case this \'wiederganger\' takes an interest in escaping. When the two are finished, %anatomist% and the scribe take out quill pens and put their signatures in each other\'s tomes, all the while congratulating each other on their work.\n\nThe whole affair has you cringing, and you notice what looks like a bead of sweat on the wiederganger\'s brow, but before you can comment you are ushered out from the home. Whatever they discussed, the anatomist is renewed with energy. %They_anatomist% speaks gingerly.%SPEECH_ON%The creature was a fraud, of course, don\'t think I did not notice that. However, this has given me plenty insight into the inventive depths of the locals. There\'s something to be preened from such creativity, being that one\'s imagination draws surreptitiously from the sublime and real, and makes inferences on what it intuits yet knows not how to describe with scientific distinction. Even in the mire and fog of regional superstition and legerdemain I can make great advances.%SPEECH_OFF%Well, alright. You mention that you knew it was a fraud because the supposedly dead cretin was sweating. The anatomist nods, and says you might not have an eye for diagnostic inquiry, but the street smarts are well enough for perspicuous scrying. You simply nod, hoping %they_anatomist% meant well by whatever that means.}";
		});
		::Legends.Screens.hook(this, "C", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_97.png[/img]{You agree to let the anatomist go, but you\'re coming along. This draws the attention of the strange scribe. %They_dude% seems reluctant about the matter now, having lost the energy which %they_dude% had in his initial invitations. As you round a corner, %they_dude% makes a sharp birdlike call, and a few men step out and you draw your sword and push %anatomist% back. One makes an attempt to attack. You\'re not in much fighting shape these days, but with a quick parry you knock him back and dissuade him of further attack. The scribe and %their_dude% minions then depart in a hurry, saying you\'re not worth it. %anatomist% looks disappointed.%SPEECH_ON%Ah, I see. So it was a scam, an endeavor that was as creative as it was criminal.%SPEECH_OFF%Looking around, you realize that your coinpurse is gone. You look over just in time to see a child holding it, then throwing it skyward to be caught by another child hanging on some gutters. %anatomist% stands beside you, looking up, fascinated by the engineering effort put in by the scamps.%SPEECH_ON%It seems where one offender fails, another may take his place. So it is that by attrition the criminals may succeed. Interesting.%SPEECH_OFF%The anatomist suddenly realizes %they_anatomist% also is a bit light on the hip and sees that %their_anatomist% purse, too, has been yoinked. You look past %them_anatomist% to see yet another child running off like a rat with its cheese. Another child runs past and tries to pickpocket you when there\'s nothing left to steal. Angered by his empty hands, the boy yells back.%SPEECH_ON%Get a job!%SPEECH_OFF%Sighing, you say it\'s probably time to head back to the company.}";
		});
		::Legends.Screens.hook(this, "D", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_51.png[/img]{You agree to let %anatomist% and the strange scribe talk, but before you can even head down the street %minstrel% the minstrel steps forth, grinning and pointing.%SPEECH_ON%%fakescribe%! What in the hells are you doing these days? This some new scam you\'ve got up your sleeve, huh?%SPEECH_OFF%The strange scribe clears %their_dude% throat. %They_dude% throws %their_dude% hands out, and clears %their_dude% throat again, %they_dude% seems ready to speak deeply to some subject, but then sighs and throws back %their_dude% cloak. A youngish and not at all scholarly looking fellow is revealed. %They_dude% shakes %their_dude% head.%SPEECH_ON%Life\'s been rough in the big city, %minstrel%. How are you doing?%SPEECH_OFF%The two chat for a time while you and %anatomist% look on bewildered. Eventually, the two minstrels turn to you, %minstrel% leading the way.%SPEECH_ON%Captain, this is %fakescribe%. %They're_dude% on hard times out here in %townname%. What say %they_dude% come along into the %companyname%? %They're_dude% a lot like me, a shitass fighter, but a %person_dude% of spunk, of moxy, a %person_dude% who has what it takes if merely given the time to find it, especially if there\'s a woman involved.%SPEECH_OFF%%fakescribe% shakes %their_dude% head.%SPEECH_ON%Ehem, ehh, with them I never, uh, find it.%SPEECH_OFF%}";
			_screen.Options[0].Text = "Sure, %they_dude% can come along.";
			_screen.start = function (_event) {
				this.Characters.push(_event.m.Minstrel.getImagePath());
				this.Characters.push(_event.m.Dude.getImagePath());
			};
		});
		::Legends.Screens.hook(this, "E", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_51.png[/img]{You take the minstrel along free of any hiring charges. %anatomist% the anatomist looks a little sullen about the whole affair, saying that %they_anatomist% longs for rare knowledge, yet all this world seems to have on offer are scams and falsities. Smiling, you tell %them_anatomist% to consider this street knowledge. %They_anatomist% smiles as well.%SPEECH_ON%Yes, perhaps I should acquire more of these...street smarts.%SPEECH_OFF%No, street knowledge. \'Street smarts\' sounds ridiculous.}";
		});
		::Legends.Screens.hook(this, "F", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_12.png[/img]{You agree to let the anatomist and strange scribe have their conversations, yourself tagging along. The %person_dude% takes you to the head of an alleyway which is considerably suspicious. %They_dude% turns around with a wild grin on %their_dude% face and %they_dude% slowly starts to unsheathe a dagger from %their_dude% sleeve, and then suddenly a knife stabs through %their_dude% face, a glimmer of steel winking in %their_dude% mouth. As %they_dude% gargles, another knife comes in and cuts %their_dude% throat in a quick slash. %killer%, the alleged killer on the run, appears from the alleyway.%SPEECH_ON%\'Ello captain and, eh, anatomist? Mortician? This \'ere was a murderer. And an encroacher, encroaching on my...uh...affairs.%SPEECH_OFF%%They_killer% drops the body to the ground and starts stripping away the cloak to reveal that this supposed scribe was in fact well armed and armored. The killer cuts off one of the ears and pockets it, then nods.%SPEECH_ON%Hey, looks like we got some free gear, eh? We should probably hide the body though. This %person_dude% puts up a great front of eminence and some may find %their_dude% absence worth investigation.%SPEECH_OFF%You know not what or who to trust on the matter, but a dead body bleeding out all over your boots tends to look bad no matter the circumstances. You hide the body, after happily stripping it the gear from it, of course. %anatomist% seems leery of %killer%. %They_anatomist% mentions that the killer on the run\'s tone of voice seemed to be one of immediately produced conjecture or, as the layman puts it, \'acting.\' Seeing as how what\'s done is done, you simply tell %them_anatomist% to help carry the gear back to inventory.}";
		});
		::Legends.Screens.hook(this, "G", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_31.png[/img]{You say the situation is far too suspicious to risk. %anatomist% says that all knowledge seems suspicious to the laity. You tell %them_anatomist% that this \'layman\' knows enough to smell a rat and that is that. The anatomist is upset, but you\'d rather %they_anatomist% be agitated than dead.}";
		});
	}

	local onClear = o.onClear;
	o.onClear = function () {
		onClear();
		::World.getTemporaryRoster().clear();
	}
});
