::mods_registerMod("mod_99_legends_complete_ja_v20_safe_from_v18", 2.0, "Legends Complete Japanese Patch v20 SAFE from v18");
::mods_queue("mod_99_legends_complete_ja_v20_safe_from_v18", null, function() {
  local gt = this.getroottable();
  local M = {};
  M["Weapon coated with vattghern poison"] <- "ヴァットゲルン毒を塗った武器";
  M["Reinforced Mutation: Alpha Beast"] <- "強化変異：群れの長";
  M["Reinforced Mutation: Skin Ghoul"] <- "強化変異：肉喰らいの皮膚";
  M["Weapon coated with acidic blood"] <- "酸性血液を塗った武器";
  M["Reinforced Mutation: Direwolf"] <- "強化変異：狼獣";
  M["Reinforced Mutation: Lindwurm"] <- "強化変異：リンドヴルム";
  M["120. Combat Rhythm (passive)"] <- "120. 戦闘リズム（パッシブ）";
  M["Reinforced Mutation: Schrat"] <- "強化変異：シュラート";
  M["Reinforced Mutation: Spider"] <- "強化変異：蜘蛛";
  M["Reinforced Mutation: Unhold"] <- "強化変異：ウンホルト";
  M["Reinforced Mutation: Hexen"] <- "強化変異：ヘクセン";
  M["Reinforced Mutation: Alp"] <- "強化変異：アルプ";
  M["Thirsty Vampire (Night)"] <- "飢えた吸血鬼（夜）";
  M["Vattghern Super Poison"] <- "ヴァットゲルン猛毒";
  M["Weakened Vampire (Day)"] <- "弱体化した吸血鬼（昼）";
  M["Mutation: Necrosavant"] <- "変異：ネクロサヴァント";
  M["Mutation: Necromancy"] <- "変異：死霊術";
  M["Sign Caster Cooldown"] <- "印の再使用待ち";
  M["Hate for Greenskins"] <- "グリーンスキン嫌い";
  M["Ifrit\\'s Durability"] <- "イフリートの耐久";
  M["Scavenger\\'s Surge!"] <- "屍漁りの高揚！";
  M["120. Combat Rhythm"] <- "120. 戦闘リズム";
  M["Fear of Greenskins"] <- "グリーンスキン恐怖症";
  M["Ifrit's Durability"] <- "イフリートの耐久";
  M["Mentally Exhausted"] <- "精神疲労";
  M["Mutation: Basilisk"] <- "変異：バジリスク";
  M["Protected by a Hex"] <- "呪詛の守護";
  M["Scavenger's Surge!"] <- "屍漁りの高揚！";
  M["Serpent\\'s Finesse"] <- "大蛇の身のこなし";
  M["Alp\\'s Resistance"] <- "アルプの耐性";
  M["Basilisk\\'s Focus"] <- "バジリスクの集中";
  M["Beastly Endurance"] <- "獣の持久力";
  M["Colossal Strength"] <- "巨躯の怪力";
  M["Goblin\\'s Cunning"] <- "ゴブリンの悪知恵";
  M["Incapable Wielder"] <- "扱えぬ担い手";
  M["Increased Insight"] <- "洞察強化";
  M["Mutation: Serpent"] <- "変異：大蛇";
  M["Mutation: Undeath"] <- "変異：不死";
  M["Orcish Aggression"] <- "オークの猛攻";
  M["Serpent's Finesse"] <- "大蛇の身のこなし";
  M["Alp's Resistance"] <- "アルプの耐性";
  M["Basilisk's Focus"] <- "バジリスクの集中";
  M["Curse Of Undeath"] <- "不死の呪い";
  M["Ethereal Attacks"] <- "霊体攻撃";
  M["Etherial Attacks"] <- "霊体攻撃";
  M["Goblin's Cunning"] <- "ゴブリンの悪知恵";
  M["Learning to Read"] <- "読み書き学習中";
  M["Mutation: Donkey"] <- "変異：ロバ";
  M["Mutation: Goblin"] <- "変異：ゴブリン";
  M["Mutation: Schrat"] <- "変異：シュラート";
  M["Mutation: Spider"] <- "変異：蜘蛛";
  M["Mutation: Spirit"] <- "変異：霊体";
  M["Mutation: Unhold"] <- "変異：ウンホルト";
  M["Orcish Agression"] <- "オークの猛攻";
  M["Sand in the Eyes"] <- "目潰しの砂";
  M["Spider\\'s Glands"] <- "蜘蛛の腺";
  M["Trapped By Yrden"] <- "イャーデンの罠";
  M["Vattghern Poison"] <- "ヴァットゲルン毒";
  M["58. Shield Bash"] <- "58. 盾打撃";
  M["Adrenaline Rush"] <- "アドレナリンラッシュ";
  M["Ghoulish Hunger"] <- "肉喰らいの飢え";
  M["Hate for Beasts"] <- "獣嫌い";
  M["Hate for Undead"] <- "アンデッド嫌い";
  M["Mutation: Beast"] <- "変異：獣";
  M["Mutation: Hexen"] <- "変異：ヘクセン";
  M["Mutation: Ifrit"] <- "変異：イフリート";
  M["Mutation: Venom"] <- "変異：毒腺";
  M["Poisoned by Rot"] <- "腐敗毒";
  M["Spider's Glands"] <- "蜘蛛の腺";
  M["Unhold\\'s Vigor"] <- "ウンホルトの活力";
  M["Vampire: Night!"] <- "吸血鬼：夜！";
  M["Fear of Beasts"] <- "獣恐怖症";
  M["Fear of Undead"] <- "アンデッド恐怖症";
  M["Mutant Poison!"] <- "変異毒！";
  M["Mutation: Wurm"] <- "変異：リンドヴルム";
  M["Pack Mentality"] <- "群れの本能";
  M["Unhold's Vigor"] <- "ウンホルトの活力";
  M["Combat Rhythm"] <- "戦闘リズム";
  M["Mutation: Alp"] <- "変異：アルプ";
  M["Mutation: Dog"] <- "変異：犬";
  M["Mutation: Orc"] <- "変異：オーク";
  M["Mutation: Rot"] <- "変異：腐敗";
  M["Short Sighted"] <- "近眼";
  M["Bloodthirsty"] <- "血に飢えた";
  M["Fainthearted"] <- "気弱";
  M["Foul Stench!"] <- "悪臭！";
  M["Miasma Cloud"] <- "瘴気雲";
  M["Vampire: Day"] <- "吸血鬼：昼";
  M["Venom Glands"] <- "毒腺";
  M["Wurm\\'s Acid"] <- "リンドヴルムの酸";
  M["Aura of Rot"] <- "腐敗のオーラ";
  M["Night Blind"] <- "夜盲症";
  M["Quen Shield"] <- "クエンの盾";
  M["Shield Bash"] <- "盾打撃";
  M["Team Player"] <- "チームプレイヤー";
  M["Venom Gland"] <- "毒腺";
  M["Wurm's Acid"] <- "リンドヴルムの酸";
  M["Clubfooted"] <- "内反足";
  M["Determined"] <- "意志堅固";
  M["Eagle Eyes"] <- "鷹の目";
  M["Gluttonous"] <- "大食い";
  M["Iron Lungs"] <- "鉄の肺";
  M["Irrational"] <- "非合理";
  M["No Shield!"] <- "盾なし！";
  M["Asthmatic"] <- "喘息持ち";
  M["Burning!!"] <- "炎上！！";
  M["Deathwish"] <- "死にたがり";
  M["Dexterous"] <- "器用";
  M["Impatient"] <- "せっかち";
  M["Lone Wolf"] <- "一匹狼";
  M["Paralyzed"] <- "麻痺";
  M["Pessimist"] <- "悲観的";
  M["Vampirism"] <- "吸血性";
  M["Barkskin"] <- "樹皮の肌";
  M["Beguiled"] <- "魅了";
  M["Drunkard"] <- "酒浸り";
  M["Fearless"] <- "恐れ知らず";
  M["Hesitant"] <- "躊躇いがち";
  M["Optimist"] <- "楽観的";
  M["Paranoid"] <- "偏執的";
  M["Survivor"] <- "生存者";
  M["Dastard"] <- "臆病者";
  M["Feasted"] <- "飽食";
  M["Unlucky"] <- "不運";
  M["Bright"] <- "聡明";
  M["Clumsy"] <- "不器用";
  M["Craven"] <- "腰抜け";
  M["Greedy"] <- "強欲";
  M["Strong"] <- "強健";
  M["Brave"] <- "勇敢";
  M["Cocky"] <- "うぬぼれ屋";
  M["Lucky"] <- "幸運";
  M["Quick"] <- "俊敏";
  M["Tough"] <- "頑丈";
  M["Dumb"] <- "鈍才";
  M["Huge"] <- "巨体";
  M["Tiny"] <- "小柄";
  M["Fat"] <- "肥満";
  M["Hex"] <- "呪い";
  local rep = function(x) { if (x == null || typeof x != "string") return x; return M.rawin(x) ? M[x] : x; };
  local patchTable = null;
  patchTable = function(t, depth = 0) {
    if (t == null || depth > 4) return;
    local typ = typeof t;
    if (typ != "table" && typ != "array") return;
    foreach(k,v in t) {
      if (typeof v == "string") { local rv = rep(v); if (rv != v) t[k] = rv; }
      else if ((typeof v == "table" || typeof v == "array") && depth < 4) patchTable(v, depth + 1);
    }
  };
  try { if ("Const" in gt && "Strings" in gt.Const) patchTable(gt.Const.Strings); } catch(e) {}
  try { if ("Const" in gt && "Perks" in gt.Const) patchTable(gt.Const.Perks); } catch(e) {}
  local replaceText = function(text, a, b) { if (text == null || typeof text != "string") return text; local pos = text.find(a); while(pos != null) { text = text.slice(0,pos) + b + text.slice(pos + a.len()); pos = text.find(a); } return text; };
  try {
    if ("Const" in gt && "Strings" in gt.Const && "FT" in gt.Const.Strings && "SkillList" in gt.Const.Strings.FT) {
      local sl = gt.Const.Strings.FT.SkillList;
      sl = replaceText(sl, "120. Combat Rhythm (passive)", "120. 戦闘リズム（パッシブ）");
      sl = replaceText(sl, "120. Combat Rhythm", "120. 戦闘リズム");
      sl = replaceText(sl, "58. Shield Bash", "58. 盾打撃");
      gt.Const.Strings.FT.SkillList = sl;
    }
  } catch(e) {}
});
