::mods_registerMod("mod_99_legends_complete_ja_v16_extra", 1.6, "Legends Complete Japanese Patch v16 Extra Repair");
local gt = this.getroottable();
local replaceText = function(text, substr, replace) { if (substr == "") return text; local right = text; local ret = ""; local i = right.find(substr); while (i != null) { local left = right.slice(0, i); right = right.slice(i + substr.len()); ret = ret + left + replace; i = right.find(substr); } return ret + right; }
local patchFantasyBroSkillListV16 = function() {
 if (!("Const" in gt) || !("Strings" in gt.Const) || !("FT" in gt.Const.Strings) || !("SkillList" in gt.Const.Strings.FT)) return;
 local s = gt.Const.Strings.FT.SkillList;
 s = replaceText(s, "12. Brute Toss (Toss)", "12. 怪力投げ（投げる）");
 s = replaceText(s, "66. Unholy Bless", "66. 不浄の祝福");
 s = replaceText(s, "77. Bite", "77. 噛みつき");
 s = replaceText(s, "1. Accidental Attack", "1. 偶発攻撃");
 s = replaceText(s, "2. Acid Grenade", "2. 酸グレネード");
 s = replaceText(s, "3. Backstab", "3. バックスタブ");
 s = replaceText(s, "4. Bear Trap", "4. ベアトラップ");
 s = replaceText(s, "5. Berserker Charge", "5. 狂戦士の突撃");
 s = replaceText(s, "6. Black Magic Grenade", "6. 黒魔術グレネード");
 s = replaceText(s, "7. Blessing", "7. 祝福");
 s = replaceText(s, "8. Bloodletting Therapy", "8. 瀉血療法");
 s = replaceText(s, "9. Blood Lust", "9. 血の渇望");
 s = replaceText(s, "10. Bribe", "10. 買収");
 s = replaceText(s, "11. Cannon Barrage", "11. 大砲斉射");
 s = replaceText(s, "12. Brute Toss (Set Target)", "12. 怪力投げ（目標指定）");
 s = replaceText(s, "13. Battle Command", "13. 戦闘指揮");
 s = replaceText(s, "14. Concentration", "14. 精神集中");
 s = replaceText(s, "15. Perfect Aimed Throw", "15. 完全照準投擲");
 s = replaceText(s, "16. Battle Cure", "16. 戦場治療");
 s = replaceText(s, "17. Demonize", "17. 悪魔化");
 s = replaceText(s, "18. Devastating Blow", "18. 壊滅打撃");
 s = replaceText(s, "19. Drain Blood", "19. 吸血");
 s = replaceText(s, "20. Earthquake", "20. 地震");
 s = replaceText(s, "21. Electric Shock", "21. 電撃");
 s = replaceText(s, "22. Feast", "22. 貪り食い");
 s = replaceText(s, "23. Fire Ball", "23. ファイアボール");
 s = replaceText(s, "24. Hellfire Grenade", "24. 地獄火グレネード");
 s = replaceText(s, "25. Flame Wave", "25. 炎の波");
 s = replaceText(s, "26. Fling Back", "26. 弾き飛ばし");
 s = replaceText(s, "27. Force of Nature", "27. 大自然の力");
 s = replaceText(s, "28. Wicked Frenzy", "28. 邪悪な狂乱");
 s = replaceText(s, "29. Frost Blast", "29. 凍結爆破");
 s = replaceText(s, "30. Gale Force", "30. 疾風怒濤");
 s = replaceText(s, "31. Great Awakening", "31. 大覚醒");
 s = replaceText(s, "32. Headbutt", "32. 頭突き");
 s = replaceText(s, "33. Magical Healing", "33. 魔法治療");
 s = replaceText(s, "34. Hide", "34. 隠れる");
 s = replaceText(s, "35. Holy Spear", "35. 聖槍");
 s = replaceText(s, "36. Judo Throw", "36. 柔道投げ");
 s = replaceText(s, "37. Kick", "37. 蹴り");
 s = replaceText(s, "38. Line Breaker", "38. 戦線突破");
 s = replaceText(s, "39. Magical Lute Song", "39. 魔法のリュート歌");
 s = replaceText(s, "40. Thunderstorm", "40. 雷嵐");
 s = replaceText(s, "41. Forced March", "41. 強行軍");
 s = replaceText(s, "42. Mark", "42. 標的指定");
 s = replaceText(s, "43. Miracle", "43. 奇跡");
 s = replaceText(s, "44. Stealing", "44. 盗み");
 s = replaceText(s, "45. Multi Shot", "45. 連射");
 s = replaceText(s, "46. Penetrating Shot", "46. 貫通射撃");
 s = replaceText(s, "47. Pincer Thrust", "47. 挟撃突き");
 s = replaceText(s, "49. Abyssal Grab", "49. 深淵の掴み");
 s = replaceText(s, "48. Telekinetic Explosion", "48. 念動爆発");
 s = replaceText(s, "50. Purifying Flame", "50. 浄化の炎");
 s = replaceText(s, "51. Extreme Weather", "51. 極端な天候");
 s = replaceText(s, "52. Courage Boost", "52. 勇気鼓舞");
 s = replaceText(s, "53. Boulder Throw", "53. 岩投げ");
 s = replaceText(s, "54. Throw Dirt", "54. 土投げ");
 s = replaceText(s, "55. Banshee Scream", "55. バンシーの悲鳴");
 s = replaceText(s, "56. Shield Guard", "56. 盾護衛");
 s = replaceText(s, "57. Shadow Walk", "57. 影歩き");
 s = replaceText(s, "58. 盾打撃", "58. シールドバッシュ");
 s = replaceText(s, "59. Shockwave", "59. 衝撃波");
 s = replaceText(s, "60. Cursed Words", "60. 呪詛の言葉");
 s = replaceText(s, "61. Serpent Bind", "61. 蛇縛り");
 s = replaceText(s, "62. Double Edge", "62. 諸刃");
 s = replaceText(s, "63. Storm Fury", "63. 嵐の怒り");
 s = replaceText(s, "64. Fury Strike", "64. 怒りの一撃");
 s = replaceText(s, "65. Summon Fiend", "65. 悪鬼召喚");
 s = replaceText(s, "66. Raise Dead", "66. 死者蘇生");
 s = replaceText(s, "67. Summon Spirit Wolf", "67. 霊狼召喚");
 s = replaceText(s, "68. Forced Swap", "68. 強制入替");
 s = replaceText(s, "69. Grappling", "69. 組み付き");
 s = replaceText(s, "70. Tai Chi Weapon Form", "70. 太極武器術");
 s = replaceText(s, "71. Silent Takedown", "71. 無音制圧");
 s = replaceText(s, "72. Unleash the Rage", "72. 怒り解放");
 s = replaceText(s, "73. War Crime", "73. 戦争犯罪");
 s = replaceText(s, "74. Warcry", "74. 鬨の声");
 s = replaceText(s, "75. Flood Bomb", "75. 洪水爆弾");
 s = replaceText(s, "76. Whirlwind Attack", "76. 旋風攻撃");
 s = replaceText(s, "77. Riding a Giant Wolf", "77. 巨大狼騎乗");
 s = replaceText(s, "78. Point Blank Shot", "78. 至近射撃");
 s = replaceText(s, "79. Agile Killer (passive)", "79. 俊敏な殺し屋（パッシブ）");
 s = replaceText(s, "80. Transcendence", "80. 超越");
 s = replaceText(s, "81. Banner Lord (passive)", "81. 軍旗の王（パッシブ）");
 s = replaceText(s, "82. Battle Trance (passive)", "82. 戦闘トランス（パッシブ）");
 s = replaceText(s, "83. Vengeance (passive)", "83. 復讐者（パッシブ）");
 s = replaceText(s, "84. Mana Mastery (passive)", "84. マナ熟達（パッシブ）");
 s = replaceText(s, "85. Challenger (passive)", "85. 挑戦者（パッシブ）");
 s = replaceText(s, "86. Adaptive Counter (passive)", "86. 適応反撃（パッシブ）");
 s = replaceText(s, "87. Desolator (passive)", "87. 荒廃者（パッシブ）");
 s = replaceText(s, "88. Drunken Master (passive)", "88. 酔拳達人（パッシブ）");
 s = replaceText(s, "89. Goblin Weaponology (passive)", "89. ゴブリン武器学（パッシブ）");
 s = replaceText(s, "90. Harden Skin (passive)", "90. 硬化皮膚（パッシブ）");
 s = replaceText(s, "91. Head Collector (passive)", "91. 首級収集者（パッシブ）");
 s = replaceText(s, "92. Poor Man's Weapon (passive)", "92. 貧者の武器（パッシブ）");
 s = replaceText(s, "93. Kensei (passive)", "93. 剣聖（パッシブ）");
 s = replaceText(s, "94. Last Stand (passive)", "94. 最後の抵抗（パッシブ）");
 s = replaceText(s, "95. Lifestealer (passive)", "95. 生命吸収者（パッシブ）");
 s = replaceText(s, "96. Masochism (passive)", "96. マゾヒズム（パッシブ）");
 s = replaceText(s, "97. Oddball (passive)", "97. 変わり者（パッシブ）");
 s = replaceText(s, "98. Orc Weaponology (passive)", "98. オーク武器学（パッシブ）");
 s = replaceText(s, "99. Outsider (passive)", "99. アウトサイダー（パッシブ）");
 s = replaceText(s, "100. Warm-up (passive)", "100. ウォームアップ（パッシブ）");
 s = replaceText(s, "101. Prudence (passive)", "101. 慎重さ（パッシブ）");
 s = replaceText(s, "102. Rapid Reflexes (passive)", "102. 高速反射（パッシブ）");
 s = replaceText(s, "103. Self Care (passive)", "103. 自己手当（パッシブ）");
 s = replaceText(s, "104. Sharpshooter (passive)", "104. 狙撃手（パッシブ）");
 s = replaceText(s, "105. Skull Surgery (passive)", "105. 頭蓋手術（パッシブ）");
 s = replaceText(s, "106. Steel Thorn (passive)", "106. 鋼の棘（パッシブ）");
 s = replaceText(s, "107. Veteran (passive)", "107. 歴戦兵（パッシブ）");
 s = replaceText(s, "117. Tactical Bluff (passive)", "117. 戦術的ブラフ（パッシブ）");
 s = replaceText(s, "118. Poking", "118. 突きまくり");
 s = replaceText(s, "119. Spirit Swipe", "119. 霊撃薙ぎ");
 s = replaceText(s, "120. 戦闘リズム（パッシブ）", "120. 戦闘リズム（パッシブ）");
 s = replaceText(s, "108. Propaganda", "108. 宣伝工作");
 s = replaceText(s, "109. Honest Attacker (passive)", "109. 正直な攻撃者（パッシブ）");
 s = replaceText(s, "110. Shield of Faith (passive)", "110. 信仰の盾（パッシブ）");
 s = replaceText(s, "111. Dragon Tooth Kick", "111. 龍牙蹴り");
 s = replaceText(s, "112. Wrath of Davkul", "112. ダヴクルの憤怒");
 s = replaceText(s, "113. Armageddon", "113. アルマゲドン");
 s = replaceText(s, "114. Swarm of Insects", "114. 虫の群れ");
 s = replaceText(s, "115. Uproot", "115. 根こそぎ");
 s = replaceText(s, "116. Battle Domination", "116. 戦場支配");
 gt.Const.Strings.FT.SkillList = s;
}

local _lcj_v16_extra = function() {
 local gt = this.getroottable();
 local nameByText = {};
 nameByText["1. Accidental Attack"] <- "1. 偶発攻撃";
 nameByText["10. Bribe"] <- "10. 買収";
 nameByText["100. Warm-up (passive)"] <- "100. ウォームアップ";
 nameByText["101. Prudence (passive)"] <- "101. 慎重さ";
 nameByText["102. Rapid Reflexes (passive)"] <- "102. 高速反射";
 nameByText["103. Self Care (passive)"] <- "103. 自己手当";
 nameByText["104. Sharpshooter (passive)"] <- "104. 狙撃手";
 nameByText["105. Skull Surgery (passive)"] <- "105. 頭蓋手術";
 nameByText["106. Steel Thorn (passive)"] <- "106. 鋼の棘";
 nameByText["107. Veteran (passive)"] <- "107. 歴戦兵";
 nameByText["108. Propaganda"] <- "108. 宣伝工作";
 nameByText["109. Honest Attacker (passive)"] <- "109. 正直な攻撃者";
 nameByText["11. Cannon Barrage"] <- "11. 大砲斉射";
 nameByText["110. Shield of Faith (passive)"] <- "110. 信仰の盾";
 nameByText["111. Dragon Tooth Kick"] <- "111. 龍牙蹴り";
 nameByText["112. Wrath of Davkul"] <- "112. ダヴクルの憤怒";
 nameByText["113. Armageddon"] <- "113. アルマゲドン";
 nameByText["114. Swarm of Insects"] <- "114. 虫の群れ";
 nameByText["115. Uproot"] <- "115. 根こそぎ";
 nameByText["116. Battle Domination"] <- "116. 戦場支配";
 nameByText["117. Tactical Bluff (passive)"] <- "117. 戦術的ブラフ";
 nameByText["118. Poking"] <- "118. 突きまくり";
 nameByText["119. Spirit Swipe"] <- "119. 霊撃薙ぎ";
 nameByText["12. Brute Toss (Set Target)"] <- "12-1. 怪力投げ（目標指定）";
 nameByText["12. Brute Toss (Toss)"] <- "12-2. 怪力投げ（投げる）";
 nameByText["120. 戦闘リズム（パッシブ）"] <- "120. 戦闘リズム";
 nameByText["13. Battle Command"] <- "13. 戦闘指揮";
 nameByText["14. Concentration"] <- "14. 精神集中";
 nameByText["15. Perfect Aimed Throw"] <- "15. 完全照準投擲";
 nameByText["16. Battle Cure"] <- "16. 戦場治療";
 nameByText["17. Demonize"] <- "17. 悪魔化";
 nameByText["18. Devastating Blow"] <- "18. 壊滅打撃";
 nameByText["19. Drain Blood"] <- "19. 吸血";
 nameByText["2. Acid Grenade"] <- "2. 酸グレネード";
 nameByText["20. Earthquake"] <- "20. 地震";
 nameByText["21. Electric Shock"] <- "21. 電撃";
 nameByText["22. Feast"] <- "22. 貪り食い";
 nameByText["23. Fire Ball"] <- "23. ファイアボール";
 nameByText["24. Hellfire Grenade"] <- "24. 地獄火グレネード";
 nameByText["25. Flame Wave"] <- "25. 炎の波";
 nameByText["26. Fling Back"] <- "26. 弾き飛ばし";
 nameByText["27. Force of Nature"] <- "27. 自然の力";
 nameByText["28. Wicked Frenzy"] <- "28. 邪悪な狂乱";
 nameByText["29. Frost Blast"] <- "29. 凍結爆破";
 nameByText["3. Backstab"] <- "3. バックスタブ";
 nameByText["30. Gale Force"] <- "30. 疾風怒濤";
 nameByText["31. Great Awakening"] <- "31. 大覚醒";
 nameByText["32. Headbutt"] <- "32. 頭突き";
 nameByText["33. Magical Healing"] <- "33. 魔法治療";
 nameByText["34. Hide"] <- "34. 隠れる";
 nameByText["35. Holy Spear"] <- "35. 聖槍";
 nameByText["36. Judo Throw"] <- "36. 柔道投げ";
 nameByText["37. Kick"] <- "37. 蹴り";
 nameByText["38. Line Breaker"] <- "38. 戦線突破";
 nameByText["39. Magical Lute Song"] <- "39. 魔法のリュート歌";
 nameByText["4. Bear Trap"] <- "4. ベアトラップ";
 nameByText["40. Thunderstorm"] <- "40. 雷嵐";
 nameByText["41. Forced March"] <- "41. 強行軍";
 nameByText["42. Mark"] <- "42. 標的指定";
 nameByText["43. Miracle"] <- "43. 奇跡";
 nameByText["44. Stealing"] <- "44. 窃盗";
 nameByText["45. Multi Shot"] <- "45. 連射";
 nameByText["46. Penetrating Shot"] <- "46. 貫通射撃";
 nameByText["47. Pincer Thrust"] <- "47. 挟撃突き";
 nameByText["48. Telekinetic Explosion"] <- "48. 念動爆発";
 nameByText["49. Abyssal Grab"] <- "49. 深淵の掴み";
 nameByText["5. Berserker Charge"] <- "5. 狂戦士の突撃";
 nameByText["50. Purifying Flame"] <- "50. 浄化の炎";
 nameByText["51. Extreme Weather"] <- "51. 極端な天候";
 nameByText["52. Courage Boost"] <- "52. 勇気鼓舞";
 nameByText["53. Boulder Throw"] <- "53. 岩石投げ";
 nameByText["54. Throw Dirt"] <- "54. 砂かけ";
 nameByText["55. Banshee Scream"] <- "55. バンシーの叫び";
 nameByText["56. Shield Guard"] <- "56. 盾の守護";
 nameByText["57. Shadow Walk"] <- "57. 影歩き";
 nameByText["58. 盾打撃"] <- "58. 盾打ち";
 nameByText["59. Shockwave"] <- "59. 衝撃波";
 nameByText["6. Black Magic Grenade"] <- "6. 黒魔術グレネード";
 nameByText["60. Cursed Words"] <- "60. 呪詛";
 nameByText["61. Serpent Bind"] <- "61. 蛇縛り";
 nameByText["62. Double Edge"] <- "62. 諸刃";
 nameByText["63. Storm Fury"] <- "63. 嵐の怒り";
 nameByText["64. Fury Strike"] <- "64. 憤怒の一撃";
 nameByText["65. Summon Fiend"] <- "65. 悪鬼召喚";
 nameByText["66. Raise Dead"] <- "66. 死者蘇生";
 nameByText["67. Summon Spirit Wolf"] <- "67. 霊狼召喚";
 nameByText["68. Forced Swap"] <- "68. 強制入替";
 nameByText["69. Grappling"] <- "69. 組み付き";
 nameByText["7. Blessing"] <- "7. 祝福";
 nameByText["70. Tai Chi Weapon Form"] <- "70. 太極武器術";
 nameByText["71. Silent Takedown"] <- "71. 無音制圧";
 nameByText["72. Unleash the Rage"] <- "72. 怒りの解放";
 nameByText["73. War Crime"] <- "73. 戦争犯罪";
 nameByText["74. Warcry"] <- "74. 雄叫び";
 nameByText["75. Flood Bomb"] <- "75. 洪水爆弾";
 nameByText["76. Whirlwind Attack"] <- "76. 旋風攻撃";
 nameByText["77. Riding a Giant Wolf"] <- "77. 巨狼騎乗";
 nameByText["78. Point Blank Shot"] <- "78. 至近射撃";
 nameByText["79. Agile Killer (passive)"] <- "79. 機敏な殺し屋";
 nameByText["8. Bloodletting Therapy"] <- "8. 瀉血療法";
 nameByText["80. Transcendence"] <- "80. 超越";
 nameByText["81. Banner Lord (passive)"] <- "81. 旗主";
 nameByText["82. Battle Trance (passive)"] <- "82. 戦闘恍惚";
 nameByText["83. Vengeance (passive)"] <- "83. 復讐";
 nameByText["84. Mana Mastery (passive)"] <- "84. マナ熟達";
 nameByText["85. Challenger (passive)"] <- "85. 挑戦者";
 nameByText["86. Adaptive Counter (passive)"] <- "86. 適応反撃";
 nameByText["87. Desolator (passive)"] <- "87. 荒廃者";
 nameByText["88. Drunken Master (passive)"] <- "88. 酔拳の達人";
 nameByText["89. Goblin Weaponology (passive)"] <- "89. ゴブリン武器学";
 nameByText["9. Blood Lust"] <- "9. 血の渇望";
 nameByText["90. Harden Skin (passive)"] <- "90. 皮膚硬化";
 nameByText["91. Head Collector (passive)"] <- "91. 首狩り";
 nameByText["92. Poor Man\\'s Weapon (passive)"] <- "92. 貧者の武器";
 nameByText["93. Kensei (passive)"] <- "93. 剣聖";
 nameByText["94. Last Stand (passive)"] <- "94. 最後の抵抗";
 nameByText["95. Lifestealer (passive)"] <- "95. 生命奪取者";
 nameByText["96. Masochism (passive)"] <- "96. 被虐嗜好";
 nameByText["97. Oddball (passive)"] <- "97. 変わり者";
 nameByText["98. Orc Weaponology (passive)"] <- "98. オーク武器学";
 nameByText["99. Outsider (passive)"] <- "99. アウトサイダー";
 nameByText["Aard Sign"] <- "アードの印";
 nameByText["Abyssal Grab"] <- "深淵の掴み";
 nameByText["Adaptive Counter"] <- "適応反撃";
 nameByText["アドレナリンラッシュ"] <- "アドレナリンラッシュ";
 nameByText["Agile Killer"] <- "機敏な殺し屋";
 nameByText["アルプの耐性"] <- "アルプの耐性";
 nameByText["Armor Protection"] <- "防具保護";
 nameByText["腐敗のオーラ"] <- "腐敗のオーラ";
 nameByText["Axii Sign"] <- "アクスィーの印";
 nameByText["Backstab"] <- "バックスタブ";
 nameByText["Banner Lord"] <- "旗主";
 nameByText["樹皮の肌"] <- "樹皮肌";
 nameByText["バジリスクの集中"] <- "バシリスクの集中";
 nameByText["Battle Trance"] <- "戦闘恍惚";
 nameByText["Bear Trap"] <- "ベアトラップ";
 nameByText["獣の持久力"] <- "獣の持久力";
 nameByText["Beguile"] <- "魅了";
 nameByText["魅了"] <- "魅了";
 nameByText["Berserker Charge"] <- "狂戦士の突撃";
 nameByText["Black Magic Grenade"] <- "黒魔術グレネード";
 nameByText["Bola\\'d"] <- "ボーラ拘束";
 nameByText["Boulder Throw"] <- "岩石投げ";
 nameByText["Bront Sign"] <- "ブロントの印";
 nameByText["炎上！！"] <- "炎上！！";
 nameByText["Challenger"] <- "挑戦者";
 nameByText["Charming"] <- "魅力的";
 nameByText["Coat with Acid"] <- "酸を塗布";
 nameByText["巨躯の怪力"] <- "巨躯の怪力";
 nameByText["Corpse Explosion"] <- "死体爆破";
 nameByText["Courage Boost"] <- "勇気鼓舞";
 nameByText["不死の呪い"] <- "不死の呪い";
 nameByText["Cursed Words"] <- "呪詛";
 nameByText["Cutthroat"] <- "喉裂き";
 nameByText["Darkflight"] <- "闇の飛翔";
 nameByText["Desolator"] <- "荒廃者";
 nameByText["Dominant Bark"] <- "支配の咆哮";
 nameByText["Double Edge"] <- "諸刃";
 nameByText["Drunken Master"] <- "酔拳の達人";
 nameByText["霊体攻撃"] <- "霊体攻撃";
 nameByText["Extreme Weather"] <- "極端な天候";
 nameByText["Extremophile"] <- "極限環境適応";
 nameByText["Fear of Mutants"] <- "変異体恐怖";
 nameByText["飽食"] <- "満腹";
 nameByText["Fire Bender"] <- "炎術師";
 nameByText["Flood Bomb"] <- "洪水爆弾";
 nameByText["Force of Nature"] <- "自然の力";
 nameByText["Forced Swap"] <- "強制入替";
 nameByText["悪臭！"] <- "悪臭！";
 nameByText["Fury Strike"] <- "憤怒の一撃";
 nameByText["Gaisthasser"] <- "ガイスト嫌い";
 nameByText["Geisthasser"] <- "ガイスト嫌い";
 nameByText["Ghastly Touch"] <- "幽鬼の接触";
 nameByText["肉喰らいの飢え"] <- "グールの飢え";
 nameByText["Glare"] <- "睨み";
 nameByText["Goblin Weaponology"] <- "ゴブリン武器学";
 nameByText["ゴブリンの悪知恵"] <- "ゴブリンの狡猾";
 nameByText["Gruesome Feast"] <- "陰惨な饗宴";
 nameByText["Harden Skin"] <- "皮膚硬化";
 nameByText["Harsh Weather"] <- "過酷な天候";
 nameByText["Hate for Mutants"] <- "変異体嫌い";
 nameByText["Hates Dogs"] <- "犬嫌い";
 nameByText["Hates Everything"] <- "万物嫌い";
 nameByText["Head Collector"] <- "首狩り";
 nameByText["呪い"] <- "呪い";
 nameByText["イフリートの耐久"] <- "イフリートの耐久";
 nameByText["Igni Sign"] <- "イグニの印";
 nameByText["Ignite Feuerspeier"] <- "火筒点火";
 nameByText["扱えぬ担い手"] <- "扱えぬ担い手";
 nameByText["洞察強化"] <- "洞察上昇";
 nameByText["Inspired by Geisthasser"] <- "ガイスト嫌いに鼓舞";
 nameByText["Irresistible Allure"] <- "抗えぬ魅力";
 nameByText["Last Stand"] <- "最後の抵抗";
 nameByText["Learned to Read"] <- "読書習得";
 nameByText["読み書き学習中"] <- "読書学習中";
 nameByText["Light"] <- "軽快";
 nameByText["Lumbering"] <- "鈍重";
 nameByText["Mana Mastery"] <- "マナ熟達";
 nameByText["Martial"] <- "武勇";
 nameByText["Masochism"] <- "被虐嗜好";
 nameByText["精神疲労"] <- "精神疲労";
 nameByText["瘴気雲"] <- "瘴気雲";
 nameByText["Misanthropist"] <- "人間嫌い";
 nameByText["Monster Hunter"] <- "怪物狩り";
 nameByText["Multi Shot"] <- "連射";
 nameByText["変異毒！"] <- "変異体の毒！";
 nameByText["Mutation Aftermath"] <- "変異の後遺症";
 nameByText["変異：アルプ"] <- "変異：アルプ";
 nameByText["変異：バジリスク"] <- "変異：バシリスク";
 nameByText["変異：獣"] <- "変異：獣";
 nameByText["変異：犬"] <- "変異：犬";
 nameByText["変異：ロバ"] <- "変異：ロバ";
 nameByText["変異：ゴブリン"] <- "変異：ゴブリン";
 nameByText["変異：ヘクセン"] <- "変異：ヘクセ";
 nameByText["変異：イフリート"] <- "変異：イフリート";
 nameByText["Mutation: Nachzehrer"] <- "変異：ナハツェーラー";
 nameByText["変異：死霊術"] <- "変異：屍術";
 nameByText["変異：ネクロサヴァント"] <- "変異：ネクロサヴァント";
 nameByText["変異：オーク"] <- "変異：オーク";
 nameByText["変異：腐敗"] <- "変異：腐敗";
 nameByText["変異：シュラート"] <- "変異：シュラート";
 nameByText["変異：大蛇"] <- "変異：蛇";
 nameByText["変異：蜘蛛"] <- "変異：蜘蛛";
 nameByText["変異：霊体"] <- "変異：霊体";
 nameByText["変異：不死"] <- "変異：不死";
 nameByText["変異：ウンホルト"] <- "変異：ウンホルト";
 nameByText["変異：毒腺"] <- "変異：毒腺";
 nameByText["変異：リンドヴルム"] <- "変異：リンドヴルム";
 nameByText["盾なし！"] <- "盾なし！";
 nameByText["Nyctophobia"] <- "暗所恐怖症";
 nameByText["Oathsworn"] <- "誓約者";
 nameByText["Oddball"] <- "変わり者";
 nameByText["Old Vatt\\'ghern"] <- "老練なヴァットガーン";
 nameByText["Old Vattghern"] <- "老練なヴァットガーン";
 nameByText["Orc Weaponology"] <- "オーク武器学";
 nameByText["オークの猛攻"] <- "オークの攻勢";
 nameByText["麻痺"] <- "麻痺";
 nameByText["Penetrating Shot"] <- "貫通射撃";
 nameByText["Pincer Thrust"] <- "挟撃突き";
 nameByText["Pluviophile"] <- "雨好き";
 nameByText["PoV Enemy Scaling"] <- "PoV敵スケーリング";
 nameByText["Point Blank Shot"] <- "至近射撃";
 nameByText["腐敗毒"] <- "腐敗毒";
 nameByText["Poor Man\\'s Weapon"] <- "貧者の武器";
 nameByText["Powerful Kick"] <- "強烈な蹴り";
 nameByText["呪詛の守護"] <- "呪いの守護";
 nameByText["Psychopath"] <- "サイコパス";
 nameByText["Purifying Flame"] <- "浄化の炎";
 nameByText["クエンの盾"] <- "クエンの盾";
 nameByText["Quen Sign"] <- "クエンの印";
 nameByText["俊敏"] <- "素早い";
 nameByText["Raise the Banner!!"] <- "旗を掲げろ！！";
 nameByText["Riding a Giant Wolf"] <- "巨狼騎乗";
 nameByText["目潰しの砂"] <- "目潰し砂";
 nameByText["屍漁りの高揚！"] <- "漁り屋の昂揚！";
 nameByText["Seductive"] <- "魅惑的";
 nameByText["Serpent Bind"] <- "蛇縛り";
 nameByText["大蛇の身のこなし"] <- "蛇の妙技";
 nameByText["Serpentine Hook"] <- "蛇の鉤爪";
 nameByText["印の再使用待ち"] <- "印のクールダウン";
 nameByText["Silent Takedown"] <- "無音制圧";
 nameByText["Silver Slash"] <- "銀の斬撃";
 nameByText["Slaughterman"] <- "屠殺人";
 nameByText["蜘蛛の腺"] <- "蜘蛛の腺";
 nameByText["Split Shield (Ranged)"] <- "盾割り（遠隔）";
 nameByText["Stealing"] <- "窃盗";
 nameByText["Tai Chi Weapon Form"] <- "太極武器術";
 nameByText["Telekinetic Explosion"] <- "念動爆発";
 nameByText["Third Eye"] <- "第三の目";
 nameByText["飢えた吸血鬼（夜）"] <- "渇いた吸血鬼（夜）";
 nameByText["Trailblazer"] <- "先駆者";
 nameByText["イャーデンの罠"] <- "イャーデン拘束";
 nameByText["ウンホルトの活力"] <- "ウンホルトの活力";
 nameByText["Unleash the Rage"] <- "怒りの解放";
 nameByText["Unstable Mutant"] <- "不安定な変異体";
 nameByText["Use Vattghern-Poisoned Oil"] <- "ヴァットガーン毒油を使う";
 nameByText["吸血鬼：昼"] <- "吸血鬼：昼";
 nameByText["吸血鬼：夜！"] <- "吸血鬼：夜！";
 nameByText["吸血性"] <- "吸血性";
 nameByText["Vatt\\'ghern"] <- "ヴァットガーン";
 nameByText["Vattghern"] <- "ヴァットガーン";
 nameByText["ヴァットゲルン毒"] <- "ヴァットガーン毒";
 nameByText["ヴァットゲルン猛毒"] <- "強化ヴァットガーン毒";
 nameByText["Vengeance"] <- "復讐";
 nameByText["毒腺"] <- "毒腺";
 nameByText["毒腺"] <- "毒腺";
 nameByText["Vomit"] <- "嘔吐";
 nameByText["弱体化した吸血鬼（昼）"] <- "弱体化した吸血鬼（昼）";
 nameByText["酸性血液を塗った武器"] <- "酸性血液を塗布した武器";
 nameByText["ヴァットゲルン毒を塗った武器"] <- "ヴァットガーン毒を塗布した武器";
 nameByText["Whip Flail"] <- "鞭連撃";
 nameByText["リンドヴルムの酸"] <- "リンドヴルムの酸";
 nameByText["Yrden Sign"] <- "イャーデンの印";
 local nameByID = {};
 nameByID["actives.pov_aard"] <- "アードの印";
 nameByID["actives.pov_axii"] <- "アクスィーの印";
 nameByID["actives.pov_beguile"] <- "魅了";
 nameByID["actives.pov_bront"] <- "ブロントの印";
 nameByID["actives.pov_coat_with_acid"] <- "酸を塗布";
 nameByID["actives.pov_coat_with_vattghern_poison"] <- "ヴァットガーン毒油を使う";
 nameByID["actives.pov_corpse_explosion"] <- "死体爆破";
 nameByID["actives.pov_darkflight"] <- "闇の飛翔";
 nameByID["actives.pov_dominant_bark"] <- "支配の咆哮";
 nameByID["actives.pov_donkey_kick"] <- "強烈な蹴り";
 nameByID["actives.pov_fire_handgonne"] <- "火筒点火";
 nameByID["actives.pov_ghastly_touch"] <- "幽鬼の接触";
 nameByID["actives.pov_glare"] <- "睨み";
 nameByID["actives.pov_gruesome_feast"] <- "陰惨な饗宴";
 nameByID["actives.pov_igni"] <- "イグニの印";
 nameByID["actives.pov_quen"] <- "クエンの印";
 nameByID["actives.pov_raise_banner"] <- "旗を掲げろ！！";
 nameByID["actives.pov_ranged_split_shield"] <- "盾割り（遠隔）";
 nameByID["actives.pov_serpent_hook"] <- "蛇の鉤爪";
 nameByID["actives.pov_silverslash"] <- "銀の斬撃";
 nameByID["actives.pov_thirdeye_skill"] <- "第三の目";
 nameByID["actives.pov_vomit"] <- "嘔吐";
 nameByID["actives.pov_whip_flail_skill"] <- "鞭連撃";
 nameByID["actives.pov_yrden"] <- "イャーデンの印";
 nameByID["actives.sb2_chokentoss_skill"] <- "12-2. 怪力投げ（投げる）";
 nameByID["actives.sb_acciattack_skill"] <- "1. 偶発攻撃";
 nameByID["actives.sb_acidbomb_skill"] <- "2. 酸グレネード";
 nameByID["actives.sb_backstab_skill"] <- "3. バックスタブ";
 nameByID["actives.sb_beartrap_skill"] <- "4. ベアトラップ";
 nameByID["actives.sb_bkcharge_skill"] <- "5. 狂戦士の突撃";
 nameByID["actives.sb_blackbomb_skill"] <- "6. 黒魔術グレネード";
 nameByID["actives.sb_blessing_skill"] <- "7. 祝福";
 nameByID["actives.sb_bloodletting_skill"] <- "8. 瀉血療法";
 nameByID["actives.sb_bloodlust_skill"] <- "9. 血の渇望";
 nameByID["actives.sb_bribe_skill"] <- "10. 買収";
 nameByID["actives.sb_cannon_skill"] <- "11. 大砲斉射";
 nameByID["actives.sb_chokentoss_skill"] <- "12-1. 怪力投げ（目標指定）";
 nameByID["actives.sb_command_skill"] <- "13. 戦闘指揮";
 nameByID["actives.sb_concent_skill"] <- "14. 精神集中";
 nameByID["actives.sb_cqcthrowing_skill"] <- "15. 完全照準投擲";
 nameByID["actives.sb_cure_skill"] <- "16. 戦場治療";
 nameByID["actives.sb_demon_skill"] <- "17. 悪魔化";
 nameByID["actives.sb_devablow_skill"] <- "18. 壊滅打撃";
 nameByID["actives.sb_drainblood_skill"] <- "19. 吸血";
 nameByID["actives.sb_earthquake_skill"] <- "20. 地震";
 nameByID["actives.sb_electric_skill"] <- "21. 電撃";
 nameByID["actives.sb_feast_skill"] <- "22. 貪り食い";
 nameByID["actives.sb_fireball_skill"] <- "23. ファイアボール";
 nameByID["actives.sb_firebomb_skill"] <- "24. 地獄火グレネード";
 nameByID["actives.sb_flamewave_skill"] <- "25. 炎の波";
 nameByID["actives.sb_flingback_skill"] <- "26. 弾き飛ばし";
 nameByID["actives.sb_fonature_skill"] <- "27. 自然の力";
 nameByID["actives.sb_frenzy_skill"] <- "28. 邪悪な狂乱";
 nameByID["actives.sb_frostblast_skill"] <- "29. 凍結爆破";
 nameByID["actives.sb_gale_skill"] <- "30. 疾風怒濤";
 nameByID["actives.sb_great_skill"] <- "31. 大覚醒";
 nameByID["actives.sb_headbutt_skill"] <- "32. 頭突き";
 nameByID["actives.sb_heal_skill"] <- "33. 魔法治療";
 nameByID["actives.sb_hide_skill"] <- "34. 隠れる";
 nameByID["actives.sb_holyspear_skill"] <- "35. 聖槍";
 nameByID["actives.sb_judo_skill"] <- "36. 柔道投げ";
 nameByID["actives.sb_kick_skill"] <- "37. 蹴り";
 nameByID["actives.sb_linebreaker_skill"] <- "38. 戦線突破";
 nameByID["actives.sb_lute_skill"] <- "39. 魔法のリュート歌";
 nameByID["actives.sb_manaforce_skill"] <- "40. 雷嵐";
 nameByID["actives.sb_march_skill"] <- "41. 強行軍";
 nameByID["actives.sb_mark_skill"] <- "42. 標的指定";
 nameByID["actives.sb_miracle_skill"] <- "43. 奇跡";
 nameByID["actives.sb_moneysteal_skill"] <- "44. 窃盗";
 nameByID["actives.sb_multishot_skill"] <- "45. 連射";
 nameByID["actives.sb_penshot_skill"] <- "46. 貫通射撃";
 nameByID["actives.sb_pincer_skill"] <- "47. 挟撃突き";
 nameByID["actives.sb_pull2_skill"] <- "49. 深淵の掴み";
 nameByID["actives.sb_pull_skill"] <- "48. 念動爆発";
 nameByID["actives.sb_puri_skill"] <- "50. 浄化の炎";
 nameByID["actives.sb_rain_skill"] <- "51. 極端な天候";
 nameByID["actives.sb_revel_skill"] <- "52. 勇気鼓舞";
 nameByID["actives.sb_rock_skill"] <- "53. 岩石投げ";
 nameByID["actives.sb_sand_skill"] <- "54. 砂かけ";
 nameByID["actives.sb_scream_skill"] <- "55. バンシーの叫び";
 nameByID["actives.sb_sguard_skill"] <- "56. 盾の守護";
 nameByID["actives.sb_shadowwalk_skill"] <- "57. 影歩き";
 nameByID["actives.sb_shieldbash_skill"] <- "58. 盾打ち";
 nameByID["actives.sb_shockwave_skill"] <- "59. 衝撃波";
 nameByID["actives.sb_slander_skill"] <- "60. 呪詛";
 nameByID["actives.sb_snake_skill"] <- "61. 蛇縛り";
 nameByID["actives.sb_snow_skill"] <- "62. 諸刃";
 nameByID["actives.sb_stormfury_skill"] <- "63. 嵐の怒り";
 nameByID["actives.sb_strike_skill"] <- "64. 憤怒の一撃";
 nameByID["actives.sb_sumfiend_skill"] <- "65. 悪鬼召喚";
 nameByID["actives.sb_sumskel_skill"] <- "66. 死者蘇生";
 nameByID["actives.sb_sumwolf_skill"] <- "67. 霊狼召喚";
 nameByID["actives.sb_swap_skill"] <- "68. 強制入替";
 nameByID["actives.sb_sweep_skill"] <- "69. 組み付き";
 nameByID["actives.sb_taichi_skill"] <- "70. 太極武器術";
 nameByID["actives.sb_tieup_skill"] <- "71. 無音制圧";
 nameByID["actives.sb_unlrage_skill"] <- "72. 怒りの解放";
 nameByID["actives.sb_warcrime_skill"] <- "73. 戦争犯罪";
 nameByID["actives.sb_warcry_skill"] <- "74. 雄叫び";
 nameByID["actives.sb_waterbomb_skill"] <- "75. 洪水爆弾";
 nameByID["actives.sb_whirlwind_skill"] <- "76. 旋風攻撃";
 nameByID["actives.sb_wolfride_skill"] <- "77. 巨狼騎乗";
 nameByID["actives.sb_zeroshot_skill"] <- "78. 至近射撃";
 nameByID["actives.sbp_agile_skill"] <- "79. 機敏な殺し屋";
 nameByID["actives.sbp_allrounder_skill"] <- "80. 超越";
 nameByID["actives.sbp_banner_skill"] <- "81. 旗主";
 nameByID["actives.sbp_battletrance_skill"] <- "82. 戦闘恍惚";
 nameByID["actives.sbp_beater_skill"] <- "83. 復讐";
 nameByID["actives.sbp_bondage_skill"] <- "84. マナ熟達";
 nameByID["actives.sbp_challenger_skill"] <- "85. 挑戦者";
 nameByID["actives.sbp_counter_skill"] <- "86. 適応反撃";
 nameByID["actives.sbp_desolator_skill"] <- "87. 荒廃者";
 nameByID["actives.sbp_drunk_skill"] <- "88. 酔拳の達人";
 nameByID["actives.sbp_goblin_skill"] <- "89. ゴブリン武器学";
 nameByID["actives.sbp_hardenskin_skill"] <- "90. 皮膚硬化";
 nameByID["actives.sbp_headcollector_skill"] <- "91. 首狩り";
 nameByID["actives.sbp_kensei_skill"] <- "93. 剣聖";
 nameByID["actives.sbp_laststand_skill"] <- "94. 最後の抵抗";
 nameByID["actives.sbp_lifestealer_skill"] <- "95. 生命奪取者";
 nameByID["actives.sbp_maso_skill"] <- "96. 被虐嗜好";
 nameByID["actives.sbp_oddball_skill"] <- "97. 変わり者";
 nameByID["actives.sbp_orc_skill"] <- "98. オーク武器学";
 nameByID["actives.sbp_outsider_skill"] <- "99. アウトサイダー";
 nameByID["actives.sbp_overwarmup_skill"] <- "100. ウォームアップ";
 nameByID["actives.sbp_prudence_skill"] <- "101. 慎重さ";
 nameByID["actives.sbp_rapid_skill"] <- "102. 高速反射";
 nameByID["actives.sbp_selfcare_skill"] <- "103. 自己手当";
 nameByID["actives.sbp_sharpshooter_skill"] <- "104. 狙撃手";
 nameByID["actives.sbp_skullsurgery_skill"] <- "105. 頭蓋手術";
 nameByID["actives.sbp_spear_skill"] <- "106. 鋼の棘";
 nameByID["actives.sbp_veteran_skill"] <- "107. 歴戦兵";
 nameByID["actives.sbq10p_bluff_skill"] <- "117. 戦術的ブラフ";
 nameByID["actives.sbq11_poking_skill"] <- "118. 突きまくり";
 nameByID["actives.sbq12_swipe_skill"] <- "119. 霊撃薙ぎ";
 nameByID["actives.sbq13p_rhythm_skill"] <- "120. 戦闘リズム";
 nameByID["actives.sbq1_propaganda_skill"] <- "108. 宣伝工作";
 nameByID["actives.sbq2p_honest_skill"] <- "109. 正直な攻撃者";
 nameByID["actives.sbq3p_shieldf_skill"] <- "110. 信仰の盾";
 nameByID["actives.sbq4_dragonkick_skill"] <- "111. 龍牙蹴り";
 nameByID["actives.sbq5_wrath_skill"] <- "112. ダヴクルの憤怒";
 nameByID["actives.sbq6_bigfire_skill"] <- "113. アルマゲドン";
 nameByID["actives.sbq7_bug_skill"] <- "114. 虫の群れ";
 nameByID["actives.sbq8_uproot_skill"] <- "115. 根こそぎ";
 nameByID["actives.sbq9_domi_skill"] <- "116. 戦場支配";
 nameByID["actives.vampire_darkflight"] <- "闇の飛翔";
 nameByID["effects.hex_master"] <- "呪いの守護";
 nameByID["effects.hex_slave"] <- "呪い";
 nameByID["effects.pov_acid_coat"] <- "酸性血液を塗布した武器";
 nameByID["effects.pov_adrenaline_rush"] <- "アドレナリンラッシュ";
 nameByID["effects.pov_alp_mutagen"] <- "変異：アルプ";
 nameByID["effects.pov_basilisk_mutagen"] <- "変異：バシリスク";
 nameByID["effects.pov_burning"] <- "炎上！！";
 nameByID["effects.pov_charm"] <- "魅了";
 nameByID["effects.pov_direwolf_mutagen"] <- "変異：獣";
 nameByID["effects.pov_direwolf_weak_mutagen"] <- "獣の持久力";
 nameByID["effects.pov_distracted"] <- "目潰し砂";
 nameByID["effects.pov_dog_mutagen"] <- "変異：犬";
 nameByID["effects.pov_donkey_mutagen"] <- "変異：ロバ";
 nameByID["effects.pov_enemy_vampire_day_effect"] <- "弱体化した吸血鬼（昼）";
 nameByID["effects.pov_enemy_vampire_night_effect"] <- "渇いた吸血鬼（夜）";
 nameByID["effects.pov_exhausted"] <- "精神疲労";
 nameByID["effects.pov_feasted"] <- "満腹";
 nameByID["effects.pov_ghost_mutagen"] <- "変異：霊体";
 nameByID["effects.pov_ghost_weak_mutagen"] <- "霊体攻撃";
 nameByID["effects.pov_ghoul_mutagen"] <- "変異：ナハツェーラー";
 nameByID["effects.pov_ghoul_weak_mutagen"] <- "グールの飢え";
 nameByID["effects.pov_goblin_mutagen"] <- "変異：ゴブリン";
 nameByID["effects.pov_hex"] <- "魅了";
 nameByID["effects.pov_hexe_curse_master"] <- "呪いの守護";
 nameByID["effects.pov_hexe_curse_slave"] <- "呪い";
 nameByID["effects.pov_hexe_mutagen"] <- "変異：ヘクセ";
 nameByID["effects.pov_learning_to_read"] <- "読書学習中";
 nameByID["effects.pov_lindwurm_mutagen"] <- "変異：リンドヴルム";
 nameByID["effects.pov_miasma"] <- "瘴気雲";
 nameByID["effects.pov_missing_hp_dmg_effect"] <- "巨躯の怪力";
 nameByID["effects.pov_mutant_poison"] <- "変異体の毒！";
 nameByID["effects.pov_near_ghost_hater"] <- "ガイスト嫌いに鼓舞";
 nameByID["effects.pov_necromancy_mutagen"] <- "変異：屍術";
 nameByID["effects.pov_non_vattghern_sword_effect"] <- "扱えぬ担い手";
 nameByID["effects.pov_orc_mutagen"] <- "変異：オーク";
 nameByID["effects.pov_orc_weak_mutagen"] <- "オークの攻勢";
 nameByID["effects.pov_paralyzed"] <- "麻痺";
 nameByID["effects.pov_quen"] <- "クエンの盾";
 nameByID["effects.pov_rot_mutagen"] <- "変異：腐敗";
 nameByID["effects.pov_rot_weak_mutagen"] <- "腐敗のオーラ";
 nameByID["effects.pov_sandgolem_mutagen"] <- "変異：イフリート";
 nameByID["effects.pov_schrat_mutagen"] <- "変異：シュラート";
 nameByID["effects.pov_schrat_no_shield"] <- "盾なし！";
 nameByID["effects.pov_schrat_weak_mutagen"] <- "樹皮肌";
 nameByID["effects.pov_serpent_mutagen"] <- "変異：蛇";
 nameByID["effects.pov_sign_cooldown"] <- "印のクールダウン";
 nameByID["effects.pov_skeleton_mutagen"] <- "変異：不死";
 nameByID["effects.pov_skeleton_weak_mutagen"] <- "不死の呪い";
 nameByID["effects.pov_spider_mutagen"] <- "変異：蜘蛛";
 nameByID["effects.pov_stench"] <- "悪臭！";
 nameByID["effects.pov_thirdeye_buff"] <- "洞察上昇";
 nameByID["effects.pov_unhold_mutagen"] <- "変異：ウンホルト";
 nameByID["effects.pov_vampire_day_effect"] <- "吸血鬼：昼";
 nameByID["effects.pov_vampire_mutagen"] <- "変異：ネクロサヴァント";
 nameByID["effects.pov_vampire_night_effect"] <- "吸血鬼：夜！";
 nameByID["effects.pov_vampire_weak_mutagen"] <- "吸血性";
 nameByID["effects.pov_vattghern_poison"] <- "ヴァットガーン毒";
 nameByID["effects.pov_vattghern_poison_coat"] <- "ヴァットガーン毒を塗布した武器";
 nameByID["effects.pov_vattghern_upgraded_poison"] <- "強化ヴァットガーン毒";
 nameByID["effects.pov_venom_mutagen"] <- "変異：毒腺";
 nameByID["effects.pov_weak_stench"] <- "腐敗毒";
 nameByID["effects.pov_yrden"] <- "イャーデン拘束";
 nameByID["effects.sb_unlrage_effect"] <- "怒りの解放";
 nameByID["injury.pov_sickness2"] <- "変異の後遺症";
 nameByID["special.pov_armor_changes_special"] <- "防具保護";
 nameByID["special.pov_rain"] <- "過酷な天候";
 nameByID["special.pov_scaling"] <- "PoV敵スケーリング";
 nameByID["spells.hex"] <- "呪い";
 nameByID["trait.pov_extremophile"] <- "極限環境適応";
 nameByID["trait.pov_fear_mutants"] <- "変異体恐怖";
 nameByID["trait.pov_hate_dogs"] <- "犬嫌い";
 nameByID["trait.pov_hate_everything"] <- "万物嫌い";
 nameByID["trait.pov_hate_ghosts"] <- "ガイスト嫌い";
 nameByID["trait.pov_hate_mutants"] <- "変異体嫌い";
 nameByID["trait.pov_misanthropist"] <- "人間嫌い";
 nameByID["trait.pov_monster_hunter"] <- "怪物狩り";
 nameByID["trait.pov_nyctophobia"] <- "暗所恐怖症";
 nameByID["trait.pov_oathsworn"] <- "誓約者";
 nameByID["trait.pov_old_vattghern"] <- "老練なヴァットガーン";
 nameByID["trait.pov_pluviophile"] <- "雨好き";
 nameByID["trait.pov_psychopath"] <- "サイコパス";
 nameByID["trait.pov_reader"] <- "読書習得";
 nameByID["trait.pov_seductive"] <- "抗えぬ魅力";
 nameByID["trait.pov_trailblazer"] <- "先駆者";
 nameByID["trait.pov_unstable_mutant"] <- "不安定な変異体";
 nameByID["weapon.pov_whip_mace"] <- "鞭連撃";
 local perkNameByKey = {};
 perkNameByKey["LegendSpecialistButcher"] <- "屠殺人";
 perkNameByKey["LegendSpecialistPrisoner"] <- "喉裂き";
 perkNameByKey["NggHAlpControlFlame"] <- "炎術師";
 perkNameByKey["NggHSerpentVenom"] <- "毒腺";
 perkNameByKey["VampireDarkflight"] <- "闇の飛翔";
 local patchStringTable = function(tab) { if (tab == null || typeof tab != "table") return; foreach(k,v in tab) if (typeof v == "string" && (v in nameByText)) tab[k] = nameByText[v]; };
 local patchPerkDef = function(p) { if (p == null || typeof p != "table") return; if (("ID" in p) && (p.ID in nameByID)) p.Name = nameByID[p.ID]; else if (("Name" in p) && (p.Name in nameByText)) p.Name = nameByText[p.Name]; };
 if (("Const" in gt)) {
   if (("Strings" in gt.Const)) {
     if (("PerkName" in gt.Const.Strings)) { foreach(k,v in perkNameByKey) gt.Const.Strings.PerkName[k] <- v; patchStringTable(gt.Const.Strings.PerkName); }
     if (("SkillName" in gt.Const.Strings)) patchStringTable(gt.Const.Strings.SkillName);
     if (("TraitName" in gt.Const.Strings)) patchStringTable(gt.Const.Strings.TraitName);
     if (("FT" in gt.Const.Strings) && ("SkillList" in gt.Const.Strings.FT)) patchFantasyBroSkillListV16();
   }
   if (("Perks" in gt.Const)) {
      if (("PerkDefObjects" in gt.Const.Perks)) foreach(p in gt.Const.Perks.PerkDefObjects) patchPerkDef(p);
      if (("PerkDefs" in gt.Const.Perks)) foreach(k,p in gt.Const.Perks.PerkDefs) patchPerkDef(p);
   }
 }
};
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_msu", _lcj_v16_extra);
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_legends", _lcj_v16_extra);
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_fantasybro", _lcj_v16_extra);
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_PoV", _lcj_v16_extra);
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_nggh_magic_concept", _lcj_v16_extra);
::mods_queue("mod_99_legends_complete_ja_v16_extra", "mod_aurapower", _lcj_v16_extra);
_lcj_v16_extra();
