::mods_hookExactClass("events/events/dlc4/horse_race_event", function(o) {
	local create = o.create;
	o.create = function() {
		create();
		foreach (s in this.m.Screens) {
			if (s.ID == "B") {
				s.Text = "%terrainImage%{You nominate %randombrother% to try and see if %they_other% can best the beast. The race\'s rules are first to the apple tree and before you can even begin to root for the sellsword the horse smokes %them_other% completely. It gets to the finish line and begins fishing the branches for apples. The company is sitting completely silent, but when %randombrother% crosses the finish line in a distant last place they roar with delight as though %they_other% just won the keys to the kingdom\'s finest whorehouse. The horse\'s owner laughs.%SPEECH_ON%Don\'t be hard on yerself, kind sir. The fun is in the chance.%SPEECH_OFF%Indeed it seems the spectacle of the %person_other%\'s efforts entertained the company.} ";
			}
			if (s.ID == "C") {
				s.Text = "%terrainImage%{%athlete% steps forward. %Their_athletic% calves bulge from %their_athletic% socks and %they_athletic% shoulder rolls to loosen up.%SPEECH_ON%Yeah I\'ll race that sorry horse.%SPEECH_OFF%The wager is made and the horse\'s owner directs you to a path. With the race set up, he holds up a pair of wooden tongs held apart, and backwards, by some tine. When he cuts the rope, the tongs snap clap together and start the race. Despite being looking like a wart left in the rain, the horse instantly gets a step on the nimble sellsword. It\'s only halfway down the track does the mercenary\'s stamina seem to put %them_athletic% back in the race, but %they_athletic% ultimately fails at the finish line. The owner claps his hands.%SPEECH_ON%Oh, that was a close one! The closest I\'ve seen!%SPEECH_OFF%You nod and pay the man what he is owed. %athlete% was beaten, but despite that it seems the loss has bettered %them_athletic% in some regard and the company certainly enjoyed the spectacle.}";
			}
			if (s.ID == "D") {
				s.Text = "%terrainImage%{Feeling rather courageous, you nominate the fattest %person_fat% in the company to handle the race. %fat% steps forward with an eyebrow raised, asking if you\'re sure about taking %them_fat% as your horseracing champion. You hold your hand on %their_fat% shoulder and say %they're_fat% the fattest fark you\'ve ever seen being a sellsword, but that you believe in %them_fat%. You also believe the horse is a haggard draught animal that\'s on its last legs, but you keep that part to yourself.\n\n The %person_fat% and horse are put next to each other. An apple tree stands in the distance and the first to it is the winner. With the rules laid out, the race is started. It\'s not an especially close one. %fat% falls behind almost instantly and trundles down the track with %their_fat% face beet red and huffing breath and the men nearly die laughing at the sight. The fat sellsword and dire horse meet back up at the apple tree and there share the fruits of their labors. You pay the horse\'s owner what he is owed. He smiles as he counts the coin.%SPEECH_ON%Don\'t usually get a show with the race, sir.%SPEECH_OFF%}";
			}
			if (s.ID == "E") {
				s.Text = "%terrainImage%{You elect %dumb%, the company\'s biggest idiot, to be your horse racing champion. The horse\'s owner takes one look at the %person_dumb% and raises an eyebrow.%SPEECH_ON%Well. Alright.%SPEECH_OFF%Rules of the race are clear: first to a distant apple tree is the winner. The %person_dumb% and animal line up on the track. Pretending that %they_dumb% knows what %they're_dumb% doing, %dumb% crouches in a tri-pointed stance. The horse owner yells and slaps his beast on the buttocks. %dumb% releases into a nice stride and shockingly gets ahead of the horse, but %they're_dumb% unable to handle %their% speed and tilts into the second lane and collides with the beast. The horse buckles at the knees and flips head over hind and %dumb% somehow ends up in the curve of its loins and on the flip around is catapulted through the air. It\'s a damned sight and one you\'ll surely never see again. The horse gets back to its feet and stares around confused while %dumb%\'s unconscious body flies over the finish line. You turn your palms to the horse owner whose hands are gripping his head.%SPEECH_ON%By the old gods, man, are you not concerned for your sellsword?%SPEECH_OFF%}";
			}
		}
	}
})