::Const.Strings.AncientSouthernNames <- ["Aahotepre","Achillas","Addaya","Agathocies","Ebana","Ahmose","Amenmose","Amenemhat","Ankhkherednefer","Ankhmakis","Ankherfenedjef","Ankhreshet","Amenemhatankh","Ahmose","Sapair","Amenemhat","Amenemopet","Amenhotep","Amunherkhepeshef","Ankhhaf","Meritamon","Nebetta","Tumerisy","Henutemipet","Sitamun","Tasherit","Anen","Pairy","Huy","Aperei","Amethu","Bay Irsu","Bakenkhonsu","Baqet","Babaef","Bebi","Bakenrenef","Charmian","Duaenre","Djau","Dagi","Djaty","Djedefhor","Djedi","Duaenhor","Djediufankh","Dedi","Djehuty","Gemenefkhonsbak","Harkhebi","Harwa","Hui","Hannu","Herihor","Harkhuf","Hapuseneb","Haremakhet","Harsiese","Hori","Hsekiu","Horbaef","Hornakht","Hakor","Hunefer","Hepu","Hewernef","Ineni","Intef","Isesi","Iuput","Ini Menkhepere","Inkaef","Isu","Itisen","Iunre","Iynefer","Ibiaw","Ibi","Iunmin","Iuty","Iymeru","Kaaper","Kagemni","Khabash","Khabekhnet","Mentuherkhopshef","Mentuhotep","Menna","Merneptah","Minmose","Nahkt","Nakhtmin","Nakhtpaaten",];

::Const.Strings.EmbalmedNobleNames <- ::Const.Strings.AncientSouthernNames;

::Const.Strings.GhostArmorNames <- [
	"Alleberg",
	"Momon",
	"Sleepy Hollow",
	"Kopfloser Reiter",
	"Gespenster",
	"Glen of Mull"
];

::Const.Strings.FleshGolemNames <- [
	"Winged Victory",
	"Venus de Milo",
	"Augustus",
	"Adonis",
	"Discobulos",
	"Belvedere",
	"Colossus",
	"Artemision",
	"Apollo"
];

::Const.Strings.DesertStalkerChampionTitles <- [
	"the Scorpion",
	"the Sand Stalker",
	"the Desert Stalker",
	"the Eagle",
	"the Raven",
	"the Hawk",
	"the Deathstalker",
	"the Master Archer",
	"the Hunter",
	"the Headhunter",
	"the Sandviper",
	"the Ray of Light",
	"the Gilders\' Hand",
	"Eye of the Hawk",
	"the Vulture",
	"the Serpent",
	"the Stinger",
	"the Heartseeker"
];

::Const.Strings.NobleGreatswordTitles <- [
	"the Greatsword",
	"the Zweihander",
	"the Blade",
	"the Longblade",
	"the Slayer",
	"the Vanquisher",
	"the Beheader",
	"the Executioner",
	"the Defender",
	"the Orcslayer",
	"the Honor",
	"the Claymore",
	"the Thug\'s Bane",
	"the Long Reach",
	"the Splitter",
	"the Warsword",
	"the Bidenhander",
	"the Gassenhauer",
	"the Landsknecht"
];

::Const.Strings.NoblewomanTitles <- [
	"Dame",
	"Lady",
	"Baroness",
	"Lady",
	"Dutchess",
	"Markgräfin"
];

::Const.Strings.LadyTitles <- [
	"The Guardian",
	"The Ghost",
	"The Swift",
	"Steelwielder",
	"The Hawk",
	"The Giant",
	"The Mountain",
	"Strongwill",
	"The Knightslayer",
	"The Undefeated",
	"The Scourge",
	"The Brute",
	"Mancrusher",
	"The Exiled",
	"The Conqueror",
	"The Skulltaker",
	"The Sentinel",
	"The Courageous",
	"The Chaotic",
	"The Brutal",
	"The Courteous",
	"The Angel",
	"The Heroic",
	"The Protector",
	"The Brave",
	"The Titan",
	"The Loyal",
	"The Merciful",
	"The Butcher",
	"The Horrific",
	"The Invincible",
	"The Slayer",
	"The Bear",
	"The Dragon",
	"The Crane",
	"The Unicorn",
	"Lionheart",
	"The Humble",
	"The Dreamer",
	"The Trusted",
	"The Mighty",
	"The Strange",
	"Dragonheart",
	"The Prodigy",
	"The Enigma",
	"The Divine",
	"The Black",
	"The Blue",
	"The Red",
	"The White",
	"The Grey",
	"The Cold",
	"The Warm",
	"The Profligate",
	"Of The Ghost",
	"Of The Dawn",
	"Of The Stars",
	"Of The Sky",
	"Of The Night",
	"Of The Twilight",
	"Of The Nightfall",
	"Of The Summer",
	"Of The Winter",
	"Of The Fall",
	"Of The Spring",
	"Of The Water",
	"Of The River",
	"Of The Ice",
	"Of The Road",
	"Of The Snow",
	"Of The River",
	"Of The East",
	"Of The West",
	"Of The South",
	"Of The North",
	"dan Glokta"
];

::Const.Strings.LadyNames <- [
	"Lady Jean",
	"Lady Hatchet",
	"Lady Matilda",
	"Lady Isabella",
	"Lady Deborah",
	"Lady Gwendolen",
	"Lady Mavia",
	"Lady Lilliard",
	"Lady Madeira",
	"Lady Hille",
	"Lady Amina",
	"Lady Mary",
	"Lady Beaton",
	"Lady Jean",
	"Lady Avice",
	"Lady Emma",
	"Lady Joan",
	"Lady Margery",
	"Lady Albree",
	"Lady Alia",
	"Lady Ela",
	"Lady Gisella",
	"Lady Elisa",
	"Lady Tamsin",
	"Lady Anabella",
	"Lady Beatrice",
	"Lady Clarae",
	"Lady Emilia",
	"Lady Constance",
	"Lady Florencia",
	"Lady Joye",
	"Lady Lucia",
	"Lady Arrianna",
	"Lady Pavia",
	"Lady Prudence",
	"Lady Sabina",
	"Lady Ursula",
	"Lady Grace",
	"Lady Yvone",
	"Lady Amelia",
	"Lady Sara",
	"Lady Jay",
	"Lady Sophie",
	"Lady Sophia",
	"Lady Jane",
	"Lady Ada",
	"Lady Katherine",
	"Lady Brienne",
	"Lady Lena",
	"Lady Holly",
	"Lady Isolda",
	"Lady Jocelyn",
	"Lady Burne",
	"Lady Barclay",
	"Lady Edith",
	"Lady Boothe",
	"Lady Dustin",
	"Lady Fairfax",
	"Lady Hendrick",
	"Lady Lyndon",
	"Lady Marlow",
	"Lady Rigby",
	"Lady Tye",
	"Lady Rose",
	"Lady Shaw",
	"Lady Robert",
	"Lady Julia",
	"Lady Slade",
	"Lady Thorne",
	"Lady Hester",
	"Lady Hallie",
	"Lady Olivia",
	"Lady Roberta",
	"Lady Priscilla",
	"Lady Cleo",
	"Lady Rae",
	"Lady Anastasia",
	"Lady Judith",
	"Lady Edyth",
	"Lady Beth",
	"Lady Libby",
	"Lady Edna",
	"Lady Ruth",
	"Lady Eleanor",
	"Lady Isabelle",
	"Lady Isobel",
	"Lady Amy",
	"Lady Henrietta",
	"Lady Lola",
	"Lady Rachel",
	"Lady Georgia",
	"Lady May",
	"Lady Meg",
	"Lady Avalon",
	"Lady Magda",
	"Lady Eva",
	"Lady Monza"
];

::Const.Strings.CharacterNamesFemaleNorse <- [
	"Agata",
	"Alfhilda",
	"Arnlaug",
	"Birna",
	"Brunhild",
	"Bylgja",
	"Dagrun",
	"Drifa",
	"Edda",
	"Eir",
	"Elli",
	"Embla",
	"Fenja",
	"Frigg",
	"Gigja",
	"Groa",
	"Gudrun",
	"Gullveig",
	"Halla",
	"Heidrun",
	"Helga",
	"Hrefna",
	"Hulda",
	"Ida",
	"Inga",
	"Ingrid",
	"Ingunn",
	"Johanna",
	"Jorunn",
	"Katla",
	"Kolbrun",
	"Kristin",
	"Laufey",
	"Magdalena",
	"Magna",
	"Marta",
	"Mette",
	"Nanna",
	"Oda",
	"Ragna",
	"Runa",
	"Sif",
	"Signy",
	"Sigrid",
	"Sigrun",
	"Solveig",
	"Svana",
	"Tekla",
	"Tora",
	"Torunn",
	"Una",
	"Valborg",
	"Valdis",
	"Yrsa",
	"Astrid",
	"Bodil",
	"Gertrud",
	"Gro",
	"Estrid",
	"Randi",
	"Signe",
	"Revna",
	"Tove",
	"Thyra",
	"Thurid",
	"Ase",
	"Ama",
	"Asdis",
	"Atla",
	"Brana",
	"Buna",
	"Brak",
	"Disa",
	"Dufa",
	"Dalla",
	"Elena",
	"Eyja",
	"Eylaug",
	"Fasta",
	"Folka",
	"Fulla",
	"Fonn",
	"Gefjon",
	"Geirdis",
	"Gisla",
	"Glyrna",
	"Grimhildr",
	"Gunna",
	"Gunsa",
	"Goll",
	"Hallbera",
	"Halldis",
	"Hallotta",
	"Herja",
	"Herbjorg",
	"Hlif",
	"Hlifhildr",
	"Hlin",
	"Hlokk",
	"Holma",
	"Hronna",
	"Ingiborg",
	"Ingilaug",
	"Ingveldr",
	"Irpa",
	"Jartha",
	"Jodis",
	"Julianna",
	"Jorunna",
	"Kathlinn",
	"Kalda",
	"Kara",
	"Katla",
	"Kolka",
	"Kyi",
	"Lif",
	"Lofn",
	"Magga",
	"Malmury",
	"Mara",
	"Mette",
	"Mist",
	"Mjoll",
	"Myrgiol",
	"Nal",
	"Nanna",
	"Nott",
	"Oddny",
	"Otama",
	"Ragndid",
	"Ragnvor",
	"Randalin",
	"Ranka",
	"Rikke",
	"Rikvi",
	"Roskva",
	"Saga",
	"Sefa",
	"Sifa",
	"Signi",
	"Sigvei",
	"Sigyn",
	"Skada",
	"Skaga",
	"Skuld",
	"Snotra",
	"Steinbjorg",
	"Svala",
	"Syn",
	"Solva",
	"Tofa",
	"Tora",
	"Ulfhildr",
	"Undrlaug",
	"Valka",
	"Var",
	"Vif",
	"Viborg",
	"Visna",
	"Libeste",
	"Marozia",
	"Rodelinda",
	"Rosamunda",
	"Abrella",
	"Addiena",
	"Aerea",
	"Allust",
	"Alpia",
	"Coblaith",
	"Darerca",
	"Derelei",
	"Domelch",
	"Drusticc",
	"Findscop",
	"Maelmuire",
	"Lonceta",
	"Vigga"
];
::Const.Strings.InventorTitles <- [
	"the Inventor",
	"the Curious",
	"the Peculiar",
	"the Inquisitive",
	"the Utilitarian",
	"the Serendipitous",
	"the Eclectic",
	"the Tinkerer",
	"the Thinker",
	"the Frantic",
	"the Eccentric"

];

::Const.Strings.SouthernFemaleNames <- ["Adila","Amsha","Asiya","Faghira","Habiba","Hanifa","Isra","Jahaira","Kamala","Layla","Maryam","Munya","Nafisa","Nyawela","Parand","Parween","Paymaneh","Paywand","Qamara","Rafiqa","Rasa","Rashida","Reshawna","Saaman","Sabba","Saghar","Sahba","Sajida","Samira","Semeah","Setara","Shahrbano","Shahzadah","Shameem","Shararah","Sheeftah","Sheeva","Shogofa","Shokouh","Shola","Sholah","Simin","Souzan","Taliba","Tanaz","Taneen","Yagana","Yakta","Yasmin","Zaynab","Abda","Ahu","Aiza","Aliyah","Butayna","Daniyah","Dima","Fahra","Fahriya","Fatima","Gamila","Ghada","Huda","Ibtisam","Karima","Kera","Khadija","Maha","Malika","Mariam","Nadia","Naila","Nur","Rahat","Raisa","Randa","Safiya","Salma","Shakira","Suraya","Tahira","Tarifa","Thashim","Umm","Wahida","Zahida","Zahra","Acenith","Alia","Amunet","Andali","Asanet","Asenath","Asenet","Azenet","Badiat","Cena","Halima","Jamila","Majida","Nabila","Nura","Radiya","Rana","Sacmis","Suhaila","Tawaret","Taweret","Titi","Thuriya","Zara","Aisha","Aziza","Duha","Farida","Golbahar","Gulnar","Gulnaz","Gulpari","Hafsa","Hasti","Huma","Jalila","Khandan","Khaterah","Khatira","Kinah","Lala","Madiha","Mahdokht","Mahsa","Mahwash","Marwa","Mastana","Mehri","Mina","Minoo","Munawwar","Muzhdah","Nahal","Najela","Nasiba","Nastaran","Nazaneen","Nazy","Neelab","Negar","Niki","Nikoo","Noushin","Rabiya","Rajiya","Sadiya","Sitara","Thana","Zuhayra","Nisrin","Nawrah","Habibah","Baysan","Wafa","Nibras","Radeyah","Jihan","Najmah","Anan","Walaa","Baraa","Buthayna","Lam'ah","Mu'azzaz","Shadhiyah","Dahab","Dalal","Aliah","Shuhrah","Salsabil","Wifaq","Hayfa","Is'af","Nadirah","Sawsan","Jawahir","Basheera","Rubadah","Aaliyah","Amira","Kayla","Nyla","Zariah","Aleah","Romina","Yara","Yamileth","Ranim","Sa'dah","Nashita","Salimah","Maladh","Raniya","Jadwa","Atifah","Shadhaa","Bilqees","Humairah","Busr","Sunbul","Capella","Adara","Afaaf","Benazir","Daneen","Dariya","Esita","Fairoz","Fareeda","Ghusan","Haniya","Heena","Kalila","Lakia","Lina","Lulu","Qadira","Rida","Sahara","Soheila","Sufia","Taliha","Ummid","Zoya","Amina","Illi","Leïla","Dene","Keyah","Repila","Abarrane","Abene","Ageda","Aina","Alba","Alberta","Antía","Aurkene","Branca","Carme","Danele","Elizabete","Fronilde","Josune","Lía","Zuriñe",];

::Const.Strings.VampireLordNames <- [
	"Brasus",
	"Khalid",
	"Lukman",
	"Madu",
	"Naggar",
	"Neb Er Tcher",
	"Psantic",
	"Radames",
	"Wrathamon",
	"Ahmose",
	"Djehutimose",
	"Imhotep",
	"Ramessu",
	"Seti",
	"Menkhaf",
	"Enkil",
	"Merkha",
	"Nanefer ka ptah",
	"Neferkheperuhersekheper",
	"Nekonekh",
	"Parennefer",
	"Pawah",
	"Rahotep",
	"Rehu'ardjersen",
	"Rudjek",
	"Sarenpet",
	"Setka",
	"Woser",
	"Zezemonekh",
	"Meryatum",
	"Montuherkhopshef",
	"Neferma'at",
	"Pawah",
	"Prehirwonmef",
	"Sobek",
	"Set",
	"Benjhamut",
	"Ro an",
	"Sabaf",
	"Senenmut",
	"Surero",
	"Ty",
	"Yuf",
	"Senouphis",
	"Par ab hor",
	"Ermenihotep",
	"Astruhotep",
	"Astennu",
	"Aptera",
	"Nechtanebos",
	"Darius",
	"Aspalut",
	"Nkuku",
	"Wamukota",
	"Kamatef",
	"Hanif",
	"Horenhef",
	"Nep ra",
	"Harsaf",
	"Anum",
	"Takarut",
	"Raemsesur",
	"Senb betef",
	"Ahi",
	"Sut",
	"Ameneman",
	"Manfred",
	"Konrad",
	"Vlad",
	"Krell",
	"Bella Kor",
	"Smento",
	"Mohar",
	"Abdamelek"
];

::Const.Strings.LegendManhunterVeteranTitles <- [
	"the Blight",
	"the Iron Shackle",
	"the Steel Shackle",
	"the Reclaimer",
	"the Relentless",
	"the Hyena",
	"the Gilder\'s Watchdog",
	"the Tracker",
	"the Pursuer",
	"the Cruel",
	"the Gilder\'s Chain",
	"the Slave Catcher",
	"the Brute",
	"the Silver Manacle",
	"the Dog"
];

::Const.Strings.PeasantButcherNames <- [
	"Frederick",
	"Jason",
	"Candyman",
	"Strapface",
	"Slappy",
	"Creepshow",
	"Elmer",
	"Chucky",
	"Bates",
	"Igor",
	"Ebriah",
	"Billy",
	"Mouse",
	"Luft",
	"Patrick",
	"Cady",
	"Chapman"
];

::Const.Strings.PeasantButcherTitles <- [
	"The Psycho",
	"The Thirteenth",
	"The Peeper",
	"The Scream",
	"The Massacre",
	"The Intruder",
	"The Burning",
	"The Savage",
	"The Terror",
	"Valentine",
	"The Sleeper",
	"The Maddened",
	"The Dawn",
	"The Protege",
	"The Prowler",
	"The Pint-Sized Slasher",
	"The Hash-Slinging Slasher"
];

::Const.Strings.BanditRabbleNames <- [ "Poss" ];
