::Legends.Backgrounds <- {};
::Legends.Backgrounds.Tag <- {
	Skeleton = "skeleton",
	Zombie = "zombie"
}
::Legends.Backgrounds.BaseAttr <- {
	Female = { // Female characters trade HP for Fatigue compared to male characters
		Hitpoints = [-10, -10],
		Stamina = [10, 10]
	},
	Default = {
		Hitpoints = [60, 60],
		Bravery = [40, 40],
		Stamina = [100, 100],
		MeleeSkill = [50, 50],
		RangedSkill = [40, 40],
		MeleeDefense = [0, 0],
		RangedDefense = [0, 0],
		Initiative = [100, 100]
	},
	Skeleton = {
		Hitpoints = [50, 50],
		Bravery = [100, 100],
		Stamina = [40, 40],
		MeleeSkill = [50, 50],
		RangedSkill = [40, 40],
		MeleeDefense = [3, 3],
		RangedDefense = [5, 5],
		Initiative = [95, 95]
	},
	Zombie = {
		Hitpoints = [75, 75],
		Bravery = [100, 100],
		Stamina = [100, 100],
		MeleeSkill = [40, 40],
		RangedSkill = [20, 20],
		MeleeDefense = [-5, -5],
		RangedDefense = [-6, -6],
		Initiative = [65, 65]
	},

	resolve = function (_tag) {
		if (_tag == ::Legends.Backgrounds.Tag.Zombie)
			return ::Legends.Backgrounds.BaseAttr.Zombie;
		if (_tag == ::Legends.Backgrounds.Tag.Skeleton)
			return ::Legends.Backgrounds.BaseAttr.Skeleton;
		return ::Legends.Backgrounds.BaseAttr.Default;
	},
};

::Const.CharacterCombatBackgrounds <- [
	"disowned_noble_background",
	// "female_disowned_noble_background",
	"adventurous_noble_background",
	// "female_adventurous_noble_background",
	"retired_soldier_background",
	"swordmaster_background",
	"sellsword_background",
	"hedge_knight_background",
	"militia_background",
	"bastard_background",
	"hunter_background",
	"beast_hunter_background",
	"legend_noble_ranged",
	"legend_noble_2h",
	"legend_noble_shield",
	"assassin_background",
	"brawler_background",
	"legend_blacksmith_background",
	"raider_background"
];
::Const.CharacterLegionBackgrounds <- [ //all
	"legend_legion_slave_background",
	"legend_legion_auxiliary_background",
	"legend_legion_legionary_background",
	"legend_legion_gladiator_background",
	"legend_legion_honour_guard_background",
	"legend_legion_centurion_background",
	"legend_legion_prefect_background",
	"legend_legion_legate_background"
];
::Const.CharacterLegionBackgroundsLOW <- [
	"legend_legion_slave_background",
	"legend_legion_auxiliary_background",
	"legend_legion_legionary_background"
];
::Const.CharacterLegionBackgroundsHIGH <- [
	"legend_legion_legionary_background",
	"legend_legion_gladiator_background",
	"legend_legion_honour_guard_background",
	"legend_legion_centurion_background",
	"legend_legion_prefect_background",
	"legend_legion_legate_background"
];
::Const.CharacterBackgroundsAnimated <- [
	"adventurous_noble_background",
	"apprentice_background",
	"bastard_background",
	"beast_hunter_background",
	"beggar_background",
	"bowyer_background",
	"brawler_background",
	"butcher_background",
	"caravan_hand_background",
	"cripple_background",
	"daytaler_background",
	"deserter_background",
	"disowned_noble_background",
	"eunuch_background",
	"farmhand_background",
	// "female_adventurous_noble_background",
	// "female_disowned_noble_background",
	"fisherman_background",
	"flagellant_background",
	"gambler_background",
	"gravedigger_background",
	"graverobber_background",
	"hedge_knight_background",
	"historian_background",
	"houndmaster_background",
	"hunter_background",
	"juggler_background",
	"killer_on_the_run_background",
	"legend_herbalist_background",
	"legend_inventor_background",
	"legend_ironmonger_background",
	// "legend_nun_background",
	"legend_taxidermist_background",
	"lumberjack_background",
	"mason_background",
	"messenger_background",
	"militia_background",
	"miller_background",
	"miner_background",
	"minstrel_background",
	"monk_background",
	"peddler_background",
	"poacher_background",
	"raider_background",
	"ratcatcher_background",
	"refugee_background",
	"retired_soldier_background",
	"sellsword_background",
	"servant_background",
	"shepherd_background",
	"squire_background",
	"swordmaster_background",
	"tailor_background",
	"thief_background",
	"vagabond_background",
	"wildman_background",
	"witchhunter_background"
];
::Const.CharacterFemaleBackgrounds <- [
	"legend_shieldmaiden_background",
	"legend_witch_background",
	// "female_adventurous_noble_background",
	// "female_disowned_noble_background",
	// "legend_nun_background"
];
::Const.SupposedWitchBackgrounds <- [
	"legend_shieldmaiden_background",
	"adventurous_noble_background",
	"disowned_noble_background",
	"monk_background"
];
::Const.CharacterPartyBackgrounds <- [
	"legend_diviner_background",
	"legend_illusionist_background",
	"legend_spiritualist_background",
	"legend_entrancer_background",
	"legend_death_summoner_background",
	"legend_enchanter_background",
	"legend_warlock_background",
	"legend_witch_background",
	"legend_runesmith_background",
	"legend_transmuter_background",
	"legend_necromancer_background",
	//"legend_ancient_summoner_background",
	"legend_master_archer_background",
	"legend_berserker_background",
	"legend_necrosavant_background",
	// "legend_nun_background",
	"legend_shieldmaiden_background",
	"assassin_background",
	"legend_crusader_background",
	"legend_conjurer_background"
];

::Const.CharacterMagicBackgrounds <- [
	//"legend_ancient_summoner_background",
	"legend_conjurer_background",
	"legend_death_summoner_background",
	"legend_diviner_background",
	"legend_enchanter_background",
	"legend_entrancer_background",
	"legend_illusionist_background",
	"legend_master_archer_background",
	"legend_necrosavant_background",
	"legend_runesmith_background",
	"legend_spiritualist_background",
	"legend_transmuter_background",
	// "legend_philosopher_background", //not using these from krolock's recommendation as to the original astro/philo intentions. will leave them as possible options should we ever decide to change it
	// "legend_astrologist_background",
	"legend_warlock_background"
];

::Const.CharacterBackgroundsRandom <- [
	"adventurous_noble_background",
	"apprentice_background",
	"assassin_background",
	"barbarian_background",
	"bastard_background",
	"beast_hunter_background",
	"beggar_background",
	"bowyer_background",
	"brawler_background",
	"butcher_background",
	"caravan_hand_background",
	"cripple_background",
	"daytaler_background",
	"deserter_background",
	"disowned_noble_background",
	"eunuch_background",
	"farmhand_background",
	// "female_adventurous_noble_background",
	// "female_disowned_noble_background",
	"thief_background",
	"fisherman_background",
	"fisherman_southern_background",
	"flagellant_background",
	"gambler_background",
	"gravedigger_background",
	"graverobber_background",
	"hedge_knight_background",
	"historian_background",
	"houndmaster_background",
	"hunter_background",
	"juggler_background",
	"killer_on_the_run_background",
	"legend_cannibal_background",
	"legend_crusader_background",
	"legend_berserker_background",
	"legend_blacksmith_background",
	"legend_donkey_background",
	"legend_noble_ranged",
	"legend_noble_2h",
	"legend_noble_shield",
	"legend_ranger_background",
	"legend_shieldmaiden_background",
	"legend_vala_background",
	// "legend_witch_background",
	"legend_herbalist_background",
	"legend_inventor_background",
	"legend_ironmonger_background",
	// "legend_nun_background",
	"legend_taxidermist_background",
	// "legend_necro_background",
	"lumberjack_background",
	"mason_background",
	"messenger_background",
	"militia_background",
	"miller_background",
	"miner_background",
	"minstrel_background",
	"monk_background",
	"peddler_background",
	"poacher_background",
	"raider_background",
	"ratcatcher_background",
	"refugee_background",
	"retired_soldier_background",
	"sellsword_background",
	"servant_background",
	"shepherd_background",
	"squire_background",
	"swordmaster_background",
	"tailor_background",
	"vagabond_background",
	"wildman_background",
	// "wildwoman_background",
	"witchhunter_background",
	// "legend_diviner_background",
	// "legend_illusionist_background",
	// "legend_spiritualist_background",
	// "legend_entrancer_background",
	// "legend_death_summoner_background",
	// "legend_enchanter_background",
	// "legend_runesmith_background",
	// "legend_transmuter_background",
	// "legend_necromancer_background",
	// "legend_ancient_summoner_background",
	"legend_master_archer_background",
	// "legend_necrosavant_background",
	// "legend_conjurer_background",
	"slave_background",
	"slave_southern_background",
	"assassin_southern_background",
	"legend_dervish_background",
	"nomad_background",
	"legend_conscript_background",
	"legend_conscript_ranged_background",
	"gladiator_background",
	"legend_gladiator_prizefighter_background",
	"legend_muladi_background",
	"daytaler_southern_background",
	"legend_qiyan_background",
	"shepherd_southern_background"
];
::Const.HorseBackgrounds <- [
	"legend_horse_destrier",
	"legend_horse_rouncey",
	"legend_horse_courser"
];

