if (!("ContractTemplate" in ::Legends))
	::Legends.ContractTemplate <- {};

::Legends.ContractTemplate.Items <- {};

::Legends.ContractTemplate.Items.FlavorCampHuman <- {
	Title = "Negotiations",
	AcceptButton = "{ I accept your offer. }",
	MoreButton = "{ We need to be paid more for this. | We need more loot if we're to do it. }",
	SomethingElseButton = "{ I don't like it, how about something else? }",
	DeclineButton = "{ Forget it, this isn\'t worth it. | What a waste of time. }",
	FailedButton = "{ We won\'t risk our lives for such meager pay... }",
	IsNegotiatingText = "[img]gfx/ui/events/event_04.png[/img]{%They_employer% nods.%SPEECH_ON%Yes. Good. I was thinking about payment for your task earlier. | %They_employer% straightens up.%SPEECH_ON%So, payment. | %They_employer% smiles.%SPEECH_ON%This will make you rich, my friend. | %They_employer% takes a deep breath.%SPEECH_ON%Very well, this is what I\'m prepared to offer you. | %They_employer% puts %their_employer% hand on your shoulder, smiling reaffirmingly.%SPEECH_ON%I think I know an adequate compensation for your services. | %They_employer% gesticulates with %their_employer% hands, pointing at %their_employer% fingers as if counting something, but it means nothing to you.%SPEECH_ON%Judging from experience, this is good payment for the task. | %They_employer% nods. %SPEECH_ON%You look able, so I am willing to pay quite a bit. | %They_employer% opens the palm of %their_employer% hands.%SPEECH_ON%I\'m tight on crowns, so before you ask, this is all I have right now. | %SPEECH_ON%Rest assured that what I\'m offering you now is a fine prize for your work.} ",
	FinalOfferText = "[img]gfx/ui/events/event_04.png[/img]{%SPEECH_START%I refuse to pay any more for this.  | %SPEECH_START%Be reasonable.  | %SPEECH_START%No, no, no.  | %SPEECH_START%Who do you think you are? I tell you how you\'re getting paid.  | %They_employer% just looks at you sternly and shakes %their_employer% head.%SPEECH_ON% | %SPEECH_START%No, you are already getting more than you\'re worth.  | %SPEECH_START%No. Do not push me too far!  | %SPEECH_START%I don\'t think you quite understand how this works. We need to come to terms if you want to be paid for this. My offer still stands. }",
	GiveMoreText = "[img]gfx/ui/events/event_04.png[/img]{%SPEECH_START%This is it then?  | %They_employer% takes a deep breath.%SPEECH_ON% | %They_employer% sighs.%SPEECH_ON% | %SPEECH_START%Fair enough.  | %SPEECH_START%Fine, fine.  | %SPEECH_START%If it must be. | %SPEECH_START%Fine. How about this?  | %SPEECH_START%Sure, sure, I understand.  | %SPEECH_START%Reasonable.  | %SPEECH_START%Interesting. I think this would be more appropiate then.  | %SPEECH_START%Would you take this instead?  | %SPEECH_START%Let me make the following offer.  | %SPEECH_ON%Fair. Would you accept this instead?  | %SPEECH_START%Very well. Given your demands I offer you this.  | %SPEECH_START%Let\'s get this over with quickly. Here is my new offer.  | %SPEECH_START%We\'re all friends here, aren\'t we? Let\'s see... }",
	DeclineText = "[img]gfx/ui/events/event_74.png[/img]{%SPEECH_START%You act as if you were the only ones to hold a sword for coin. I think I\'ll look elsewhere for the men I need. Good day.%SPEECH_OFF% | %SPEECH_START%My patience has limits, too, and I think I\'m wasting my time here.%SPEECH_OFF% | %SPEECH_START%I\'ve had enough of this! I\'m sure I\'ll find someone else to do the job!%SPEECH_OFF% | %SPEECH_START%Do not insult my intelligence! Forget about this contract. We\'re done.%SPEECH_OFF% | %Their_employer% face turns red with anger.%SPEECH_ON%Get out of here, I\'m not in the habit of making deals with greedy devils!%SPEECH_OFF% | %They_employer% sighs. %SPEECH_ON%Just... forget it. I shouldn\'t have trusted you in the first place. Leave me so I can look for other, more sensible men.%SPEECH_OFF% | %SPEECH_START%I really thought we had a good relationship here. But know that I can only be pushed so far. I don\'t think this is working out. I\'ll take my leave.%SPEECH_OFF% | %SPEECH_ON%This has been an utter waste of time for me. Don\'t bother coming back until you learned some reason.%SPEECH_OFF%}"
	SingleOfferAppendix = "{You\'ll get | You are to receive | You\'ll be paid with | It\'s} this item from my private collection when the contract is done.%SPEECH_OFF%"
	MultipleOfferAppendix = "{You\'ll get | You are to receive | You\'ll be paid | It\'s} this pile of %reward_item_count% items when the contract is done.%SPEECH_OFF%"
	NoOfferAppendix = "{You\'ll be paid nothing. Is that what you want?%SPEECH_OFF%}"
};
