::mods_hookExactClass("events/events/location/artifact_reliquary_enter_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "A", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_182.png[/img]{The estate towers over the area with pure cut stoneworks and colored roofing tiles. It has something most royalty cannot afford, which is a sense of taste. With grass trimmed low, the lawn seemed almost like a footprint unto an unkept land. Statues of people dot the landscape, capturing poses both regaling and regretful. Amidst the crowd of sculptures are hedges cut into the shapes of animals and fountains with clear water in them. The company stands outside a black fence, idling and staring through the bars like farm animals. %randombrother% shakes %their_randombrother% head and spits.%SPEECH_ON%Yeah, it\'s all quite pretty and all, but no deep pocket fark is just gonna leave the front gate open like this for no reason, ya know? I think either somebody has already ran through the place, or something awful is inside and it don\'t mind the occasional innocent passerby.%SPEECH_OFF%You agree. When looking further in, you can see the path leads to a bowled out decline, as if the gods had knuckled a bit of the earth itself with overhangs and escarpments encircling the area. If you\'re going to explore such a place, you know in your heart that you might not make it back. You could still leave now and return later...}";
		});
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_182.png[/img]{You order the company into the moon-like escarpment. Suddenly, a man wearing a tall black helm swings himself around a statue. He wields an unusual staff, a trail of green mist wafting behind its glassy top.%SPEECH_ON%Welcome! Have you come to understand my work? It is in the warmth of mothering that one finds the primal instincts, the flashes of intellect which all creatures, from the feeblest worms to the most soaring birds, understand, and without which man shall never have supremacy over all things. I, a man, am mother now. I, a man, have broken the order, and on this instinct native to all creatures, I shall rise, wombless, ascending above the architecture of nature herself, and become nurturer to all! I, the Grand Diviner, the one who shall moisten this dry earth with manifestations...%SPEECH_OFF%Monologuing madmen wielding strange staffs rarely have good intentions. You draw your sword and, seeing your blade, the Grand Diviner goes quiet. He nods and swings his arms wide, a flash of green sparking from his staff. Creatures like those you've seen before - gelatinous, bulbous assemblages of vague appendages - all start shuffling out from behind the statues. More yet encircle the entire company, occupying spaces on high, saddling themselves onto the lip of the escarpments like visitors in a coliseum, ever-ready to watch a good fight. The Grand Diviner grins and points his staff at you.%SPEECH_ON%Smile, sellsword, for when you die I shall mother you back into this world, and you shall find nurture in the bosom of my power!%SPEECH_OFF%}";
		});
		::Legends.Screens.hook(this, "Victory", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_182.png[/img]{The Diviner is found in the mire of his creatures, a wounded man strewn across the afterbirth of his own manifestations. His heavy helmet guards his neck, but you simply crouch down and lever the point of your sword under it, like lifting a bucket with a dagger. He coughs and says.%SPEECH_ON%You can truly kill me no more than you can kill mother nature.%SPEECH_OFF%You nod and drive the steel through his chin until you hear its tip touch the top of his helm. Blood spews over the neckguard. Standing, you say,%SPEECH_ON%I am mother nature.%SPEECH_OFF%%randombrother% laughs.%SPEECH_ON%Nice line, captain. Sorta dumb if you think about it too much but-%SPEECH_OFF%You cut the sellsword off and tell %them_randombrother% and the rest of the men to loot the place. Surely the gothic estate has some valuables that will have made this venture worthwhile. As for the Diviner\'s curious staff still yet swirling with a faint green glow, you have it taken to inventory. As you prepare to leave, a report comes in that a number of the \'flesh golems\' ran out of the gothic estate and fled into the wild. Their progenitor is dead, but it seems you may still yet continue to find his creations.}";
		});
	};
});
