// i'm not hooking this
::Const.Strings.CharacterNames = ["Abel","Anders","Anund","Asger","Balder","Benedikt","Bjoern","Bo","Christian","Christoffer","Edvard","Einar","Erik","Ernst","Esben","Fredrik","Frej","Frode","Glum","Gnupa","Gorm","Gotfred","Gregers","Grim","Gunnar","Halfdan","Halvor","Hans","Harald","Helge","Hemming","Henrik","Hjalmar","Holger","Ingolf","Jakob","Jens","Joakim","Johann","Karl","Knud","Kristian","Leif","Lennart","Ludvig","Malthe","Mads","Mikkel","Mogens","Niels","Odd","Olav","Oluf","Peder","Poul","Ragnar","Ragnvald","Rolf","Rune","Severin","Sigfred","Sigtryg","Sigurd","Sivard","Steen","Svend","Thorolf","Thorvald","Torben","Torbjoern","Tord","Torfinn","Torgils","Ture","Ubbe","Uffe","Ulf","Valdemar","Valentin","Vilfred","Yngvar","Alv","Arne","Arnfinn","Arnkjell","Arnmod","Arnvid","Aslak","Audun","Eigil","Eilif","Eirik","Erlend","Erling","Eystein","Finn","Gudbrand","Gudleik","Gudmund","Gudroed","Guttorm","Haldor","Halkjell","Inge","Ivar","Jon","Kolbein","Lodin","Magnus","Ogmund","Orm","Ossor","Ottar","Paal","Skjalg","Skofte","Skule","Svein","Sverre","Tore","Torbrand","Torgeir","Torgil","Tormod","Torolf","Torstein","Trond","Tryggve","Ulv","Vigleik","Albrikt","Alf","Algot","Arnfast","Astrad","Azur","Bagge","Bengt","Bertil","Birger","Borkvard","Botulf","Brage","Bror","Brynjolf","Dag","Dan","Dyre","Egil","Emund","Eskild","Faste","Filip","Folke","Georg","Greger","Gustav","Halsten","Helgi","Holmger","Ingemar","Ingvar","Jedvard","Johan","Kettil","Kettilmund","Klas","Knut","Kol","Lars","Markus","Mats","Nils","Niklas","Olaf","Orvar","Sigtrygg","Starkad","Sten","Sune","Sven","Sverker","Thomas","Tjudmund","Toke","Tolir","Torkel","Torsten","Toste","Totil","Tyke","Adalvard","Rodulvard","Jaerpulf","Stenar","Brynolf","Ale","Alfr","Alfgeir","Anlaufr","Anundr","Arngrimr","Arni","Baldr","Barid","Bersi","Botulfr","Bragi","Egill","Einarr","Eirikr","Falki","Frirek","Freyr","Folki","Gandalfr","Geirr","Grimr","Gunnarr","Hakon","Haraldr","Haukr","Hrafn","Hrolfr","Hrane","Hysing","Ingjald","Kjartan","Oddr","Ofeig","Olafr","Ormr","Ottarr","Refr","Refil","Ragnarr","Rikulfr","Skuli","Snorri","Steinn","Sturla","Styrkar","Suni","Sveinn","Ulfr","Vagn","Abo","Adalbero","Adalbert","Adalbrand","Adaldag","Adalgar","Adalgod","Adolf","Aelle","Albrecht","Alebrand","Altfrid","Ansgar","Arnd","Arnold","Asig","Balduin","Balthasar","Banzleib","Beneke","Benno","Bernd","Bernhard","Bertold","Bertram","Boddic","Brun","Bruno","Burchard","Cissa","Claus","Cobbo","Cord","Cyprian","Dago","Dedo","Dethard","Detleff","Detmar","Diederik","Donar","Eggerd","Egilmar","Ekbert","Engelbert","Engelhard","Erp","Esiko","Everd","Ewald","Floribert","Freawine","Frederik","Gehrke","Gelder","Gero","Gerold","Gevert","Ghert","Giselher","Giselmar","Gosschalk","Goswin","Gunzelin","Harthgate","Hartwig","Heideke","Hengest","Henneke","Herberd","Hermann","Hinrik","Hoger","Hulderic","Humfried","Immed","Isidor","Jacob","Jaspar","Jochim","Juries","Kersten","Laurentz","Lembert","Leuderic","Liawizo","Liemar","Liudger","Luder","Ludolf","Ludwig","Marbold","Marquard","Mathias","Meinwerk","Merten","Michael","Norbert","Odo","Ordulf","Peter","Philipp","Radke","Reginbern","Reinbern","Reineke","Reinmar","Rudigar","Rudolf","Sigbert","Sigfrid","Sigward","Simon","Steffen","Thankmar","Theoderic","Theodoric","Theodwin","Thimo","Tobe","Tymmeke","Udu","Otto","Unwan","Viric","Volkwin","Volrad","Walbert","Waldemar","Waldered","Waltard","Warin","Warinechin","Wecta","Wenzel","Werneke","Weybrecht","Wichbert","Wichmann","Wicho","Widukind","Wigebert","Wilbrand","Willichin","Withgils","Witikind","Witta","Wlencing","Wolter","Wulff","Thurgot","Abrahil","Abram","Adalbald","Adalgari","Adalgrim","Aegidius","Ageric","Agilbert","Agiulf","Ailbert","Albric","Aldedramn","Andica","Ansovald","Arcambald","Aregisel","Arnegisel","Arnulf","Ascaric","Audovald","Austregisel","Autbert","Autgari","Autgeri","Avremar","Badegisel","Barnard","Berald","Bernard","Berneri","Bero","Berold","Berthefried","Bertlin","Bertrand","Ceslin","Chararic","Charibert","Childebert","Childeric","Chilperic","Chlodomer","Chlothar","Chramnesind","Clodio","Clodion","Clovis","Creat","Dagaric","Dagobert","Drogo","Eberulf","Ebregisel","Engilbert","Euric","Everard","Faroard","Faroin","Feremund","Feroard","Foroen","Frobert","Frotari","Frothard","Frothari","Frotlaic","Fulcari","Fulcrad","Galteri","Gararic","Garivald","Gaucelm","Gaudulf","Gaujoin","Gausbert","Gausbold","Gautmar","Gauzbert","Gedalbert","Gedalca","Genobaud","Gerbert","Gerhard","Gislari","Gislevert","Gocelm","Godalbert","Godomar","Gozhelm","Grimald","Guadulf","Gualtari","Gualter","Guillabert","Guitard","Gundobad","Gunthar","Guntram","Haldemar","Hartmut","Harduin","Hildebald","Hildebold","Hildegaud","Hildevold","Hildoin","Hucbert","Hugbert","Imnachar","Ingalbert","Ingomer","Ivo","Karloman","Lambert","Lantbert","Leudast","Lothar","Magnachar","Magneric","Mainard","Mallobaudes","Marachar","Marcomer","Marell","Martin","Maurifi","Meginhard","Merogais","Merovech","Munderic","Niebelung","Odelric","Odolric","Otbert","Otgeri","Otker","Pepin","Pharamond","Pippin","Radulf","Ragambald","Ragena","Ragenard","Raginari","Ragnachar","Ragnald","Ragno","Raimbold","Rainald","Ramnulf","Rathar","Raynold","Reginari","Ricchar","Rignomer","Roland","Robert","Rotbert","Segoin","Seguin","Sicbald","Sichar","Sicland","Sicleard","Siclevold","Sigebald","Sigebert","Sigeric","Sigismund","Sigobert","Sinop","Sunnegisil","Sunno","Tancrad","Tancred","Tassilo","Teotbert","Tetbert","Teutbald","Teutbert","Theoric","Theudebald","Theudemeres","Theuderic","Theudoald","Theutbald","Trutgaud","Vuitard","Vulfari","Vulframn","Vulvari","Waltgaud","Werinbert","Wilbert","Willichar","Wolfari","Adalhard","Adam","Ademar","Alarich","Alberich","Alois","Amadeus","Amalrich","Andreas","Anselm","Archembald","Augustin","Baldarich","Baldewin","Baldomar","Baldur","Berard","Berengar","Berthold","Christopher","Dieter","Dietmar","Dietpold","Dietrich","Dietwin","Eberhard","Eginolf","Ehrenfried","Ekkehard","Emelrich","Emich","Emmerich","Erich","Ferdinand","Filibert","Folkhard","Folkmar","Franz","Friedrich","Gautselin","Gebhard","Gerlach","Giselbert","Gottfried","Gotthard","Gottschalk","Gotzelo","Hartmann","Hardwin","Heinrich","Helferich","Heribert","Hesso","Hugo","Humbert","Hupold","Iwo","Karlmann","Kaspar","Konrad","Kuno","Landolf","Leopold","Liudolf","Liutbert","Liutbrand","Liutpold","Lutbert","Manegold","Manfred","Markward","Matthias","Meinhard","Milo","Nikolaus","Poppo","Radbot","Reinhard","Reinhold","Ruprecht","Rutger","Siegfried","Sieghard","Siegmund","Stefan","Theodorich","Thietmar","Udalrich","Ulrich","Viktor","Walram","Walther","Welf","Werner","Wido","Wigerich","Wilhelm","Wolfgang","Wolfram","Adelbrik","Aitet","Aldgisl","Audulf","Auutet","Avin","Avo","Avuko","Avutet","Bavo","Bentet","Blekulf","Blithulf","Brunhard","Bubo","Edulf","Egildeg","Eilbern","Eilherd","Eilulf","Eilward","Eldei","Elderd","Elhard","Engilbald","Enhard","Entet","Esulf","Euitet","Euuerhard","Focko","Folcbald","Folkbern","Folkward","Frethirik","Frethold","Frethuhard","Frethwi","Frithunath","Geldulf","Geltet","Gerbald","Gerbrand","Gerbruht","Gerdeg","Gerulf","Gerwar","Gosse","Habo","Haring","Hathuward","Hebetet","Helibad","Hessel","Hobern","Hoitet","Juw","Liaftet","Liudbad","Liudbald","Liudgod","Liudulf","Liudward","Liuppo","Lubbiko","Meginbraht","Meginulf","Meintet","Menbold","Menfrid","Menger","Menhard","Menhold","Meniko","Mentet","Menward","Merulf","Miginward","Notheri","Occo","Osnath","Popetet","Raeddeg","Rauantet","Redbad","Reginhard","Reinier","Renhard","Renward","Riklef","Rikwi","Rodbern","Saco","Salaco","Sibod","Sibraht","Sidei","Sikke","Silef","Siward","Siwi","Sjoerd","Sytse","Taco","Tadaco","Tado","Thancward","Thankbern","Thiadbold","Thiadbrund","Thiaddi","Thiaderd","Thiadulf","Thiadward","Thiadwi","Thiedold","Thonkrik","Wambald","Wening","Wentet","Wibad","Wibraht","Wibrund","Wiftet","Wigbald","Wigerd","Wihard","Wilco","Wiltet","Wulfnoth","Ygo","Adriaen","Alwin","Ambroos","Antoon","Balderik","Barend","Barnaerd","Bartolomeus","Boudewijn","Claes","Claeuwaert","Daevit","Damaes","Diederick","Dirk","Douwe","Eduard","Egmund","Emmo","Engelbrecht","Filips","Floris","Folbert","Frans","Gerard","Gerolt","Gerrit","Gijsbrecht","Godfried","Godschalk","Gozewijn","Guij","Gwijde","Hendrik","Herman","Hubert","Ijsbrand","Ijsbrecht","Jacco","Jan","Karel","Koenraad","Kristof","Lodewijk","Ludewijn","Luthard","Maertijn","Marquart","Niclaes","Olivier","Otwin","Onno","Pieter","Reinaerd","Reinoud","Reginar","Robrecht","Rodulf","Roelof","Sebastiaen","Sicco","Steven","Steyn","Theodolf","Waelram","Walter","Wicher","Willem","Wolfard","Aldrich","Hilmar","Sigbold","Siegward","Ulfert","Kalle","Espen","Hagen","Ejnar","Gunther","Jannold","Bertel","Wiedekind","Egon","Casimir","Hilderich","Wendel","Hasso","Wilreich","Torhelm","Fritz","Mattis","Birk","Adler","Elmer","Jost","Tostig","Kunold","Donbert","Erwin","Caspar","Edmund","Kunibert","Meinolf","Oskar","Giselherr","Reimar","Wernhard","Vander","Wigald","Willibald","Bjarne","Ruthard","Alrik","Hartbert","Asgeir","Horik","Hanke","Guido","Till","Geralt","Thorben","Gisbert","Wigmar","Guntbert","Eckbert","Roger","Ralf","Bernfried","Leonhard","Helmer","Falk","Diethelm","Alvar","Eberecht","Hildebert","Theudobald","Havard","Kori","Randolf","Rollo","Ingmar","Asbjorn","Steinar","Reynhart","Carsten","Eugen","Anton","Torvald","Leberecht","Ottmar","Balon","Eberold","Bertwin","Oswald","Rabe","Reimund","Wolf","Grimwald","Hallstein","Helfrich","Haribert","Tobjoern","Erland","Horst","Thorismund","Torleif","Erhard","Sorrel","Alfred","Rupert","Heimrad","Sigmar","Friso","Landrich","Lienhard","Sigmund","Reinhardt","Kurt","Bodo","Volmar","Liebwin","Eike","Malte","Raban","Rumold","Witold","Volker","Volkhart","Bertolf","Ortwin","Adelmar","Gernot","Adelbert","Reiner","Burkhard","Winrich","Wilderich","Wilfried","Raimund","Thilmann","Norman","Ludger","Markolf","Hadebrand","Roderick","Rambert","Stanley","Ybel","Clarence","Aloysius","Cosmo","Percy","Sholto","Sidney","Benezer","Absolon","Jonas","Victor","Redway","Noel","Hant","Fremin","Obert","Fray","Burnel","Grifon","Marcel","Orrick","Rodolph","Ulger","Engelard","Freskin","Dolfin","Renost","Cyon","Cicero","Leofric","Leofwin","Leofwine","Osgar","Kenward","Ulric","Harold","Dunstan","Adestan","Thirkell","Pattrik","Larkin","Felix","Donnet","Donatus","Cornelius","Benedict","Bennet","Benedick","George","Denys","Alexander","Gawain","Conan","Nicolas","Isac","Barnabas","Warner","Rowley","Randall","Rand","Maynard","Louve","Ives","Ilbert","Galien","Frank","Degore","Bardol","Arnott","Aldous","Gilbert","Nicholas","Abbo","Adaloald","Agilulf","Ahthari","Aimeric","Alboin","Arbogast","Berin","Bovo","Cleph","Faroald","Garibald","Gisulf","Gumpert","Hilderic","Imbert","Lando","Kyr","Odoin","Pandulf","Taino","Ricimer","Romuald","Vulmar","Waco","Waimar","Abbán","Abner","Abél","Accolon","Achiuir","Áengus","Aethon","Allan","Arthfael","Bedwyr","Beli","Bodfan","Bran","Caradog","Cawne","Dauid","Drust","Gareth","Ranald","Pabo","Sadwr","Urbgen","Uther","Adrien","Aimery","Alain","Aldebert","Alphonse","Amaury","Ancel","Angelbert","Antoine","Archambaud","Arnaud","Arnault","Arnoul","Aubry","Aymar","Baudouin","Bohemond","Boson","Bouchard","Centule","Charles","Clotaire","Ebbon","Enguerrand","Eudes","Eustache","Evrard","Foulques","Gargamel","Gaucher","Gaucelin","Gauthier","Geoffroy","Gelduin","Gilles","Godefroy","Guichard","Guiges","Guilhem","Guillaume","Guy","Hamelin","Henri","Herbert","Hugues","Jacques","Jaspert","Jean","Josselin","Jourdain","Julien","Lothaire","Louis","Loup","Mathieu","Maurice","Ogier","Onfroy","Orson","Othon","Payen","Philippe","Pierre","Raimbaut","Raoul","Raymond","Raynaud","Renaud","Richard","Robin","Rorgon","Rorgues","Roubaud","Savary","Sigismond","Thibault","Thierry","Valeran","Yves","Abelard","Adelard","Alfons","Anfroi","Anquetil","Armand","Arnald","Asclettin","Aubrey","Baldwin","Bertran","Beuves","Blayve","Botolf","Clemence","Errand","Faramond","Ferant","Filbert","Fulk","Fraunk","Frery","Gaillard","Gaufrid","Gerald","Geraud","Gervas","Giffard","Godfrey","Goubert","Guntard","Haimo","Henry","Hugh","Humphrey","Ildebrando","Jordan","Joscelin","Lancelin","Mauger","Nigel","Orderic","Osbern","Osmond","Oswulf","Oswyn","Radolf","Ranulf","Rayner","Rolland","Roscelin","Sayer","Serlo","Serril","Sewal","Silvester","Stefen","Torf","Turold","Turquetil","Turstin","Tybalt","William","Wymund","Acfred","Alberic","Albert","Alias","Amalric","Amaneus","Ancelmes","Archambaut","Arnaut","Artau","Aton","Aymeric","Aznar","Barral","Beneset","Bermond","Bernat","Bernat-Aton","Bernat-Ezi","Blasi","Borel","Carles","Centolh","Dat","Dodon","Doumenge","Duran","Ebles","Enric","Ermengau","Ferrand","Folquet","Frederi","Garcia","Gaston","Gautier","Girard","Girvais","Godafres","Gui","Guigues","Guiraud","Guitart","Jacme","Jaufret","Joan","Jorge","Julian","Leon","Loui","Lop","Matfre","Matias","Miquel","Nicholaus","Odon","Otton","Peranudet","Pol","Pons","Raimond","Rainaut","Rainer","Raolf","Ricard","Rogier","Sancho","Savarics","Tibaud","Toumas","Ubald","Ubert","Uc","Ugues",];

::Const.Strings.CharacterNamesFemale = ["Agnethe","Anna","Asta","Benedikte","Birgitta","Bodil","Cecilie","Christina","Dagmar","Dorothea","Elisabeth","Ellinor","Emilie","Erika","Ester","Estrid","Frederikke","Freja","Grethe","Gudrun","Gunhild","Gyda","Helena","Ida","Ingeborg","Ingegerd","Ingrid","Johanne","Jutta","Karin","Karoline","Katarina","Katrine","Kirsten","Klara","Lise","Luitgard","Lykke","Magdalene","Maren","Margrethe","Maria","Martha","Ragnfrid","Ragnhild","Rikissa","Runa","Sanna","Signe","Sigrid","Silje","Sofie","Svanhild","Thyra","Tora","Thordis","Astrid","Brigida","Cecilia","Eldrid","Gjertrud","Gudrid","Gunnhild","Gyrid","Haldora","Homlaug","Ingjerd","Jorunn","Kristina","Margrete","Ragna","Rannveig","Sunniva","Thora","Thorborg","Aleta","Alfhild","Alfridh","Beata","Bothild","Edla","Elin","Elisabet","Gyla","Gurli","Gytha","Hafrid","Holmfrid","Iliana","Inga","Ingfrid","Linda","Maer","Malmfrid","Margareta","Maerta","Saga","Sara","Sofia","Ulvhilde","Ylva","Alfhildr","Asa","Aslaug","Bothildr","Freyja","Grima","Gunnhildr","Halla","Kraka","Sif","Skuld","Svanhildr","Ulfhildr","Vigdis","Yrsa","Addila","Adelheid","Alof","Agnes","Athela","Beatrix","Bertha","Bertrada","Bia","Bisina","Bithild","Diedke","Eilika","Enda","Frederuna","Geilana","Gerberga","Gertrud","Gisela","Glismod","Hadwig","Hasala","Heilwig","Helene","Hildegard","Hrothwina","Imma","Irmgard","Irminburg","Katharina","Kunigunde","Margarete","Mathilde","Mechthild","Oda","Othelindis","Radegund","Reginlint","Richardis","Rodelinda","Sophia","Suanhilde","Theodrada","Thiedburga","Wienke","Wiltrud","Wulfhild","Adalgardis","Adallinda","Adaltrude","Adaluildis","Adelaidis","Airsenda","Albofleda","Albrada","Alda","Aldegonde","Aliberta","Alitrudis","Ansegudis","Ansegundis","Anstrude","Arsindis","Audofleda","Audovera","Austreberta","Austrechild","Balthild","Begga","Beretrude","Bernegildis","Bertenildis","Berthefled","Berthefried","Berthegund","Berthildis","Bertilla","Bladovildis","Brunhild","Burgundofara","Celsa","Celsovildis","Cesaria","Chlodosind","Chlothsinda","Clotild","Creada","Dagena","Eldesendis","Ermengardis","Ermengildis","Ermensindis","Eustadiola","Faileuba","Faregildis","Fastrada","Framberta","Fredegunde","Frolaica","Frotberga","Frotlildis","Frotlina","Galswinth","Gaudildis","Gautlindis","Genovefa","Gersvinda","Gertrude","Glodesind","Goiswinth","Gotberga","Gundrada","Halderudis","Harildis","Hildegarde","Hildegardis","Hildesendis","Hiltrude","Illegardis","Ingitrude","Ingohildis","Ingunde","Itta","Landina","Lanthechilde","Lantsida","Leubast","Leubovera","Leutberga","Leutgardis","Liutgarde","Madelgarde","Magnatrude","Marcatrude","Marcovefa","Martinga","Monegund","Morberga","Rictrude","Rigunth","Rosamund","Rothaide","Rotrude","Ruothilde","Rusticula","Sadalberga","Siclehildis","Sigalsis","Theodelinda","Theoderada","Ultrogotha","Vuldretrada","Waltrude","Adela","Adelinde","Agathe","Alberade","Amalberga","Amalie","Barbara","Benedicta","Berchte","Berta","Binhilde","Brunhilde","Christine","Cothilda","Emma","Engeltraud","Ermengard","Eufemia","Frida","Friedrica","Gerhild","Gunhilda","Hedwig","Heike","Heilwiva","Helga","Hemma","Henrike","Hildeburg","Ilsa","Ingeltrude","Irmele","Irmeltrud","Isentrude","Karlotte","Klementia","Konstanze","Kriemhild","Osterhild","Richara","Richenza","Richwara","Romilda","Serhilda","Sybille","Trude","Ulrike","Ursula","Ute","Walpurga","Wilhelmina","Winfrida","Wulfhilde","Aleberna","Alena","Aleydis","Alretieren","Amalburga","Amelgeir","Atghardis","Aue","Auesoete","Badeloghen","Baua","Bet","Breghlent","Brundonis","Dieuwke","Douwen","Eingeliadis","Elke","Emgelberna","Erkenradis","Ermegardis","Esa","Femke","Fenna","Folqui","Gerburgis","Ghela","Ghodelde","Hadewigis","Hersewindis","Hodine","Imsoete","Inka","Itsburgis","Jeltsje","Lenildis","Liedelde","Liudburgis","Lutghardis","Lys","Maike","Mareike","Mette","Minke","Nienke","Rengnalda","Volcwiif","Wendelmodis","Wiebke","Wobbe","Yda","Ymmekine","Ada","Aechte","Agaete","Aleid","Alijse","Aliken","Annelies","Badeloge","Bava","Beatrijs","Blanca","Blanceflore","Cecily","Cille","Clara","Clementia","Ellijnore","Ermingarde","Fenne","Filippa","Gheertrude","Gerda","Godila","Haduwijn","Herlinda","Hilligonda","Ide","Imagina","Irene","Isabelle","Iudith","Jacoba","Jaccobijn","Jasminne","Johanna","Jolanda","Juliana","Jutte","Kathrijne","Katrien","Liedwin","Lisebet","Machtelt","Odelt","Olinde","Onna","Pieternelle","Reynilde","Sanne","Sigerda","Sophie","Swanhildis","Thetburga","Waltrud","Wila","Wendelmoet","Wenna","Willemine","Yonefij","Yvonne","Zoete","Irma","Birgit","Blanche","Borghild","Hilda","Judith","Sibyle","Joanna","Mathilda","Agnise","Clare","Ursular","Vronika","Magrit","Eneyde","Elsa","Birgitte","Gissela","Lena","Agness","Athelyna","Alyna","Milisant","Ade","Evett","Hawyse","Emilina","Elia","Auberee","Jenna","Adriana","Mara","Trina","Amy","Amelia","Adelaide","Millicent","Hermesent","Griselda","Giselle","Emmeline","Clarimonde","Alyson","Ricolda","Orielle","Yennefer","Magdalen","Sapphira","Susannah","Masota","Tamasin","Sulley","Mollie","Jaclyn","Esobel","Ysabelon","Osane","Tibota","Elizabeth","Bess","Bershaba","Ismay","Maerwynn","Genevieve","Brangwyne","Agas","Eulalia","Katerin","Margot","Coleta","Filota","Siscella","Clariandra","Cussata","Emily","Francesse","Hilaria","Honora","Juliane","Laura","Monday","Sabyn","Hursell","Viola","Viviana","Adalsinda","Affra","Aleseta","Brida","Elsebeth","Ermengontia","Genefe","Genofeva","Kaetherlen","Adalmode","Alice","Alix","Almodis","Amelie","Anne","Antoinette","Arsinde","Aude","Aurengarde","Belleassez","Berthe","Bonne","Bourgogne","Bourguigne","Charlotte","Constance","Denise","Douce","Echive","Eglantine","Ermengarde","Ermessinde","Esclarmonde","Euphrosine","Eustachie","Eve","Gerberge","Guillaumette","Helvis","Hodierne","Isabeau","Jeanne","Julienne","Mafalda","Mahaut","Marguerite","Marie","Marthe","Mascarose","Pernelle","Perinne","Pernette","Plaisance","Raymonde","Sarrazine","Tiburge","Valence","Yolande","Adeltrudis","Agata","Ana","Arsenda","Assalhida","Ava","Azelma","Beatritz","Berenguela","Brandimena","Bregida","Brunissenda","Camila","Caterina","Clarmonda","Cloutilda","Elena","Elisa","Ermengarda","Ermessentz","Esclarmonda","Estefania","Eufrosina","Faidida","Filipa","Filomena","Francesa","Garcenda","Geneviva","Gersenda","Gisla","Guigone","Guilheumina","Heloise","Ioulanda","Joana","Mabila","Madalena","Margarida","Marquisa","Marta","Matilda","Navar","Patricia","Petronilha","Puelle","Raisenda","Raimonda","Rosa","Sibilla","Tiborg","Verounica","Violent","Adele","Adelin","Adelise","Alberada","Alienora","Aline","Alisce","Alison","Amburga","Aubrey","Aveis","Avelina","Berengaria","Busilla","Clarimond","Clemenza","Cundo","Egelina","Eleanor","Elise","Elysande","Emelenine","Emonie","Eremberga","Ermyntrude","Felicia","Flandina","Fredesende","Fressenda","Fressende","Geva","Gohilde","Gundred","Hadwis","Helewisa","Heria","Herleve","Hermessent","Hermine","Hugolina","Judit","Lesceline","Mabel","Matheode","Maud","Mautild","Maysant","Muriella","Oriel","Richenda","Rosalind","Selova","Stephanie","Sibyl","Sibylla","Umfreda","Valdrade","Wilmot","Yolanda","Yvon",];

::Const.Strings.SouthernNames = ["Jamil","Uthman","Sayid","Radwan","Thepla","Yazid","Sahir","Wahib","Amira","Aslam","Atiq","Sadan","Ayman","Hakan","Hafas","Sawar","Shuyab","Husan","Hamdun","Ayshun","Jabir","Zuhri","Jifri","Galib","Tamim","Jaquba","Zawahir","Shurayd","Walid","Musa","Ubaid","Harad","Tariq","Wasi","Fariss","Abani","Mutar","Tawid","Zahiri","Milad","Nuh","Abdari","Junaid","Malik","Naser","Jahaf","Yazir","Talha","Sabti","Harun","Firi","Rashid","Hamdin","Rasil","Hayan","Askari","Barkud","Husni","Omar","Aarôn","Abdul-Hazeem","Anisse","Mufawwiz","Ugwistan","Zaia","Relip","Wilen","Abarran","Zorion","Abu-Bakr","Aarif","Abdul-Gafur","Abdul-Jaleel","Abdul-Qadir","Abdul-Wahab","Abdul","Abdullah","Aghlab","Akin","Ali","Alim","Aram","Azam","Bahir","Burhanaddin","Fadil","Fadl","Faruk","Ghalib","Hafiz","Halil","Hasan","Husam","Hussayn","Ibrahim","Idris","Isa","Jalil","Jibril","Khaireddin","Khalil","Mahdi","Mahmud","Mansur","Mirza","Mubarak","Muhammad","Mukhtar","Murad","Muslihiddin","Muzaffaraddin","Najib","Nasr","Nizam","Qawurd","Ramadan","Sadiq","Sami","Samir","Shaiban","Shamir","Shujah","Sulayman","Talib","Ubayd","Uways","Yahya","Youkhanna","Yusuf","Zeyd","Abdul-Azeem","Abdul-Hamid","Abdul-Lateef","Abdul-Razzaq","Abdul-Wahad","Adhid","Adil","Akab","Amir","Ashraf","Aziz","Bashar","Boutros","Faisal","Fayiz","Ghazi","Hakam","Hamdan","Hashmaddin","Imamaddin","Ismat","Jahan","Kamran","Khalid","Khudayar","Majid","Muaddam","Muhsin","Muzaffar","Nasraddin","Nuraddin","Nuri","Radhi","Rasul","Salahaddin","Seyfullah","Sharaf","Sirhan","Taimur","Tawfiq","Umaya","Wahid","Yasar","Zahir","Aaron","Abanoub","Abderahman","Abdul-Aziz","Abdul-Haq","Abdul-Madjid","Abdul-Salaam","Abianos","Abisalom","Ablarion","Abraam","Adnan","Agathon","Agathonikos","Agathos","Ahmad","Akbar","Alam","Amr","Androus","Anthinos","Arsenios","Asim","Athanasios","Badr","Bashir","Biktor","Binyamin","Bishoi","Danyal","Dawlat","Ezra","Farhan","Firuz","Georgios","Ghiyasaddin","Habil","Hammud","Hanri","Haroun","Hisham","Ilyas","Izzaddin","Jalaaladdin","Jawdat","Jerjer","Kemaladdin","Krystafer","Latif","Lot","Matta","Mehtar","Mikail","Mikhael","Mina","Muammar","Murshid","Nabil","Nasir","Nassib","Pamin","Qadir","Rafiq","Ridwan","Sabah","Salim","Sharif","Suhail","Tadros","Tajaddin","Tayyib","Touma","Usama","Yared","Yassir","Youssef","Zakariyah","Abbad","Abbas","Abdallah","Abdul-Hakam","Abdul-Hasan","Abdul-Hazm","Abdul-Rahman","Abu","Adfuns","Ayyub","Balashk","Bilal","Fath","Galind","Garsiya","Hilal","Jyad","Lubb","Mubashir","Mundir","Muyahid","Raf","Rasiq","Sanyo","Siddray","Suleyman","Tifilwit","Umar","Utman","Wannaqo","Yahaff","Aden","Zainuddin","Zulfiqar",];

::Const.Strings.SouthernNamesLast.extend([
	"Eld-Taro",
	"Tel-Contar",
]);
::Const.Strings.NomadChampionTitles.extend([
	"the Midas Lord",
	"the Gilded",
]);
::Const.Strings.ExecutionerChampionTitles.extend([
	"The Ikon"
]);

::Const.Strings.NobleTitles.extend([
	"Markgraf"
]);

::Const.Strings.SellswordTitles.extend([
	"Orcbolg"
]);

::Const.Strings.HedgeKnightTitles.extend([
	"The Jouster",
	"Strongwill",
	"the Shrubbery",
	"Who Says Ni",
	"The Cleaver",
	"The Sentinel",
	"The Courageous",
	"The Chaotic",
	"The Brutal",
	"The Courteous",
	"The Angel",
	"The Heroic",
	"The Protector",
	"The Brave",
	"The Titan",
	"The Loyal",
	"The Merciful",
	"The Butcher",
	"The Horrific",
	"The Invincible",
	"The Slayer",
	"The Bear",
	"The Dragon",
	"The Unicorn",
	"Lionheart",
	"The Humble",
	"The Dreamer",
	"The Trusted",
	"The Mighty",
	"The Strange",
	"Dragonheart",
	"The Prodigy",
	"The Enigma",
	"The Divine",
	"The Black",
	"The Blue",
	"The Red",
	"The White",
	"The Grey",
	"The Cold",
	"The Warm",
	"Of The Rule",
	"Of The Ghost",
	"Of The Dawn",
	"Of The Stars",
	"Of The Sky",
	"Of The Night",
	"Of The Twilight",
	"Of The Nightfall",
	"Of The Summer",
	"Of The Winter",
	"Of The Fall",
	"Of The Spring",
	"Of The Water",
	"Of The River",
	"Of The Ice",
	"Of The Road",
	"Of The Snow",
	"Of The River",
	"Of The East",
	"Of The West",
	"Of The South",
	"Of The North"
]);

::Const.Strings.MasterArcherNames.extend([
	"The Headhunter",
	"Farsight",
	"Oneshot",
	"Trueshot",
	"Quickdraw",
	"%randomname% the Eliminator"
]);
::Const.Strings.MasonTitles.extend([
	"the Tradesman",
	"the Maker",
	"the Bricked Up"
]);
::Const.Strings.MilitiaTitles.extend([
	"the Recruit",
	"the Levyman",
	"the Trooper"
]);
::Const.Strings.BrawlerTitles.extend([
	"One Punch",
	"Hammerfist",
	"Stonehand",
	"the Hurricane",
	"the Hitman"
]);
::Const.Strings.PeddlerTitles.extend([
	"the Mountebank",
	"the Broker"
]);
::Const.Strings.WitchhunterTitles.extend([
	"the Saltzpire",
	"the Inquisitor",
	"the Righteous",
	"the Witchsmeller"
]);
::Const.Strings.GravediggerTitles.extend([
	"the Lonely",
	"Blackfinger"
]);
::Const.Strings.RatcatcherTitles.extend([
	"the Fink",
	"the Ratter",
	"the Trapper",
	"the Ratmancer",
	"the Trapper",
	"the Beagle",
	"the Scabby"
]);
::Const.Strings.BastardTitles.extend([
	"the Spare",
	"the Secret"
]);
::Const.Strings.PilgrimTitles.extend([
	"the Barefoot",
	"the Penitent",
	"the Ascetic"
]);
::Const.Strings.KnightNames.extend([
	"Sir John",
	"Sir Fenlock",
	"Sir Andrew",
	"Sir Arthur",
	"Sir Henry",
	"Sir Vincent",
	"Sir Drake",
	"Sir Edwin",
	"Sir Nelson",
	"Sir Laurel",
	"Sir Oscar",
	"Sir Gregory",
	"Sir Peter",
	"Sir David",
	"Sir Geoffrey",
	"Sir William",
	"Sir Randal",
	"Sir Talbot",
	"Sir Odo",
	"Sir Lance",
	"Sir Hugh",
	"Sir Guy",
	"Sir Diggory",
	"Sir Ademar",
	"Sir Badrick",
	"Sir Coldwell",
	"Sir Kolby",
	"Sir Yates",
	"Sir Weatherspoon",
	"Sir Rudyard",
	"Sir Wallace",
	"Sir Strong",
	"Sir Woolsey",
	"Sir Sterling",
	"Sir Quentin",
	"Sir Tarquin",
	"Sir Bertie",
	"Sir Easton",
	"Sir Godwine",
	"Sir Irving",
	"Sir Kipling",
	"Sir Rudyard",
	"Sir Melville",
	"Sir Hemingway",
	"Sir Kingsley",
	"Sir Mann",
	"Sir Farrow",
	"Sir Effingham",
	"Sir Crane",
	"Sir Darxo",
	"Sir Rue",
	"Sir Luke",
	"Sir Freykin",
	"Sir Plouf",
	"Sir Teamson",
	"Sir James",
	"Sir Percy",
	"Sir Satow",
	"dan Brock",
	"dan Gorst",
	"dan Glokta"
]);

::Const.Strings.OrcWarlordNames.extend([
	"Arvius",
]);
::Const.Strings.BanditLeaderNames.extend([
	"%randomname% the Blade",
	"Mad %randomname%",
	"Slithering %randomname%",
	"%randomname% the Smug",
	"%randomname% the Rat",
	"Toothless %randomname%",
	"Cheating %randomname%",
	"%randomname% the Nightmare",
	"%randomname% Three Fingers",
	"Scarface %randomname%",
	"Lucky %randomname%",
	"Poison %randomname%",
	"Cackling %randomname%",
	"%randomname% the Swindler",
	"%randomname% the Menace",
	"%randomname% the Viper",
	"%randomname% the King of Thieves",
	"The Abominable Bastard",
	"Lanky Jim",
	"The Duke of Destruction",
	"Barry Bigsmiles",
	"Slippery %randomname%",
	"Mad %randomname% of %randomtown%",
	"Rancid Richard",
	"The King of the Lunatics",
	"%randomname% the Human Slime",
	"Boswauld the Maggot",
	"Small Sam",
	"Saint %randomname% the Liar",
	"The Tripe King of %randomtown%",
	"%randomname% No Neck",
	"Handsome %randomname%",
	"%randomname% the Chopper",
	"Despicable Dick",
	"Killer %randomname% of %randomtown%",
	"Funny %randomname%",
	"%randomname% Priestkiller",
	"%randomname% Firestarter",
	"Rude %randomname%",
	"Nasty %randomname%",
	"The Pig",
	"Prince %randomname% Murderhand",
	"%randomname% Ubermensch",
	"Furious %randomname%"
]);
::Const.Strings.KrakenNames.extend([
	"Rap-Stofchri The Deepest One",
]);

::Const.Strings.AncientDeadNames.extend([
	"Tibon",
	"Arakus",
	"Tyran",
	"Vitalus",
	"Lefos",
	"Vasilus",
	"Kalon",
	"Mekason",
	"Eganus",
	"Baslus",
	"Duranius",
	"Kyrilepeles",
	"Furonius",
	"Nykon",
	"Dion",
	"Tadeus",
	"Sobek",
	"Lacadius",
	"Dabosa",
	"Rhemaxus",
	"Scorylo",
	"Thiamarcos",
	"Zyraxes",
	"Dromichaeta",
	"Bastiza",
	"Istros",
	"Naparis",
	"Dotos",
	"Mucapor",
	"Oroles",
	"Asteta",
	"Marcus",
	"Lucius",
	"Gaius",
	"Julius",
	"Titus",
	"Octavius",
	"Quintus",
	"Flavius",
	"Cassius",
	"Severus",
	"Tiberius",
	"Valerius",
	"Fabius",
	"Publius",
	"Decimus",
	"Antonius",
	"Pompeius",
	"Crassus", //GIVE ME BACK MY LEGIONS
	"Sulla",
	"Drusus",
	"Ignatius",
	"Cassius",
	"Brutus",
	"Cicero",
	"Gracchus",
	//Gender Neutral names:
	"Fabia",
	"Marcellus",
	"Junius",
	"Terentius",
	"Valerius",
	"Minervius",
	"Flaviana",
	"Tiberia",
	"Severa"
]);

::Const.Strings.AncientDeadNamesFemale <- [
	"Julia",
	"Claudia",
	"Cornelia",
	"Livia",
	"Octavia",
	"Aurelia",
	"Flavia",
	"Domitia",
	"Fulvia",
	"Marcella",
	"Terentia",
	"Sylvanus",
	"Flora",
	"Valeria",
	"Concordia",
	"Clementia",
	"Prudentia",
	"Aurora",
	"Junia",
	"Laetitia",
	"Diana",
	"Victoria",
	"Honoria",
	"Fortuna",
	"Juno",
	"Minerva",
	//Gender Neutral names:
	"Fabia",
	"Marcellus",
	"Junius",
	"Terentius",
	"Valerius",
	"Minervius",
	"Flaviana",
	"Tiberia",
	"Severa"
];

::Const.Strings.AncientDeadTitles.extend([
	"the Hanter",
	"the Patient",
	"the Blessed",
	"the Father",
	"the Watcher",
	"the Unbroken",
	"the Pure",
	"the Consul",
	"the Tall",
	"the Smiling",
	"the Valiant",
	"the Eagle",
	"the Bold",
	"the Wise",
	"the Cruel",
	"the Traveler",
	"the Grateful",
	"the Magnificent",
	"the Upstart",
	"the Sharp",
	"the Merciful",
	"the Cold",
	"the Temperate",
	"the Chaste",
	"the Generous",
	"the Kind",
	"the Brave",
	"the Old",
	"the Younger",
	"the Avenging",
	"the Faithful",
	"the Incorruptible",
	"the Builder",
	"the Strong",
	"the Entombed",
	"the Founder",
	"the Rested",
	"the Gladiator",
	"the Master",
	"the Tempted",
	"the Speaker",
	"the Twisted",
	"the Wanderer",
	"the Master of Ceremonies",
	"the Governor",
	"the Seneschal",
	"the Elder",
	"the Last",
	"the High Judge",
	"of the High Command",
	"the Master of Horse",
	"the Builder",
	"the Elder",
	"the Magistrate",
	"the Augur",
	"the Gladiator"
]);
::Const.Strings.GoblinNames.extend([
	"Snubb",
	"Pix",
	"Zintin",
	"Shpash",
	"Skring",
	"Zubbub",
	"Grith",
	"Trisskuz",
	"Spixik",
	"Kradix",
	"Illip",
	"Mudbung",
	"Zirgr",
	"Aggi",
	"Quixzsk",
	"Pum",
	"Gikgop",
	"Dubbzix",
	"Malox",
	"Grundr",
	"Zetmob",
	"Krippo",
	"Zimnim",
	"Akkik",
	"Blix",
	"Lebzuk",
	"Flix",
	"Kulu",
	"Dipfit",
	"Lix",
	"Figgxi",
	"Krik",
	"Nixmal",
	"Ziggum",
	"Grubxhi",
	"Woo",
	"Pezlok",
	"Xoronik",
	"Tikspit",
	"Jorisk",
	"Bogzung",
	"Ignot",
	"Zinkling",
	"Zogrok",
	"Kulzik",
	"Xatox",
	"Vekuz",
	"Carax",
	"Drukzug",
	"Xeegox",
	"Sruzuz",
	"Drutnog",
	"Nogzak",
	"Wreek",
	"Zatush",
	"Kleklux"
]);
::Const.Strings.GoblinTitles.extend([
	"the Talon",
	"Crookback",
	"the Man Mincer",
	"Snaggletooth",
	"Heelslasher",
	"Skintaker",
	"the Child Flayer",
	"Tonguebiter",
	"Hatemachine",
	"Dogsoup",
	"Headboiler",
	"Brainroaster",
	"the Hungry",
	"Childsnatcher",
	"Scalplover",
	"Screamdancer",
	"Gut Taster",
	"Legchewer",
	"the Sneakthief",
	"Mantrap",
	"Wormtooth",
	"Fat Tongue",
	"the Boil Burster",
	"Bonelicker",
	"Piglung",
	"Sharpface",
	"Stabfoot",
	"Clawbelly",
	"Hotfork",
	"Toe Taker",
	"the Man Opener",
	"Yipjaw",
	"Skinmuncher",
	"the Baby Eater",
	"the Facewearer",
	"Catgnasher"
]);
::Const.Strings.FallenHeroTitles.extend([
	"the Hollow",
	"the Black Hand",
	"the Damned",
	"the Awakened",
	"the Terrible",
	"the Doom of Man",
	"the Underlord",
	"the Soul Reaper",
	"the Eviscerator",
	"the Lord of Bones",
	"the Unyielding",
	"the Restless",
	"the Tomblord",
	"the Gravewalker",
	"the Fleshtaker",
	"the Ravenous",
	"the Banished",
	"the Immortal",
	"the Devourer",
	"the Blackguard",
	"the Suffering",
	"the Unforgiving",
	"the Resurected",
	"the Maleficent",
	"the Vengeful",
	"the Doomed",
	"the Blackhearted",
	"the Cold",
	"the Abyss",
	"Darkblood",
	"the Disturbed",
	"the Hellknight",
	"the Death Prophet",
	"the Enduring",
	"the Wraith"
]);

::Const.Strings.NecromancerNames.extend([
	"%randomname% Necrofear"
]);
