local gt = this.getroottable();
gt.translation.scenarios<-{};
local t=gt.translation.scenarios;
t["scenario.beast_hunters"]<-{name="獣狩り",
description="[p=c][img]gfx/ui/events/event_122.png[/img][/p][p]君とその部下は、文明の周辺にある村を襲った多くの獣を追い詰めることで生計を立てている。 それは危険な仕事だが報酬はいい。世の中には常に殺すべきより大きな獣と、稼ぐべきより多くのクラウンがある。\n\n[color=#bcad8c]獣狩り：[/color] 3人の獣狩りとまともな装備、そしていくつかのビーストトロフィーから開始する。\n[color=#bcad8c]追跡巧者：[/color] より遠くから足跡を確認可能。\n[color=#bcad8c]解体巧者：[/color] 君が殺した各獣は、50％の確率で追加のトロフィーをドロップする。\n[color=#bcad8c]偏見：[/color] ほとんどの人は君のような者を信用していないため、売買価格が10％悪くなる。[/p]"
,brosrawdescriptions= [{b="%name% saved you in the brigand's ambush that destroyed your band of slayers. He does not hang this fact over you, for you have saved him many a times yourself. The man suffers no emotion that does not bid him well in this world, and that alone makes him a sound slayer.",t="%name%は君の一団を壊滅させた山賊達の待ち伏せから君を救った。彼はこの事実を君にかぶせることはない、なぜなら君も何度も彼を救ってきたからだ。この男はこの世で自分に都合の悪い感情を抱くことはなく、それだけで彼を殺し屋足らしめている。"},
        {b="A young lad from the city, %name% got his start in beast slaying by rooting out the warrens of 'vicious rabbits', as he puts it. You're not sure how true that is, but regardless he has proven himself on the field of battle more times than you can count.",t="街から来た若者 %name%、彼が獣退治を始めたのは「凶暴なウサギ」の巣を根絶やしにするためだったという。その真偽のほどはわからないが、それとは関係無しに、彼は数えきれないほどの戦場で自分の力を証明してきた。"},
        {b="Grizzled vets are a rarity in beast slaying, and %name% sure ain't one. Instead, he's an intelligent man who started his foray into monster hunting by reading books instead of training the sword. Still a good enough warrior at heart, it is his study and preparation that gives him the edge in battle.",t="白髪混じりのベテランは獣退治では珍しいが、%name%は確かにそうではない。その代わり彼は知的な男で、剣を鍛える代わりに本を読むことから怪物狩りを始めた。それでも根っからの戦士であることに変わりはないが、彼が戦闘で優位に立てるのは研究と準備の賜物である。"}]
};
t["scenario.southern_quickstart"]<-{name="南方の傭兵団",
description="[p=c][img]gfx/ui/events/event_156.png[/img][/p][p]君とその小さな傭兵団は、何年もの間小さな商人の汚れ仕事をしてきたが、山賊よりはかろうじてマシというだけである。 より大きくなりたい。君の望みはそれだけだ 。 そして、ギルダーはその道を明らかにするだろう。\n\n[color=#bcad8c]南方でのクイックスタート。特に長所や短所はない。[/color][/p]"
,brosrawdescriptions= [{b="{%name% was once in a Vizier's elite vanguard. A pitched battle saw his entire legion annihilated and himself buried underneath their bodies. He was abandoned to the desert and survived by means that even to this day he will not tell you. But his unerring loyalty to you speaks more than any war story ever could.}",t="{%name%はかつて宰相の精鋭部隊に所属していた。激戦の末に彼の軍団が全滅し、彼自身もその死体の下敷きになった。彼は砂漠に捨てられ、今日に至るまで君に話すこともないような方法で生き残った。しかし、君に対する彼の揺るぎない忠誠心は、どんな戦争体験談よりも多くを物語っている。}"},
        {b="{If loyalty was gold, %name% might be the wealthiest man to stand beneath the Gilder's eye. You found the man being ambushed in an alley. Helping him fight off the thieves, he swore allegiance to you for one year. And it has been many since. Despite getting his ass kicked at first sight, %name% is a very formidable fighter when not getting bushwhacked.}",t="{忠誠心が金だったとしたら、%name%はギルダーの眼下に立つ最も裕福な男かもしれない。君は路地で襲われていた男を見つけた。強盗達を撃退するのを手伝うと、彼は一年間君に忠誠を誓った。そしてそれ以来、多くのことがあった。初めて会ったときには尻を蹴られていたが、奇襲されていなければ%name%は非常に手ごわい戦士である。}"},
        {b="{You're not entirely sure of %name%'s past, only that his path has not had as much shine as one would hope. He says he's filled many roles, but the army won't have him, and the city guard won't have him, and the women certainly won't have him, so he's taken the life as a Crownling. He thinks a glorious and hastened death will bring him to the Gilder's eye so he can ask Him why exactly He's treated his life so harshly. When he's not moping about, %name% can be cheerful and funny. Just keep him away from drinks and priests.}",t="{%name%の過去を完全に知っているわけではないが、その過去が望んでいたほど輝いていないだけである。彼は多くの役割を果たしてきたと言うが、軍は彼を望まず、市衛兵も彼を望まず、女性も当然ながら彼を望まなかったため、彼はクラウン稼ぎとしての生活を送っている。彼は栄光と早急な死がギルダーの目の前に彼を導き、なぜ自分の人生を過酷に扱ったのか尋ねることができると考えている。%name%はふさぎ込んでいないときは陽気で面白い。ただし酒と聖職者からは遠ざけた方がいい。}"}]
};
t["scenario.gladiators"]<-{name="剣闘士",
description="[p=c][img]gfx/ui/events/event_155.png[/img][/p]君は何年も南方の闘技場で戦ってきた。まずは自由のために、次にクラウンのために、そして最後は不死身になるために。他に運命は何を用意しているのだろうか？\n\n[color=#bcad8c]剣闘士: [/color]経験豊富でいい装備を持つが、日給が非常に高い3人の剣闘士で開始する。\n[color=#bcad8c]闘技場の伝説:[/color]各剣闘士は戦闘時に固有の特性を持つ。\n[color=#bcad8c]栄光の3人: [/color]君の名簿には12人までしか登録できない。また開始時の3人全員が死亡した場合、キャンペーンは終了する。"
,brosrawdescriptions= [{b="{%fullname% thinks muscles make for glory. Wrong. Captain, it is I, ",t="{%fullname%は筋肉で栄光を手に入れると思っているが、それは間違いだ。 団長、この辺りの女たちを指揮しているのは私 "},
        {b=", who commands the ladies of this realm. Need not ask me how. Behold! Look at it! Look at the size of it! Yeah. That's what I thought. Fools, train all you want, you can't have this!}",t="だ。どうやってか聞く必要はない。見ろ！これを見ろ！この大きさを見ろ！そう、これが私の考えだ。愚か者共め！好きなだけ鍛えるがいい。でもこれは得られんぞ！}"},
        {b="{%fullname% is not the best warrior here, let's be clear. Captain, look at my muscles, is it not I, ",t="{はっきりさせておくが、%fullname% はここでは一番の戦士ではない。団長、私の筋肉を見ろ。人生最大の報酬、つまり敵にとっての恐怖、それを率いるのは、俺 "},
        {b=", who commands the greatest reward of life: the fear of one's own enemies! Look, if I lather a little and catch the light, the muscles gleam. Would it not be that the heavens were mistakened for above, when all the women say they find them right here, particularly here, upon my glorious pecs?}",t="ではないか！見よ、汗に濡れ日を浴びて光る筋肉を。女たちは皆、天が上にあると勘違いしているのではないだろうか。私の輝かしい胸筋の上、特にここに天を見つけられるというのにだ。}"},
        {b="{Why are you looking at %fullname%? Captain, it is I, ",t="{なぜ%fullname%を探しているんだ？団長、最高の剣闘士は俺、"},
        {b=", who is your greatest gladiator. I am the one who swept the legs of a lindwurm and choked it out with its own tail! What you bastards say? You call that a tall tale? Pah! 'Tis a horizontal lizard at best.}",t="だ。リンドヴルムの足を払ってヤツの尻尾で首を絞めて窒息させたのは何を隠そう俺だよ！この野郎何だって？でまかせ言うなだと？ふん！あんなのぁせいぜい横長のトカゲだぜ。}"}]
};
t["scenario.early_access"]<-{name="新たなる傭兵団",
description="[p=c][img]gfx/ui/events/event_80.png[/img][/p][p] 僅かな報酬のために何年も剣を血で染め続けてきたが、君は自分の傭兵団を立ち上げるのに十分なクラウンを貯めることができた。君と共にいるのは、以前シールドウォールで肩を並べて共に戦った経験豊富な傭兵3人である。\n\n[color=#bcad8c]特に長所も短所もないクイックスタート。[/color][/p]"
,brosrawdescriptions= [{b="{You saved %name%'s life in a battle against brigands, and he returned the favor in an alley ambush by thieves. Given that common criminals are a few levels beneath brigands, you often joke with him that he is still a little behind on the 'saving each other's asses' debt.}",t="{君は山賊との戦いで%name%の命を救い、彼は路地で強盗に待ち伏せされたときに恩を返した。一般的な犯罪者は山賊より数段下であることを考えると、君はしばしば彼に対して、まだ「お互いのケツを助け合う」借りの返済が少し足りていないと冗談を言っている。}"},
        {b="{Whatever is wrong with %name% you hope he never fixes it. A character with a particular taste for battling, whoring, gambling, singing, dogfighting, skirt chasing, weirdly dish washing, vomiting and, of course, drinking, he has always been a gift to have around. He also just happens to be an excellent fighter in his own right.}",t="{%name%にどんな問題があるにせよ、君は彼がそれを直さないことを望んでいる。喧嘩、売春、ギャンブル、歌、闘犬、スカートめくり、ヘンテコな皿の洗い方、嘔吐、そしてもちろん酒が得意なのが彼のキャラクターで、常に才能に溢れている。そしてたまたま彼自体が優れた戦士でもあるだけのことだ。}"},
        {b="You crossed paths with %name% a number of times prior to his joining the company. First time you were both simple laborers. The second time you were sellswords. And now is the third go of it with him joining your company. If all goes well, he'll finally stick around this time and you'll both find the riches you seek.",t="彼が傭兵団に入る前にも、君は%name%と何度もすれ違っていた。最初は二人とも単純労働者だった。二度目は君が傭兵だった。そして三度目の今、彼は君の傭兵団に入団した。全てが順調にいけば、彼も今度こそはと粘るだろうし、二人ともが求める富を見つけるだろう。"}]
};
t["scenario.random"]<-{name="ランダム",
description="[p=c][img]gfx/ui/events/event_74.png[/img][/p][p]ランダムに選択された起源でキャンペーンを開始する。楽しそうでしょう！[/p]"
};
t["scenario.militia"]<-{name="農夫の民兵",
description="[p=c][img]gfx/ui/events/event_141.png[/img][/p][p]家を守るために志願する勇気があるか、あるいはその必要に迫られた人で構成された雑多な民兵団は、今や小さな軍隊へと成長した。 毎日食糧を必要とする軍隊へ。 民兵のサービスを借りることはできるだろうか？\n\n[color=#bcad8c]農民の軍団：[/color] 装備の乏しい農民12人で開始する。\n[color=#bcad8c]人海戦術：[/color]最大16人を一度に戦場に連れて行くことができ、最大25人まで名簿に登録できる。\n[color=#bcad8c]薄汚れた農民：[/color]：身分の高い出自の者を雇用できない。[/p]"
,brosrawdescriptions= [{b="%name% is a farmer's son, and presumably wishes to be the father of his own son at some point. For now, he's with you which is quite a regrettable clash between dreams and reality.",t="%name%は農夫の息子であり、いつかは自分の息子の父親になりたいと思っているだろう。今のところ、彼は君と共にいる。それは夢と現実の衝突であり、残念なことだ。"},
        {b="%name% owned a farmstead that has long since gone underfoot of countless passing armies, including the very ones he has fought for. His 'allegiance' to you is arguably the result of an empty belly more than anything.",t="%name%は農場を所有していたが、その農場は、彼が戦ってきた軍隊を含め、数え切れないほどの通過する軍隊の足に長い間踏み躙られてきた。彼の君への「忠誠」は、何よりも空腹からくるものであることは間違いない。"},
        {b="It is a common joke that %name% is in fact a nobleman hiding away from the world, but to the best of your knowledge he was a simple poacher. The grind of the world got him to where he is today, not much else need be said other than you hope he gets back on his feet.",t="%name%が実は世間から身を隠している貴族であるというのはよくある冗談だが、君の知る限り、彼はただの密猟者だった。世間の苦難が彼を今の場所に押し込めたのだろうが、彼が立ち直ることを願う以外に言うべきことはない。"},
        {b="You notice that %name% hides from certain noblemen. It is likely that he is a common criminal at large for some petty crime, but so long as he fights well it is no business to you.",t="君は%name%が特定の貴族から隠れていることに気づいている。おそらく彼は微罪で逃亡中の犯罪者なのだろうが、彼がうまく戦っている限り、君には関係のないことである。"},
        {b="A daytaler and common laborer, %name% would rather join your outfit than go back to wasting his body building some nobleman's new fancy foyer.",t="日雇い労働者であり平凡な労働者である%name%は、貴族の新しい豪華な玄関を建てるために身体を浪費するぐらいなら、君の団に加わりたいと思っている。"},
        {b="Seeking riches, %name% has come to the right place in your newfound mercenary band. Unfortunately, his background is in farming, milling, and laying stone, particularly none of which he was any good at.",t="富を求めて、%name%は君の新しい傭兵団の適切な場所に来た。残念ながら、彼の経歴は農業、製粉、石材加工で、特に得意なものはなかった。"},
        {b="%name% states he was a sailor prior to coming inland and falling in with the militia and now your mercenary band. He hopes to eventually own a boat and put its sails to the open ocean. You hope he can do that someday, truly.",t="%name%は、内陸に来る前、つまり民兵団や君の傭兵団に落ちる前は船乗りだったと言っている。彼はいずれ自分の船を持ち、大海原に帆を張ることを望んでいる。君はいつの日か本当にそれが叶うことを願っている。"},
        {b="%name% has apparently been in many militias, all of which eventually dissolved for one reason or another. At no point has he made any money in any of them, so he hopes to changes that with this whole new sellswording schtick.",t="%name%は多くの民兵団に所属していたようだが、その全てが何らかの理由で最終的に解散した。彼はそのいずれでも金を稼いだことは一度もないため、この新しい傭兵の仕事でそれを変えようと考えている。"},
        {b="A proper lad, %name% enjoys carousing ladies at the pub and chasing skirt in the church. You get the sense he's only tagged along to spread his sense of 'fun' around the world.",t="まっとうな若者である%name%は、パブで女性をなだめたり、教会でスカートを追いかけたりするのを楽しんでいる。彼の「楽しい」という感覚を世界中に広めるために付き合わされているようにしか君には感じられないが。"},
        {b="Daytaler, laborer, caravan hand, sailor, militiaman, %name%'s done a bit of it all. Hopefully this new foray into mercenary work will stick for him.",t="日雇い、労働者、キャラバン隊員、船乗り、民兵、%name%はその全てを少しずつこなしてきた。傭兵稼業への新たな進出が定着することを願っている。"},
        {b="Like yourself, %name% was fed up with militias being overused to solve the crises of unprepared nobles. He was arguably the most earnest of the men in joining the transition to mercenary work.",t="君と同様、%name%も準備不足の貴族の危機を解決するために民兵が乱用されていることにうんざりしていた。彼は間違いなく、傭兵稼業への転身に参加する男の中では最も熱心だった。"},
        {b="%name% is, ostensibly, running away from his wife. You met her once and approve his escape plan entirely, and not just because it affords you another body on the front line.That wench is genuinely crazy.",t="%name%は表向きは妻から逃げている。君は一度彼女に会い、彼の逃亡計画を全面的に承認したが、それは前線でもう1人戦えるからという理由だけではない。あの女は本当に狂っている。"}]
};
t["scenario.cultists"]<-{name="ダヴクル狂信者",
description="[p=c][img]gfx/ui/events/event_140.png[/img][/p][p]ダヴクルが待っている。君は古代神を信奉する小集団を率いている。信者を増やし、富を得て、生贄でダヴクルを喜ばせろ。\n\n[color=#bcad8c]狂信者: [/color] 貧弱な装備の4人の狂信者から開始する。無料で追加の狂信者が集団に加わるかもしれない。\n[color=#bcad8c]生贄: [/color] ダヴクルは時折生贄を要求するが、彼に忠誠を尽くす者には恩恵を与える。[/p]"
,brosrawdescriptions= [{b="When %name% joined, he warmly called you captain, saying \"tis a proper manner to pursue the path into the black from whence we came\".",t="%name%が加入したとき、彼は温かく君を隊長と呼びこう言った、「これがどこから来たのかわからない暗黒への道を追求する正しい方法ですよ」"},
        {b="%name% found you upon the road. He stated that he knew you were a mercenary captain. You wore but ordinary cloth at that moment, but he said by Davkul's darkness you had an aura of wanted black about you.",t="%name%は道で君を見つけた。 彼は君が傭兵団長であることを知っていたという。 そのとき君は普通の服を身につけていたが、ダヴクルの闇により君には暗黒を求めるオーラがある、と彼は言った。"},
        {b="A quiet man, %name% has shadows beneath his fingerprints, running like the brine beneath a pallid shore. When he shook your hand, it was as though you could hear the hissing of your sanity.",t="無口な男、%name%は指紋の下に影があり、それは蒼白い海岸の下の塩水のように流れている。 彼が君の手を握ったとき、正気がシッと制止する音が聞こえたような気がした。"},
        {b="%name% banded with you outside a tavern. The first time you saw him he had scars running up his arms and across veins that would imply he should not still be living. But each morning it appears as though his scars move, slowly creeping in one direction: toward his forehead.",t="%name%は酒場の外で君と組んだ。 彼を初めて見たとき、腕や血管を横切って走っている傷跡があり、それは彼がまだ生きているはずではないようなものだった。 しかし、毎朝彼の傷跡が動き、ゆっくりと一方向に忍び寄っているように見えるのだ。彼の額に向かって。"}]
};
t["scenario.manhunters"]<-{name="人狩り",
description="[p=c][img]gfx/ui/events/event_172.png[/img][/p][p]都市国家と遊牧民の絶え間ない争いはいい商売になる。君の部隊の大部分は捕虜で、自由を得るために戦うことを余儀なくされており、彼らの階級は戦いのたびに成長していく。\n\n[color=#bcad8c]奴隷商部隊:[/color] 奴隷使い2人と奴隷4人でスタート。一度に16人までの兵士を戦場に連れて行くことができる。奴隷の数よりそうでないメンバーの数が多い場合、士気が下がる。\n[color=#bcad8c]監督官:[/color] 全ての奴隷以外のメンバーは戦闘中に奴隷に鞭を打ち、士気を回復してステータスにバフをかけることができる。\n[color=#bcad8c]奴隷:[/color] 奴隷は獲得経験値が25%減少し、最大レベルが7に制限され、倒されると死亡する。[/p]"
,brosrawdescriptions= [{b="{In a sense, you don't particularly care for %name%. He's not hateful nor forgiving toward the prisoners of war, criminals, and the like. He just handles his business. But he's also this calm, unwavering way with you, and it's a bit bothersome. The man has so much potential, which is why you have him onboard for the %companyname%, but you just wished he showed some passion now and again.}",t="{ある意味、君は%name%のことを特に気にかけていない。彼は捕虜や犯罪者などに対して憎しみも寛容もない。彼は自分の仕事をこなしているだけだ。しかし、彼は君に対して冷静で揺るぎない態度で接するため少々厄介である。この男は多くの可能性を秘めており、だからこそ彼を%companyname%に参加させたのだが、たまには情熱を見せてほしいと思っている。}"},
        {b="{%name% is one of the worst people you have ever come to know. He is relentlessly brutal on the indebted, even by your measure, and is responsible for outright killing a few of your catches. That said, his mean streak will serve the company well. And given that you've already whipped him a time or three for losing inventory, you know he can take a hit as well as he can give it.}",t="{%name%は、君が今までに知り合った中で 最悪の人間の一人である。彼は、君の尺度でも、奴隷には容赦なく残忍であり、実際のところ、君が捕まえた何人かを完全に殺した責任がある。とは言え、彼の意地悪な性格は傭兵団の利益になることもあるだろう。それに在庫を減らしたことについて彼を数回鞭打ったことで、 彼も打つだけでなく打たれることがあると理解したはずだ。}"},
        {b="{You found %name% being lawed by city guards. It looked like they were gonna play a game of 'catch the scimitar' with his wrists until you intervened, opining that he owed the Gilder far before he owed any man. You hoped to offload him to high-paying Viziers, but none would take him as he was too 'learned' and seemed the exact sort of threat to spur an uprising. Unusual to a man of his standing, he does harbor a fair bit of respect for you.}",t="{君は市衛兵によって%name%が捕まったところを見つけた。衛兵たちが彼の手首を使った\"シミター取り\"ゲームを始めようとしたところで、君が介入し、彼はギルダーに借りがあるのだから人に借りを返すよりもずっと先にギルダーに借りがあると主張した。君は彼を宰相達に高値で引き渡せると考えていたが、彼は余りにも「学がありすぎて」反乱を起こしうる脅威としか思われず、 誰も相手にしてくれなかった。彼のような地位のある男には珍しく、彼は君にかなりの敬意を抱いている。}"},
        {b="{Not a friendly man by any means, but that's what the shackles are for. %name% was on the chopping block for a series of crimes when you happened upon him. You paid for his life as an investment, stating that he now owed hard work to find salvation in the Gilder's eyes. He's not so sure of your earnest beliefs, but you paid a priest to confirm that the man indeed owes his sweat to a higher sublimity.}",t="{決して友好的な男ではないが、そのための足枷である。 君が彼に出会ったとき、%name%は一連の犯罪で断頭台の上にいた。 君は彼の生命を投資として支払い、ギルダーの目に救いを見出すために懸命に働く義務があると述べた。 彼は君の真剣な信念をあまり信じていないが、君は聖職者に金を払い、彼が本当に崇高なものに汗を流しているということを確認した。}"},
        {b="{%name% is an heirloom of heresy, a man gifted to you by one of the Vizier's priests. The man was a deserter in the high lord's army, but through wealthy connections managed to avoid execution. However, there's only one way to avoid the fire of the hells, and that is through indebted gratitude. He will work for you until he finds salvation, and when that happens is entirely up to you.}",t="{％name％は異端の家宝であり、宰相の司祭の1人から贈られた男である。 その男は太公軍の脱走兵だったが、裕福なコネで処刑を免れることが出来た。 しかし、地獄の業火を避ける方法はただひとつ、恩義に報いることのみ。 彼は救いを見つけるまで君のために働くだろうし、それがいつになるかは全て君次第である。}"},
        {b="{Found on the streets, %name% never stood much of a chance. Being a beggar, it was physically easy to slap the chains on him, and socially no one would care. The Gilder cares not for those who do not work, and every day the man squandered without putting in his sweat he accrued a debt. Now it must be paid lest he taste that desert fire for eternity. He's actually healthier looking now than when you found him, though he never seems to thank you for this.}",t="{路上で見つかった％name％にはチャンスがなかった。 物乞いである彼に鎖をかけるのは物理的に簡単だったし、社会的には誰も気にしなかった。 ギルダーは働いていない者達を気にかけず、汗を流さず浪費するたびに負債を負う。 彼が永遠に砂漠の炎を味わうことのないように、借りは返さねばならない。 彼は君が彼を見つけたときよりも健康そうに見えるが、君に感謝している様子はない。}"}]
};
t["scenario.rangers"]<-{name="狩人仲間",
description="[p=c][img]gfx/ui/events/event_10.png[/img][/p][p]何年もの間、君は地元の森で密猟をし、領主の手下から逃げ回ることでそれなりの生活を送ってきた。 しかし収穫はますます少なくなり、君は決断に迫られている-君が知っているのは弓の使い方だけなのに、どうやって生計を立てるのだろう？\n\n[color=#bcad8c]狩人：[/color]3人の狩人で開始する。\n[color=#bcad8c]斥候巧者: [/color] フィールドの移動速度が速く、近くにいる敵の偵察報告を常に得ることができる。\n[color=#bcad8c]身軽な行軍：[/color] 傭兵団のインベントリとして持ち運べるアイテムが少なくなる。[/p]"
,brosrawdescriptions= [{b="{A bit of a devious runt, though a good man at heart. %name% used to hunt for his local liege, but when the nobleman died falling into an unseen ravine the hunter was blamed and kicked out of court. With some guile, he turned his hunting talents into poaching and fur trade. He is of a merchant's mind and was quick to engender the idea of mercenary work because of it.}",t="{性根は善人だが、少々邪悪な小心者。 %name%はかつて地元の領主のため猟をしていたが、貴族が見えない渓谷に落ちて死んだとき、猟師は責められ宮廷から追い出された。 悪知恵を働かせ、彼は狩猟の才能を密猟と毛皮貿易に転じた。 彼は商人気質があったため、すぐに傭兵稼業のアイデアを生み出した。}"},
        {b="{%name% fell into poaching after a drought ravaged his farmstead. Like most poachers, he is not truly of the criminal mind. Long grouped together in the hunting gangs, %name% was quick to nominate you as captain of the new sellsword outfit.}",t="{%name%は干ばつが彼の農場を荒廃させた後、密猟に手を染めた。 他の密猟者と同様、彼は本当に犯罪を犯したいとは思っていない。 長い間狩猟団で一緒に過ごしていたため、%name%はすぐに君を新しい傭兵団の団長へと推薦した。}"},
        {b="{A former jester whose gag was to shoot three water jugs out of the sky. You don't know how he got into poaching, and in fact seems rather bitter about some jester-related drama, but he is an excellent archer. He also likes to remind you that he is a far better shot than you.}",t="{空に浮かした3つの水差しを射ることが十八番であった元道化師。 彼が何故密猟に手を染めたのかは知らないし、実際、道化師にまつわる演劇については苦々しく思っているようだが、彼は優れた射手である。 彼はたびたび彼が君よりはるかに射撃が上手いことを思い出させたがる。}"}]
};
t["scenario.tutorial"]<-{name="傭兵団の再建 (チュートリアル)",
description="[p=c][img]gfx/ui/events/event_21.png[/img][/p][p]君は、以前からホガートという名の山賊を追跡してきた傭兵団の副団長である。想定外の出来事の連続は、バラバラになった傭兵団と、傭兵団を再建して元の栄光を取り戻す責任を君に残した。\n\n[color=#bcad8c]序盤に役立つガイダンスが収録されており、初めてプレイする方におすすめ。[/color][/p]"
};
t["scenario.lone_wolf"]<-{name="一匹狼",
description="[p=c][img]gfx/ui/events/event_35.png[/img][/p][p]君は長い間一人で旅をしてきた。トーナメントに参加したり、若い貴族とスパーリングをしたりしてきた。木のように背の高い放浪騎士である君は長い間ほかの誰も必要としなかった。今でもそうだろうか？\n\n[color=#bcad8c]一匹狼:[/color] 上級装備を持った経験豊富な放浪騎士1人で開始するが、資金は少ない。\n[color=#bcad8c]少数精鋭: [/color] 名簿には12人までしか登録できない。\n[color=#bcad8c]アバター：[/color] 君自身である放浪騎士が死亡するとキャンペーンは終了する。[/p]"
};
t["scenario.trader"]<-{name="交易商人",
description="[p=c][img]gfx/ui/events/event_41.png[/img][/p][p]君は小さな隊商を運営しており、ほとんどのクラウンを交易商品に投資している。 しかし、街道は危険になっている-山賊とグリーンスキンが待ち伏せており、そこにはさらに悪いことが待っているという噂がある。\n\n[color=#bcad8c]隊商：[/color] 雇った2人の護衛で開始する。\n[color=#bcad8c]商売人：[/color] あらゆる売買で価格が10%有利になる。\n[color=#bcad8c]戦士にあらず：[/color] 名声なしでスタートし、通常の66%しか名声を得られない。[/p]"
,brosrawdescriptions= [{b="A daytaler, mason, miller, %name% had done it all, passing from task to task with no dallying in making a one of them a true vocation. You weren't sure if he was long to stay as a caravan hand either, but when asked to turn to mercenary work he had no problem agreeing to that...",t="日雇い、石工、粉挽き、%name%は全ての仕事をこなし、仕事から仕事へと移り変わり、その1つ1つを天職とするために躊躇することなく渡り歩いていた。 彼がキャラバン隊員を長く続けているかどうかもわからなかったが、傭兵に転向するよう頼まれたとき、彼は何の問題もなく同意した..."},
        {b="You found %name% being thrown out of a pub and at first glance was little more than a drunken miscreant. But you watched as he fought off three would-be muggers. They managed to take his boots in the end, sure, but they couldn't truly defeat his spirit. Impressed, you took him on as a caravan hand.",t="君がパブから追い出される%name%を見かけたとき、単なる酔っ払ったゴロツキに過ぎないように見えた。 しかし、君は彼が3人の強盗を撃退するのを見た。 最終的に、強盗達は彼のブーツを奪うことは出来たが、彼の精神を本当に打ち負かすことはできなかった。感心した君は彼をキャラバン隊員として雇用した。"}]
};
t["scenario.deserters"]<-{name="脱走兵",
description="[p=c][img]gfx/ui/events/event_88.png[/img][/p][p]長い間、君は高い塔に座っている領主の気まぐれで、血生臭い戦いから別の戦いへと引きずり込まれてきた。 昨夜、君は他の3人と一緒に野営地を離れた。 まだ兵士のような格好をしてはいるが、君は脱走兵であり、ここに長く滞在しすぎると縄で縛られることになるだろう。\n\n[color=#bcad8c]脱走兵：[/color] 標準的な装備を持つ3人の脱走兵で開始する。ただし資金は少なく、君を追い詰めたい貴族家がいる。\n[color=#bcad8c]訓練された動き：[/color] 君の部下は戦闘の最初のラウンドでは常に最初に行動する。[/p]"
,brosrawdescriptions= [{b="{Prior to his conscription into the army, %name% was a failed, illiterate baker. His poor work and frequent dessert errors made him prone to being pulled into military ranks. Having always hated the life, the deserter was quick to join your cause and company.}",t="{軍に徴兵される前、%name%は落ちこぼれの文盲のパン屋だった。 仕事の出来が悪くデザートのミスも多かったため、軍に引き抜かれがちだった。 ずっとその生活を嫌っていたため、その脱走兵はすぐに君の大義と仲間に加わった。}"},
        {b="{A fine fighter by any judgment, %name% simply hated the low pay of being a soldier in the army. His pursuit of the sellsword's life makes sense. Though he is quite flighty, you believe his transient sense of allegiance will be buffered by a steady flow of good coin.}",t="{どのように判断しても立派な戦士だった%name%は、単に軍隊の兵士は低賃金であることを嫌っていた。 彼が傭兵生活を追求するのは理にかなっている。 彼はとても気まぐれだが、彼の一過性の忠誠心は、安定した収入によって和らげられると君は信じている。}"},
        {b="{%name% is like many deserters. You can see the spirit of a fighter in him, but the heart for it is withering. It doesn't make him a coward, as many assume deserters to be, but instead simply a man who may need change. Hopefully the coin of mercenary work can provide it.}",t="{%name%は多くの脱走兵と同じである。 彼の中に闘志は見えるが、その心は枯れている。 脱走兵を臆病者だと決めつけている者は多いが、そうではなく単に変化が必要な男なのだ。 傭兵稼業で得るコインがそれを提供することを願う。}"}]
};
t["scenario.raiders"]<-{name="北方の蛮族",
description="[p=c][img]gfx/ui/events/event_139.png[/img][/p][p]大人になってからずっと、君はこの土地で襲撃し、略奪してきた。 しかし、地元の農民がネズミのように貧しいため、君はより有益な傭兵という分野へと進出したいと思うかもしれない - もし、雇用主となり得る者達が君の過去の罪を許すことを厭わないならば、ではあるが。\n\n[color=#bcad8c]戦闘集団：[/color] 経験豊富な蛮族3人で開始する。\n[color=#bcad8c]略奪者：[/color] 殺した敵のアイテムを戦利品として手に入れる確率が高くなる。\n[color=#bcad8c]無法者：[/color] ほとんどの派閥との関係が悪い状態から開始する。[/p]"
,brosrawdescriptions= [{b="A sturdy warrior, %name% has been through many campaigns of raiding and pillaging. Although a man of few words, the raider is an absolutely vicious specimen in battle. Even for a raider, what he does to defeated villagers irks many. It is likely he came with you to satiate his more sadistic lusts.",t="頑丈な戦士である%name%は、襲撃や略奪といった数多くの戦闘を経験してきた。口数は少ないが、略奪者は戦闘においては非常に凶暴な人物である。略奪者と言えども、彼が敗北した村人に行うことは多くの人を苛立たせる。彼はより嗜虐的な欲望を満たすために君と一緒に来たのだろう。"},
        {b="%name% was a boy when taken from a southern village and raised amongst the barbarians of the wastes. While he learned the language and culture, he never fit in and was a constant victim of cruel jokes and games. You're not sure if he's followed you to return home or to get away from his northern 'family'.",t="%name%は南方の村から連れ去られ、荒野の蛮族の中で育った少年だった。言語や文化を学びはしたものの、決して馴染めず、常に残酷な悪ふざけやゲームの犠牲になっていた。彼が君についてきたのは、故郷に帰るためなのか、それとも北方の「家族」から逃れるためなのかはわからない。"},
        {b="Barbarian raiders often take from lands foreign to them. Most see their raids as a matter of material and women, but occasionally they will enslave formidable boys with great potential. %name%, a northerner, was such a child and he was raised to be a raider himself. Half his life was with his primitive clan, and the other half with those who took him. This has made him as hardy and brutish a warrior as one can get.",t="蛮族の襲撃者はしばしば異国の地から略奪を行う。ほとんどの者は彼らの襲撃を物資と女性の問題として見ているが、時折彼らは大きな可能性を秘めた手ごわい少年を奴隷にすることもある。北方人である%name%はそんな子供で、自らも略奪者として育てられた。彼の人生の半分は原始的な一族と共にあり、残りの半分は彼を連れ去った者達と共にある。そのため、彼は頑丈で残忍な戦士になった。"},
        {b="The man who put you on the path, you believe %name% may serve some greater role to your attaining immense treasures. You've seen northern gimps and one-armed men who would best him in combat, but his knowledge and intelligence may be sharper blades in good time.",t="君をこの道に導いた男、%name%は君が莫大な財宝を手に入れるために何か大きな役割を果たすかもしれないと信じている。君は彼に勝てる北方の片足を引きずったり片腕だったりする男達を見たことがあるだろうが、彼の知識と知性は時が経てばより鋭い刃になるかもしれない。"}]
};