local gt = this.getroottable();
gt.translation.rumors<-{};
local t=gt.translation.rumors;
t["RumorsMiningSettlement"]<-{rumors= [{b="The other day my pickaxe broke while I was hammering away. Piece of it clipped my cheek. Not much and I'd be missing an eye!",t="この間、ツルハシを打っている最中に壊れたんだよ。 その破片で頬を切っちまった。 大したことはなかったんだが、目を失くすところだったぜ！"},
        {b="The mines are a real deathtrap, we're losing men every week. Even venturing with you might be better for longevity, ha!",t="鉱山は本当に死の落とし穴だよ、毎週部下を失ってる。 アンタと一緒に冒険する方が長生きできるかもしれねぇな、ハ！"},
        {b="Working the mines has its merits, too, you know. We never get wet from the rain, it's just the dust that kills you eventually.",t="鉱山で働くのはいいこともあるもんさ。 俺達は雨に濡れることは決してないからな、結局ホコリで死ぬだけさ。"},
        {b="In the other mine shaft, %randomname% found a nugget the size of me fist! The overseer got to him before he could hide it, though.",t="もう一方の坑道で、%randomname%がオレの拳サイズの塊を見つけたんだ！ だが、そいつがそれを隠す前に監督に捕まっちまったよ。"}]
};
t["RumorsItemsBarbarians"]<-{rumorsitems= [{b="Nothing is holy to those barbarian brutes! A completely naked priest stumbled in here from %direction%. He was on the way to bring a revered relic to the temple but they took it from him.",t="あの野蛮な蛮族にとって聖なるものなどないのだ！%direction%の方角から裸に剥かれた聖職者がここに駆け込んできたのだ。 彼は寺院に聖遺物を持っていく途中だったが、彼らに奪われてしまった。"},
        {b="A mercenary company came by here hunting barbarians. The leader wielded a weapon unlike anything I ever saw before. They turned %direction% and were never to be seen again.",t="傭兵団がここに蛮族を狩りにやって来た。 リーダーは今まで見たことがないような武器を振るっていたよ。 彼らは%direction%に向かい、それから二度と戻ることはなかったがな。"},
        {b="When you head out %terrain% %direction%, keep your eyes peeled for a group of fierce wild men. They may lead you to their stash where a famed stolen weapon is said to be found.",t="%direction%の%terrain%に向かうときは、獰猛な野生の男達に気をつけておけよ。 有名な盗まれた武器があるっていう奴等の隠し場所に導いてくれるかもしれん。"},
        {b="Hark! A tribe of uncultured barbarians has been seen %direction% of here with a shield called %item% in their dirty hands! Slay them and get it back!",t="聞いてくれ！ ここの%direction%で、文明化されていない蛮族の一団がその汚れた手に%item%と呼ばれる盾を持っているのを見たんだ！ 奴らを殺し、それを取り戻してくれ！"},
        {b="A friend of a friend spotted some wildmen in the distance %direction% of here. He swears they carried a finely crafted shield. I call horseshit, as everbody knows they do not use shields like we do!",t="友達の友達がここの%direction%に向かったところで何人かの蛮族を見かけたんだ。 そいつは奴等が精巧に作られた盾を持っていたって言うんだよ。 オレはデタラメだって言ったんだ、みんな知ってるが、奴等はオレ達みたいに盾を使わない！"},
        {b="Only a good defense allows for a strong offense they say. Rumors has it, a band of barbarians %distance% to the %direction% are in the possession of a famed shield...",t="いい防御だけが強い攻撃を可能にすると言うよな。 噂によると、%direction%の%distance%にいる蛮族の一団が有名な盾を持ってるらしい..."},
        {b="I used to be trading with some of the not-so-wild barbarians %direction% of here. When I last visited them there was a magnificent shield hanging in one of their huts. They might still be hanging out there %terrain%.",t="私はここの%direction%にいたそれほど野蛮ではない蛮族の何人かと取引していた者です。 私が最後に彼らを訪ねたとき、彼らの小屋の1つに立派な盾がぶら下がっていました。 彼らはまだその%terrain%にいるかもしれません。"},
        {b="You look like you could use some better armor, my friend. If you are not scared of taking on fierce barbarians, there is a mighty fine armor to be claimed in one of their camps called %location%, %terrain% %direction% of here.",t="もっといい鎧が欲しそうだな、友よ。 獰猛な蛮族を相手にすることが恐くないのなら、ここの%direction%の%terrain%に%location%と呼ばれる彼らの野営地の1つで所有されている強力な素晴らしい鎧があるぞ。"},
        {b="The famed %item% has been guarded in the armory for decades, but when the wild men from the north came they took everything with them. They are said to be camping out somewhere in %terrain% %distance% form here.",t="有名な%item%は何十年もの間兵器庫で守られてきたが、北方から来た蛮族の男たちがやって来て、全てを持ち去ったんだ。 彼らは%distance%の%terrain%のどこかに野営していると言われているよ。"},
        {b="I came here to pick up an heirloom from my late grandfather just to get to know it has been stolen by marauding barbarians. They are said to loiter somewhere %terrain% %direction% of here, but I fear I will never get it back.",t="私は亡くなった祖父から家宝を回収するためにここに来たんですが、ちょうどそれは蛮族達によって盗まれたことが分かったところです。彼らは%direction%の%terrain%のどこかをうろついているようなのですが、私は二度と取り戻せないのではないかと危惧しています。"},
        {b="Are you also here to look for %item% like all those other fools? It is said to lie somewhere %terrain% %direction%. Nothing but hogwash if you ask me...",t="他の愚か者のようにアンタも%item%を探すためにここに来たのか？ それは%direction%の%terrain%のどこかにあると言われている。 私に言わせれば、出鱈目以外の何物でもないがね..."}]
};
t["RumorsLocation"]<-{rumors= [{b="There's a place called %location% %terrain% to the %direction% of here. Most people know about it, I think, but few would venture there.",t="%direction%の%terrain%に%location%と呼ばれる場所がある。 ほとんどの人はそれを知っていると思うが、そこに挑む者はほとんどいない。"},
        {b="%randomname% told me 'bout %location% the other day. Full of treasure he said, %distance% %direction% of here. Or maybe I'm remembering it wrong.",t="%randomname%がこの間%location%について教えてくれたんだ。 彼は、ここから%direction%へ%distance%にあるそこには宝物がいっぱいあると言っていた。もしかしたら間違って覚えているかもしれないけどね。"},
        {b="If it's adventure you seek, there's a place called %location% %terrain% %direction% of here. Don't know who lives there nowadays, though.",t="もし貴方が冒険を求めているなら、%direction%の%terrain%に%location%という場所がある。 最近誰がそこに住んでいるのかはわからないが。"},
        {b="Heard of %location%? People say it's haunted, the dead walking and all. Somewhere %direction% of here. Maybe someone else in %townname% can tell you more...",t="%location%のことを聞いたことがあるかい？ 人々はそこは幽霊や、歩く死体やなんやらで一杯だと言うんだ。%direction%のどこかだよ。 多分%townname%の誰かがもっと詳しく教えてくれるさ..."},
        {b="You know of... gosh, what was it called again? To the %direction% %distance% from here, %terrain%. Can't for the life of me remember what we used to call it...",t="知ってますよね...アレ、何て名前だったっけ？ ここから%direction%へ%distance%にある%terrain%ですよ。 どうしても思い出せないんです、昔は何て呼んでいたか…"},
        {b="Came across %location% on your way here? Why, it's %terrain% to the %direction%. Someone should hire you to burn that thing to the ground. Nothing good's coming from there, that's for sure.",t="ここに来る途中で%location%に出くわしたかい？ なぜかって言うと、それは%direction%にある%terrain%さ。 誰かが貴方を雇ってそこを焼き払わせるべきなんだ。 あそこからいいものは何も来ない、それは確かだよ。"},
        {b="We spotted something on our way here, hidden way off the road, %terrain% %distance% %direction% of %townname%. Don't know what the locals call it, or if they even know about it, but it might be worth it going back there.",t="我々はここに来る途中、%townname%から%direction%へ%distance%にある%terrain%で、道路から離れたところに隠れた何かを見つけたんです。 地元の人がそれを何と呼んでいるのか、あるいはそれについて知っているかどうかさえわかりませんが、そこに戻る価値があるかもしれませんね。"}]
};
t["RumorsTemplate"]<-{rumorstemplate= [{b="The patrons raise their cups to you, but it seems there is nothing more to be learned by talking to them tonight.",t="常連客は君にカップを掲げるが、今夜はこれ以上話を聞いても何も得られないようだ。"},
        {b="The patrons talk about this and that.",t="常連客があれやこれやと話している。"}]
};
t["RumorsTundraSettlement"]<-{rumors= [{b="You may think our land is barren and scant but once you live here you will learn to love it like no other!",t="私たちの土地は不毛で乏しいと思うかもしれませんが、ひとたびここに住めば、他の土地にはない愛着を覚えるでしょう！"},
        {b="The clans and families in these parts are still strong and define who we are. Those nancy southern folks will never understand how things work here in the north.",t="この地域の一族と家族は未だに強く、我々が何者であるかを決定付けているのさ。 あのナヨついた南の連中には、ここ北方の物事の仕組みは決して理解できないよ。"},
        {b="If you're looking to make a quick coin with some trades look around for furs. The ones from around here are the best far and wide.",t="もし貴方が交易で手っ取り早く金を稼ぎたいのなら、毛皮を探すんだな。 この辺りのものは長くて広くて最高だよ。"},
        {b="You came to the right place if you're looking for able men to bolster your company. Us northern folk are strong, rugged and honest!",t="貴方の傭兵団を強化する有能な男性を探しているんなら、貴方は正しい場所に来たよ。 我々北方の民は強く、頑丈で正直者さ！"}]
};
t["RumorsItemsBandits"]<-{rumorsitems= [{b="Word has it that a bunch of ne'er do wells %direction% from here got their hands on something real fancy and sharp through a brash heist.",t="噂によるとだな、ここから%direction%に来たロクデナシ達が、大胆な強盗をやって本当に派手で鋭利なものを手に入れたらしい。"},
        {b="Buncha lowlifes tried raiding a caravan %terrain% %distance% from here. They all got slain, but rumor has it that some valuable weapon went missing during the fight. The caravan guards have been searching for it frantically since.",t="下衆の集団がここから%distance%の%terrain%にあるキャラバンを襲撃しようとしたんだ。 奴らは全員殺されたが、噂によれば戦いの最中に貴重な武器を紛失したらしい。 それ以来、隊商の護衛達が必死にそれを探しているぞ。"},
        {b="A bewildered patron told me he was held prisoner by some rogues %terrain% %distance% from here. Said they had something real pretty with them. Some sort of curious looking weapon.",t="困惑した常連客が%distance%の%terrain%でならず者達に捕まったと言ってたよ。 何かきれいなものを持っていたとも言ってたな。 ある種の奇妙な武器だ。"},
        {b="The captain of the guard deserted a while ago to join a raider camp hidden %terrain% to the %direction%. My uncle, who served under him, claims he raided the armory before leaving and grabbed a real prize.",t="警備隊の隊長が少し前に脱走して%direction%の%terrain%に隠された略奪者の野営地に参加した。 彼の下で仕えた私の叔父は、そこを去る前に武器庫を襲撃して本当に貴重な物を手に入れたと言い張っている。"},
        {b="The captain of the guard deserted a while ago to join a raider camp hidden %terrain% to the %direction%. My uncle, who served under him, claims he raided the armory before leaving and grabbed a real prize.",t="警備隊の隊長が少し前に脱走して%direction%の%terrain%に隠された略奪者の野営地に参加した。 彼の下で仕えた私の叔父は、そこを去る前に武器庫を襲撃して本当に貴重な物を手に入れたと言い張っている。"},
        {b="I hear the famous shield %item% has been sighted. %randomname% claims that it belongs to a band of hard boiled raiders camping out %direction% of here. But then, %randomname% talks lots about things he knows nothing about.",t="有名な盾%item%が目撃されたと聞いたぞ。%randomname%は、ここから%direction%で野営している非情な略奪者の一団のものだと言い張ってる。 だが、%randomname%は自分が何も知らないことについてたくさん話すからな。"},
        {b="All anyone talks 'bout 'round these parts are damned raiders. 'Suppose they're the toast of Rumorville 'cause they gots their hands on the %item% or some such thing now. Where at? Oh, somewhere %terrain%.",t="この辺りじゃ誰もがとんでもない略奪者の話ばかりしてる。 奴等が今%item%だか何だかを手に入れたって噂の的になってるからだな。 そりゃどこだって？ ああ、どこかの%terrain%だよ。"},
        {b="A friend of a friend got robbed %direction% from here by a group of outlaws the other day. He claims the leader donned the most astonishing armor!",t="先日、友達の友達が無法者の集団にここから%direction%で強盗されたんだ。 彼の話によるとリーダー格の男が驚くような鎧を着てたんだってさ！"},
        {b="The captain of the guard deserted a while ago to join a raider camp hidden %terrain% to the %direction%. My uncle, who served under him, claims he raided the armory before leaving and grabbed a real prize.",t="警備隊の隊長が少し前に脱走して%direction%の%terrain%に隠された略奪者の野営地に参加した。 彼の下で仕えた私の叔父は、そこを去る前に武器庫を襲撃して本当に貴重な物を手に入れたと言い張っている。"},
        {b="A brash young man came through just the other day, nobility methinks, looking for an old family heirloom called %item%. Last I saw, he was heading %direction% of here.",t="つい先日生意気な若者がやってきたんだが、思うにありゃ貴族だな、%item%と呼ばれる古い家宝を探しに来てたみたいなんだ。 最後に見たとき、あいつはここから%direction%に向かっていたよ。"}]
};
t["RumorsSwampSettlement"]<-{rumors= [{b="You like mushrooms? Well, I most certainly hate them! But there's not much else to be found in this stinking swamp besides biting midges and spiders.",t="お前さんキノコは好きかい？ まぁ、オレは大嫌いなんだがな！ しかしこの悪臭を放つ沼地には刺すようなカやクモ以外に見るべきものはほとんどないぜ。"},
        {b="Traders don't come here often. Their large carriages tend to get stuck in the mud and guess who has to help them out once that happens...",t="商人達はあまりここには来ない。 彼らの大きな馬車は泥にハマりがちで、ひとたびそうなったら誰が彼らを助けなければならないか..."},
        {b="There once was a stone road leading here bringing traders, customers and all kinds of folk. One day it completely sunk into the swamp and look at this place now...",t="かつてはここに通じる石造りの道があり、商人、その客、そして様々な人々を連れてきたもんだ。 ある日それは完全に沼に沈み、今やこの場所を見てくれよ..."},
        {b="Don't wander through the swamps at night! You might get lost, yes, but out in the swamp at night there's far worse things that can happen to a man. Just ask anyone around here.",t="夜に沼地をさまよってはいかん！ 道に迷うかもしれん、ああ、だが夜の沼地では、もっと悪いことが起きるかもしれんのだ。 この辺りの誰かに聞いてみるがいい。"}]
};
t["RumorsMilitary"]<-{rumors= [{b="Ever fought an orc? It's said they're twice as tall and thrice as strong as a man, and that they can split us clean in half with a single strike!",t="オークと戦ったことがあるか？ 奴等は人間の2倍の身長と3倍の強さを持ち、一撃で俺達を半分にキレイに分割できると言われてる！"},
        {b="Picking up desperate farmers and fishers for your company is all good and well, but you should look for recruits in a castle like this one. Here you'll find people who actually know which end of the sword goes where.",t="貴方の傭兵団のために自暴自棄になった農民や漁師を拾ってくるのもいいが、このような城で新兵を探すべきだ。 ここでは、剣のどの端がどこに行くのかをちゃんと知っている人間を見つけることができる。"},
        {b="A sturdy shield is a real life-saver, let me tell you. Wouldn't have a man fight without one.",t="言わせてくれ、頑丈な盾は本当に命の恩人だ。 それなしではヒトは戦えない。"},
        {b="The garrison commander fought in the Battle of Many Names. Claims large orcs just shrug off hits to the head with a waraxe, he does. Don't know what to make of this.",t="守備隊長は「多名の戦い」で戦ったんだ。 大型のオークは戦斧を頭へ当てても軽くあしらわれるぞ、実際にやったからな、と彼は言うんだよ。 これをどう考えればいいのかわからない。"},
        {b="There're things out there way more scary than some group of brigands. You'll see what I mean soon enough if you head out beyond the borderlands.",t="そこらへんの山賊達よりも余程怖いものがある。 国境地帯を越えれば、私が何を言いたいのかすぐにわかるさ。"},
        {b="I always rely on my axe to smash the enemy's shield. Even the tallest man will fall quickly once he can not defend himself any more.",t="敵の盾を打ち砕くため、俺はいつも斧に頼ってる。 どんなに背の高い男でも、自分の身を守ることができなくなればすぐに倒れるぞ。"},
        {b="If I learned one thing during my soldiering years, it's that the high ground wins battles. Trust me on this one.",t="私が兵士時代に学んだことのひとつ、それは高台が戦いに勝つということ。 信じてくれ。"},
        {b="I once was a mercenary like you but then I took an arrow to the knee.",t="昔はお前のような傭兵だったのだが、膝に矢を受けてしまってな。"},
        {b="I've seen %randomnoble% at a tourney recently. Damn, what a sight, that man. The way he jousts, I mean. Took the prize and all the ladies loved him.",t="最近、トーナメントで%randomnoble%を見かけたんだ。 くそッ、なんて光景だ、あの男。 奴の一騎打ちのやり方だよ。 優勝したし、全ての女性に彼は愛されてた。"},
        {b="I'm old now, but I still remember my first battle. Pissed my pants even before the first arrow flew. Ha!",t="ワシはもう年をとったが、初めての戦いを今でも覚えておるぞ。 最初の矢が飛ぶ前から小便を漏らしてしまったんじゃ。 ガハハ！"},
        {b="Been to %randomtown% not long ago and they told me about wolves as large as a man, with teeth as long as the fingers on my hand. Really don't want to meet one of those.",t="少し前に%randomtown%に行ったことがあるんだが、彼らは私の手の指と同じくらいの長さの歯を持つ、ヒトと同じくらいの大きさのオオカミについて教えてくれたのさ。 そういうものには本当に会いたくないね。"},
        {b="You know that orcs make their armor out of what they strip from those who fall against them? Honest, I'm not making this up. They wear it as trophies or something. If you ever meet one of them large orcs, you'll see. They look like it's a knight or two wrapped around them.",t="オークの鎧は敵に倒れた者から剥ぎ取ったもので作るって知ってるか？ 正直なところ、これは作り話じゃないんだ。 奴等はそれをトロフィーか何かとして身につけるんだ。 大型のオークに会えばわかるよ。 まるで騎士が一人か二人巻き付いているように見える。"},
        {b="1st %townname% Company. Best lot of halfwits and scallywags I've ever served with. Wouldn't trade 'em for the world.",t="最初の%townname%傭兵団。 私が今まで所属した中で最高に間抜けで卑劣な連中だよ。 世界と引き換えにはしないだろう。"},
        {b="I miss my wife and my two daughters. Been stationed at %townname% for too long already, but a man's got to put food on the table somehow.",t="妻と2人の娘が恋しいよ。%townname%に駐留して久しいが、男はどうにかして食卓に食べ物を並べなきゃならんからな。"},
        {b="We'll head out again soon to patrol the roads. Sometimes I feel everything would go down the shitter if it weren't for us keeping order 'round here.",t="すぐにまた出かけて道路を巡回するんだ。我々がこの周辺の秩序を維持していなければ、全てが台無しになってしまうと感じることがある。"},
        {b="Farkin' patrol duty. Barely got back 'ere, blisters on me feet still from all the marchin' and we're about to 'ead out again. Just put us on 'orses, I say!",t="巡回任務クソッタレだ。 やっとの思いで戻ってきたってのによ、行軍で足にまだマメが残ってるのによ、これからまた出て行こうってんだぜ。 馬に乗せてくれ、って言いたいね！"},
        {b="Got wounded bad some months back in a skirmish 'gainst goblins. Couldn't feel me legs anymore, but the lads carried me all the way back to %townname%. Gods bless 'em.",t="ゴブリン共との小競り合いで何ヶ月か前に酷い怪我をしたんです。 もう足の感覚がなかったんですが、若者達が私を%townname%まで連れて行ってくれました。 彼等に神の祝福を。"},
        {b="You'll know greenskin territory from the idols they erect out of skulls and bones. Of human skulls and bones.",t= "グリーンスキンの支配領域は、奴等が頭蓋骨や骨で作った偶像からわかるだろう。 人間の頭蓋骨と骨だ。"},
        {b="Fourteen. That's how many men I've killed. Women I count extra, three so far. What about you?",t="14人。 俺が殺した男の数だ。 女も入れるなら、これまでのところ3人。 お前はどうだ？"},
        {b="I usually stand guard on the gate tower. To be honest, spitting down on some travellers is the only fun I get all day.",t="俺は普段門塔で警備してる。 正直なところ、旅行者達に唾を吐くことが一日の唯一の楽しみなんでね。"},
        {b="The mood amongst the garrison is pretty bad. They say that pay's been delayed a few times already and everyone's starting to lose patience.",t="駐屯地の雰囲気はかなり悪い。 もう何度も給料の支払いが遅れてて、皆我慢の限界が来てるって話だ。"},
        {b="When I was moved to %townname% I never imagined life here to be so dull and hard. But still better than working the fields until your back snaps, I suppose...",t="%townname%に引っ越したとき、ここでの生活がこんなに退屈でつらいとは想像もしていなかったよ。 それでも背骨が折れるまで畑仕事をするよりはまだマシだと思う..."},
        {b="I prefer fighting with my flail. Hard to defend against and it don't matter if they carry a shield, I'll just swing around it and make pulp of their head!",t="私はフレイルで戦うことが好きだ。 防御するのが難しくて相手が盾を持っていても関係ないから、フレイルを振り回して頭をペシャンコにするのさ！"},
        {b="Damn nigh impossible to find a reliable shield 'round here, bloody things keep breaking in two. Been keeping a spare on me back now just incase. I should charge more for fighting men with axes, ha!",t="この辺りで信頼できる盾を見つけるのはほぼ不可能に近い、血なまぐさいものが2つに割れてしまう。 万一に備えて今は予備を持ち歩いているよ。 斧を持った男達と戦うためにもっと金を貰う必要があるな、ハハハ！"},
        {b="One day I'll be standard bearer of the company. It's only the bravest of us all and they've been with the company for years and years, y'know, but it's the greatest honor for a man with common blood. I've seen even a knight once shake the hand of ours.",t="いつの日か傭兵団の旗手になりたいんだ。 団で最も勇敢な者だけがなれるし、何年もの間傭兵団にいたってことで、知っての通りだけど、それは平凡な血を引く者にとっては最高の栄誉なんだよ。 騎士でさえ握手するのを見たことがある。"},
        {b="I've trained militia before, and let me tell you, spears are the best weapons for when the men don't know what they're doing yet. Cheap and easy to hit with. Put a few men together for a spearwall and it's hard to even get close to them without a spear in your belly.",t="私は以前民兵を訓練したことがあるんだが、ひとつ言いたいのは、槍は部下がまだ自分が何をしているのかわからない時期に最適な武器だ。 安価で当てやすいからな。 何人かで槍の壁を作れば、腹に槍が付いてるのでもなければ近づくことさえ難しい。"},
        {b="Ever fought goblins? Nastly little buggers, don't be fooled by their size. I'd take large kite shields to protect the men from their arrows. And a pack of wardogs to run them down as they scatter, if you can afford it.",t="ゴブリンと戦ったことがあるかい？ 意地悪でちっぽけな虫ケラだが、サイズにだまされちゃいけねぇ。 俺なら矢から身を守るために大型のカイトシールドを持っていく。 そして買う余裕があれば、奴等が散り散りになったときに追い詰めるための軍用犬の群れもな。"}]
};
t["RumorsFarmingSettlement"]<-{rumors= [{b="Even with the bad harvest this year the landlord won't give us a rest! The high folks got to have their feasts, you know...",t="今年は不作だっていうのに、領主様は休息をお与えにならないのさ！ 高貴な方々はごちそうを食べなければならなかったもんでね..."},
        {b="If you're looking to stack up on food and supplies head over to the market and look for %randomname%. He has the best quality and the lowest prices!",t="食料品や消耗品を買い溜めしたいのなら、市場に行って%randomname%を探してみるといい。 最高のものが一番安く買えるよ！"},
        {b="I've been a farmhand all my life and sometimes I wish I'd taken the chance to venture with a company like yours... well, it's too late for that now.",t="私はずっと農夫だった、時々貴方のところのような傭兵団でチャンスを掴んでいればと...まあ、今となっては手遅れだけど。"},
        {b="There's lots of young and naive lads out there looking for adventure. I hope you take good care of them and return them safely to their families one day.",t="冒険を求めている若くて素朴な若者がたくさんいます。 大切に育てて、いつか無事に家族の元に返していただければ幸いです。"}]
};
t["RumorsGreaterEvil"]<-{rumorsitems= [{b="The nobles are quarreling again like two old hags at the garden fence. They just can't get over their pride!",t="貴族達が庭のフェンスの前で二人の老婆のようにまた言い争いをしてる。 自尊心が許さないんだろうな！"},
        {b="The nobles will take all your crowns, and your sons and husbands too, and burn them in their pointless struggles - a thousand curses 'pon them!",t="貴族達はお前のクラウンを全て奪い、息子や夫も奪い、無意味な闘争で全てを燃やすだろうさ - 彼等に千の呪いを！"},
        {b="I've served my time in the army twenty years ago. Lost an ear, see? Now my boy's marching. Was snatched right out the stables and forced into the frontline. Different war, same old shit. I pray he stays low and keeps his shield up.",t="20年前に軍隊にいたことがある。 片耳を失ったよ、見えるかい？今、私の息子が行軍中なんだ。 厩舎から引き抜かれて最前線に押し込まれた。 戦争は違っても、クソなのは昔と一緒さ。 あの子が姿勢を低くして盾を掲げ続けることを祈る。"},
        {b="The green tide keeps washing away one army after the other! We're all doomed! Doomed!",t="緑の潮は次々と軍隊を洗い流していくゥ！ 私達は破滅するッ！ 破滅するんだァ！"},
        {b="All are running from the greenskins but not me! I will stand my ground, club in one hand, pitcher in the other! Send them my way!",t="みんなグリーンスキンから逃げてるがオレは違うぜ！ 片手に棍棒、もう片方の手にピッチャーを持ってオレは立ち上がる！ 奴等をこっちに向かわせろ！"},
        {b="We barely fought off the greenskins last time at the Battle of Many Names, just barely made it, and now they're back.",t="前回の「多名の戦い」ではグリーンスキンをかろうじて撃退した、かろうじて撃退したが、また奴等が戻って来た。"},
        {b="We hear stories of more and more farms and hamlets getting burned every day. It's greenskins raiding the countryside.",t="毎日たくさんの農場や集落が焼かれているという話を聞いてる。 グリーンスキン共が田舎を襲ってるんだ。"},
        {b="May the old gods help us! The dead are stirring in their graves all over the lands. They will come and claim the living. Repent, repent and pray!",t="古の神々よ我等を助けたまえ！ 世界中の墓の中で死者が蠢いている。 彼等は来たりて生者を襲う。 悔い改めよ、悔い改めよ、そして祈るのだ！"},
        {b="The nobles are on their back foot, and nobody knows how to stop the undead menace coming for us. I have to keep my mind off of it - inkeeper! Another!",t="貴族達は後手に回っているし、アンデッドの脅威をどうやって食い止めるか誰も知らない。 気を引き締めねば- 亭主！ おかわりを！"},
        {b="Maybe I should just hang myself, get it over with and join the ranks of the marching dead. This waiting is driving me insane!",t="自分で首を吊って、さっさと終わらせて、死者の行進の仲間入りをするべきなのかも。 待ってるだけで気が狂いそうだ！"},
        {b="A man was found dead on the road. He sat upright on a donkey cart, all dried up, like a puppet of skin, tendrils, and bone. The donkey too. 'Tis like the blood was sucked right out of 'em.",t="男が道路で死んでいるのが見つかった。 彼はロバの荷車に座っていたが、完全に干からびていて、皮膚と蔓と骨の人形のようだった。 ロバもそうだった。 まるで血を吸い取られたかのように。"},
        {b="Ghastly ghosts, empty graves, otherworldly mindless slaves\nHave a glass, find a wench before your teeth will clench!\nKill the can, don't stay dry, three days until we die!",t= "おぞましい幽霊、空の墓、異世界の心無き奴隷\nグラスを持って、歯が食いしばる前にオンナを探せ！\n缶を殺し、乾いたままにするな、俺達が死ぬまであと3日！"},
        {b="%randomnoble% had his lunch come back from the dead. Was about to take a healthy bite of stuffed goose when the thing jumped from his plate and started flapping in circles. Sprayed baked apples across the living quarters. Must've been a sight to remember.",t="%randomnoble%が昼食を死から蘇らせた。 ガチョウのローストにかぶりつこうとしたとき、皿から飛び降りたガチョウが円を描いて羽ばたき始めた。 リビング全体に焼きりんごを撒き散らした。 記憶に残る光景だったに違いない。"},
        {b="Did you hear the news? Armies are rallying at %randomtown% to march south. I just hope the gilded don't strike back some day...",t="知らせを聞いたか？ 軍隊が南に進軍するために%randomtown%に集結している。 いつか金ピカが逆襲してこないことを願ってるが..."},
        {b="If you are looking for coin you should head south and teach those sun-worshippers a lesson!",t="コインを探しているなら南に向かい、太陽崇拝者に教訓を与えるべきだよ！"},
        {b="What.... WHAT!? I can't hear you! I was fighting those Gilder followers at the Oracle and something loud went up near my ear...",t="何…何！？ 聞こえない！ 私は託宣でギルダー信者と戦ってたんだが、耳元で何か大きな音がして..."},
        {b="Want some soup? I got beef and potatoes in there. No spices, though. Ran out of 'em on account of the war.",t="スープはどうだい？ 牛肉とじゃがいもが入ってるよ。 スパイスは入ってないけどね。 戦争で使い果たしたんだ。"},
        {b="The priest says that the old gods will take you in if you don't make it back from the crusade. 'Tis a good thing to know, right? Those Gilder fanatics are a dangerous lot.",t="聖職者様が言うには、もし聖戦から戻らなければ古き神々が貴方を引き取ってくれるんだとか。 知っておいて損はないですよね？ ギルダーの狂信者達は危険な連中ですから。"},
        {b="Can you believe it? %randomnoble% paid some nomad folk to guide his host through the desert. Bloody folly if true, that. Wouldn't trust those snakes as far as I can piss.",t="信じられるか？%randomnoble%は砂漠を案内させるために遊牧民を雇ったんだとよ。 もしそれが本当なら血まみれの愚行だ。 俺が小便できる限りあいつらみたいな蛇共は信用できないね。"},
        {b="A nephew of mine got killed in the desert. Poor lad. Set out to protect the faith and was ran through with a spear for it. Bastard who did it is still alive. Make 'em pay for it, I say. Make the thrice cursed lot o'em pay!",t="私の甥は砂漠で殺されたんです。 かわいそうな子だよ。 信仰を守るために出発し槍で切り裂かれたんだ。 犯人のろくでなし共はまだ生きてるんです。 奴等に報いを受けさせてください。 三度呪われた奴等に報いを！"}]
};
t["RumorsDesertSettlement"]<-{rumors= [{b="Those northeners pay good coin for our silk and spices, so we have caravans going up all the time. And caravans need escorts, you know.",t="北方人は私たちの絹や香辛料を高値で買ってくれるから、常にキャラバンを出しているんだ。 そして知ってると思うが、キャラバンには護衛が必要だよ。"},
        {b="If I can give you one piece of advice, it's this: don't venture too far out in the desert. There are things far worse than heat and sand at the edge of the world.",t="私が貴方にひとつアドバイスを与えるとするなら、それは砂漠であまり遠くまで出かけてはいけないということだ。 世界の果てには、熱や砂よりもはるかに悪いことがある。"},
        {b="Those northern dogs have no right to come into our lands, they should stay where they belong!",t="北の犬共に我々の土地に来る権利なんかない、彼等がいるべき場所にとどまるべきだ！"}]
};
t["RumorsGeneral"]<-{rumors= [{b="If you're looking to fetch a good price for your trading goods, my friend, you should go to one of the large cities or castles and not some run-down poor village at world's ass.",t="友よ、君の交易品に高値をつけたいのなら、世界の尻に敷かれた貧しい村でなく大都市や城に行くべきだよ。"},
        {b="The drinks over in %randomtown% are way better than the cat piss they serve here!",t="%randomtown%の酒は、ここで出してるネコのションベンよりもはるかに美味いぜ！"},
        {b="A trader came by this morning, claims he saw dead people shuffling through the hills nearby. Won't buy that humbug, that's for sure!",t="今朝商人がやって来て、近くの丘で死人がゾロゾロ歩いているのを見たって言うのさ。 そんなデタラメ言うヤツから買うもんなんかねぇよな！"},
        {b="There is many a place out there, long lost and forgotten, that holds great riches.",t="長い間失われ、忘れ去られていた場所には、大きな富が眠っている。"},
        {b="If you're ever visiting the tavern in %randomtown% make sure to try their roasted goat - you'll never eat that good elsewhere!",t="%randomtown%の酒場を訪ねたなら、是非ヤギの丸焼きを試してみてくれ - 他では決して食べられない味だよ！"},
        {b="Mercenaries aren't very popular around these parts. They kill, plunder and pillage like common brigands, so don't expect to be greeted with cheers and flowers.",t="傭兵はこの辺りじゃあまり人気がない。 彼らは普通の山賊みたいに殺したり、不法占拠したり、略奪するからなんだが、歓声や花束で迎えられるとは思わないでくれよ。"},
        {b="If you're in need of supplies, head over to old %randomname% on the market here in %townname%. Tell him I send you!",t="消耗品が必要なら、この%townname%にある市場の古い%randomname%に行くといい。 俺の紹介だって伝えてくれよ！"},
        {b="Tomorrow night the famous minstrel %randomname% {the Songbird | the Bard | the Storyteller | the Nightingale | the Poet} is coming to this very tavern, you better not miss it!",t="明日の夜、有名な吟遊詩人%randomname%{女性歌手 | 吟遊詩人 | 語り部 | 夜の歌手 | 詩人} がこの酒場に来ているので、お見逃しなく！"},
        {b="Don't trust the barber's potions! A friend of my cousin's friend's uncle drank one and it turned him into a toad, I swear!",t="床屋の薬は信用するな！ いとこの友達のおじさんの友達が飲んだら、ヒキガエルになってしまったんだ、ホントだよ！"},
        {b="So I heard of a free company by the name of %randommercenarycompany% and it's said they collect the ears of their enemies and wear them 'round their necks!",t="%randommercenarycompany%という名前のフリーの傭兵団のことを聞いたんだが、彼らは敵の耳を集めて首にかけていると言われているんだ！"},
        {b="Don't drink the water in %randomtown%, let me tell you. It'll give you the runs in no time!",t="ひとつ教えましょう、%randomtown%では水を飲まないでください。 すぐ腹を壊しますよ！"},
        {b="My cousin %randomname% left town with a mercenary company like yours, %randommercenarycompany% or something like that it was called. Haven't heard from him since...",t="いとこの%randomname%は、貴方のところのような傭兵団、%randommercenarycompany%とかいう団と一緒に町を出た。 それ以来彼から連絡がない..."},
        {b="From one sellsword to another: If you value your reputation as a mercenary, you'd better not double-cross your employers. Some will go to great lengths to hunt you down, tell ill of you and make you pay.",t="ある売剣から別の売剣へ：傭兵としての評判を大切にするなら、雇用主を裏切らない方がいい。 お前を追い詰め、悪口を言いふらし、代償を払わせようとする者もいる。"},
        {b="The noble houses act like an old couple; constant quarreling and wrangling. And who suffers most from those feuds? Not the high lords up in their castle towers, no, it's us simple folk, of course!",t="高貴な家は老夫婦のように振る舞う。絶え間ない口論と諍いだ。 そのような確執で最も苦しむのは誰か？ 城の塔の上にいるお偉いさん達じゃない、もちろん私達平民さ！"},
        {b="I'd stay clear of swamps and marshes. There's ghastly diseases they’re just waiting to latch onto you.",t="沼地や湿地には近づかない方がいい。 そこには恐ろしい病気があり、貴方に取り憑こうと待ち構えている。"},
        {b="I've heard they have a mage on the council of %randomtown%, a real wizard. Not sure if I believe that.",t="%randomtown%の評議会には本物の魔術師がいると聞いたことがあるよ。 それを信じるかどうかはわからないけど。"},
        {b="I love women! The way they look, the way they talk. Don't know what I'd do in a world without 'em...",t="僕は女が大好きだ！ あの見た目、話し方。 彼女達のいない世界で僕は何をすればいいかわからない..."},
        {b="It's you and the %companyname%! Remember me from %randomtown%? We talked about... well, I don't really remember, but here we are! Let's drink! How have you been faring?",t="貴方と%companyname%か！ %randomtown%の俺を覚えてるか？ 俺達は話したんだ、あの...まぁ、よく覚えてないが、俺たちゃここにいる！ 飲もうぜ！ 調子はどうだい？"},
        {b="Death is a part of life. The sooner you accept it, the more you can cherish your stay in this world.",t="死は人生の一部です。 早くそれを受け入れることで、この世での滞在を大切にすることができます。"},
        {b="One of my teeth fell out just the other day, see? I think the others are so loose, they're about to follow. Can you feel it? Go on, touch. They're loose, right?",t="つい先日、歯が1本抜けましてね、ほら。 他のもゆるくて、今にも抜けそうなんですよ。 わかるかい？ ほら、触ってみて。 ゆるいでしょう？"},
        {b="Gods, I need to take a piss. Will you watch that beer for me?",t="神よ、私はオシッコがしたいのです。 ビールを見ててくれませんか？"}]
};
t["RumorsCivilian"]<-{rumors= [{b="Always be sceptical towards the nobility, my friend. You never know what their real agenda might be.",t="貴族に対しては常に懐疑的であれ、友よ。 彼らの本当の意図が何であるかは決して知ることはできないのだから。"},
        {b="Ever considered putting down your sword and settling down? Mercenaries tend to have rather short lives.",t="剣を捨てて落ち着くことを考えたことはあるか？ 傭兵の寿命は短いぞ。"},
        {b="They found the farm of old %randomname% burned to the ground the other day. That whole family was hanging from a nearby oak...",t="この前、古い%randomname%の農場が焼け落ちているのを発見したんだ。 その家族全員が近くの樫の木にぶら下がってたよ..."},
        {b="Since some brigands burned down my old man's farm I switched the pitchfork for the beer mug. I hope they get what they deserve some day.",t="山賊達がオヤジの農場を焼き払ったから、俺はピッチフォークからビールジョッキに持ち替えたんだ。 いつか奴等が報いを受けることを願ってる。"},
        {b="Our militia is in a pitiful state, rusty pikes and worm-eaten shields everywhere. I wish the council would take crowns in hand and buy the poor sods some real weapons.",t="我々の民兵は哀れな状態で、錆びたパイクと虫食いの盾がいたるところにある。 評議会がクラウンを手に、あの哀れな人達に本物の武器を買ってあげればいいのに。"},
        {b="We don't need sellswords like you here! You're nothing but trouble. Our militia can take care of us. Always has, always will.",t="ここにお前のような傭兵は必要ない！ お前はただの厄介の種だ。 私達の民兵は自分達の面倒を見ることが出来る。 これまでも、そしてこれからもだ。"},
        {b="The miller's daughter went missing last night. They found her and she is well, but she's not willing to talk about it.",t="粉屋の娘さんが昨夜行方不明になったんだ。 彼女は見つかって元気だが、彼女はそのことについて話したがらないんだよ。"},
        {b="Farkin' %randomname% and his farkin' dog. Rug of flea's barking day and night, rain or sunshine. Can't take it much longer, I really can't...",t="クソッタレ%randomname%とヤツのクソッタレ犬め。 昼夜を問わず雨の日も晴れの日も吠え続けるノミの絨毯さ。 これ以上我慢できない、本当に無理だ..."},
        {b="I heard some tombstones in the old graveyard have been toppled over. But no one in their right mind would go there anyways.",t="古い墓地の墓石が幾つか倒されたそうです。 でも、どうせまともな人は誰もそこには行かないでしょうね。"},
        {b="Bought me this scramasax the other day from a travelling merchant. Real bargain, he said. A man's got to protect himself and his family, see.",t="先日、旅商人からこのスクラマサクスを買ってもらった。 本当に掘り出し物だって。 男は自分と家族を守らなきゃいけないからね、ほら。"},
        {b="I don't trust the militia here. One time, as a band of outlaws approached, they turned tail and ran for the hills without giving any fight!",t="私はここの民兵を信用していない。 ある時、無法者の一団が近づくと、彼らは尻尾を巻いて戦いもせずに丘に向かって走っていったんだ！"},
        {b="We had a murder here. Some bastard from %randomtown% put a knife into the back of one of the merchants. He'll see the noose on Sunday, you should come watch!",t="ここで殺人があったんだ。%randomtown%から来た野郎が、商人の1人の背中にナイフを突き刺した。 彼は日曜日にお縄になるから、見に来るべきだよ！"},
        {b="They burned %randomfemalename% at the stake last week, some witchhunter did. Just appeared one day, accused her of sorcery and whatnot and had her burned. The council didn't object and that man just left soon after. Wish I knew who he was, really. Good thing he saved us from that witch, I suppose...",t="先週、魔女狩りが%randomfemalename%を火炙りにしたんだ。 ある日突然現れて、彼女を魔術か何かの罪で告発して火刑に処した。 評議会は反対せず、その男はすぐに立ち去った。彼が誰なのかわかればよかったんだけどね、 魔女から私達を救ってくれたのはよかったんだが..."}]
};
t["RumorsContract"]<-{rumors= [{b="I've heard the council of %settlement% is looking to hire mercenaries. Don't know what for.",t="%settlement%の評議会が傭兵を雇おうとしていると聞いたよ。何のためにかわからない。"},
        {b="A group of young lads left for %settlement% some days ago. They're looking to hire armed men over there, willing to pay real good. I just hope they make it back alive.",t="若者の集団が何日か前に%settlement%に向けて出発したんだ。 向こうで武装した男たちを雇おうとしてるんだが、高い報酬を支払うそうだ。 生きて帰ってくることを願うばかりだよ。"},
        {b="If you lot is looking for work, I've heard that they're hiring sellswords over at %settlement%.",t="もし君らが仕事を探しているなら、%settlement%で傭兵を雇っていると聞いたぞ。"},
        {b="You heard that they're looking to hire fighting men at %settlement%?",t="%settlement%で戦える人間を雇おうとしているって聞いてるかい？"},
        {b="Some guy from %settlement% was here just the other day, wanted to hire strong lads for some problem they have over there. Don't think many went with him, though.",t="つい先日%settlement%から来た男がいたんだけど、向こうで抱えている問題のために強い若者を雇いたいと思っていたみたいだ。 彼と一緒に行った人は多くなかっただろうけど。"},
        {b="Mercenaries, eh? We got a few of those these days. Just some days ago a bunch that called themselves %randommercenarycompany% travelled through. On their way to %settlement%, they said, good coin to be made there.",t="傭兵だろ、えぇ？ 最近そういう連中が何人か来てるな。 ほんの数日前、%randommercenarycompany%と名乗る一団が通りかかったのさ。 %settlement%に向かう途中らしくて、あそこじゃいいカネが稼げるって言ってたぜ。"},
        {b="If it's work you're looking for, they're taking crowns in hand over at %settlement% to hire strong men.",t="もしアンタが仕事を探してるなら、強い男達を雇うために%settlement%でクラウンを手に持ってるぞ。"},
        {b="Heard that some fancy fat merchant or so from %settlement% is looking to hire armed guards the other day. Well, I ain't going to die for him, no thanks. Have me my house and wife right here.",t="先日、%settlement%の派手な太った商人が武装した警備員を雇おうとしていると聞いたよ。 まぁ、俺は彼のために死ぬつもりはないけどな、そんなのゴメンだ。 私の家と妻がここにいるんだし。"}]
};
t["RumorsForestSettlement"]<-{rumors= [{b="I've been a lumberjack all my life, just like my father before me. But the young folk these days are all 'bout adventure and seeing the lands, you may well find some hanging 'round the market that'll have no qualms 'bout coming with you on the road.",t="私は父と同じように、ずっと木こりだった。 しかし、最近の若者たちは皆、冒険と世界を見ることが全てだから、市場に行ってみれば貴方の旅に同行することに何の躊躇いもない者達がいるかもしれないな。"},
        {b="There are things in the forest... in the deep, dark parts, there are things. Nobody dares speak of them but trust me, those are no animals...",t="森には何かがいる...深く暗いところに何かが。 誰もあえてそれについて話さないが、信じてくれ、それは動物じゃない..."},
        {b="Say, you interested in woodcarvings? The works of %randomname% are true pieces of art and made our town known throughout the realm!",t="なぁ、木彫りに興味があるか？ %randomname%の作品は真の芸術作品であり、我々の町を世界中に知らしめたんだ！"},
        {b="Hiring a man of the woods could be a good idea for a mercenary like you, I'd say. They ought to know how to fling around those large axes!",t="森の男を雇うのは貴方のような傭兵にとってはいい考えかもしれないね。 彼らは大斧の振り回し方も知ってるはずだよ！"},
        {b="I've been hearing folk tell of eyes watching them from the forest's edge. Seems to be some vile creatures making their nests in these here woods. Perhaps they're sizing up their prey before striking.",t="森の端からこちらを見ている目があるという話を聞いたことがある。 この森の中に下劣な怪物達が巣を作っているみたいだな。 多分、奴らは襲う前に獲物の大きさを見定めているんだろう。"},
        {b="Long as I can remember the woods around here have been full of wildlife. Deer, boar, wolves and bear roam them in great number. Because of this it's been tradition for families to teach the art of archery at childhood. Try to outmatch any of our lads with a bow and you're sure to be disgraced.",t="私が覚えている限り、この辺りの森は野生生物がたくさんいた。 シカ、イノシシ、オオカミ、クマが数多く徘徊してる。 だから、子供の頃から弓の技術を教えるのが伝統だった。 弓で我々の若者の誰かを弓で打ち負かそうとすれば、きっと恥をかくことになる。"}]
};
t["RumorsFishingSettlement"]<-{rumors= [{b="The sea is a fickle mistress. One moment it is as calm as a mirror and the next you find yourself in a tempest fighting for your life.",t="海は気まぐれな愛人さ。 鏡のように穏やかかと思えば、次の瞬間には命懸けの大嵐に見舞われるんだ。"},
        {b="Nobody knows what lives in the deep black waters, but you hear the old fishermen talk about giant fish larger than any ship, tentacles that crush boats like they were nutshells, and evil, dead eyes under the surface.",t="真っ暗な海に何が住んでいるのかは誰にも分からないが、どんな船よりも大きい巨大な魚、木の実の殻のように小船を押しつぶす触手、そして水面下の邪悪な死の目について、老漁師達が話しているのが聞こえるだろう。"},
        {b="Some of the old fishermen will tell you that those lost at sea are cursed to walk the seabed, only to be released if they drag others down to take their place. Priest says it ain't true, but I don't know. What are the elders telling it for, then?",t="古くからの漁師の何人かは、海で遭難した人々は海底を歩く呪いをかけられていると言う者もいる、その代わりに他の人間を引きずり下ろした場合にのみ解放されると。 聖職者はそれは真実ではないと言うが、私にはわからない。 では、長老達は何を言っているのだろうな？"},
        {b="The biggest fish of my catch I always place in front of %randomfemalename%'s door to woo her. Some day I'm going to reveal myself as her secret admirer and ask for her hand!",t="釣った魚の中で一番大きな魚はいつも%randomfemalename%の家の扉の前に置いてるのさ、彼女を口説くためにね。 いつか彼女の隠れファンであることを明かして、彼女に結婚を申し込むつもりなんだ！"}]
};
t["RumorsItemsUndead"]<-{rumorsitems= [{b="Now, I don't want to start any rumors, but I saw a dead man walking around %direction% of here. His rotten hands clutched an extraordinary weapon but I'd never dare go there again in my life!",t="あぁ、噂は流したくないんだが、ここの%direction%を歩いている死人を見たんだ。 ヤツの腐った手にはとんでもない武器が握られていたんだが、もう一度あそこに行く勇気は俺にはない！"},
        {b="Some drunk scavenger came by last night, told us he'd tried to wrestle a weapon beset with gems from a dead man's hands %distance% to the %direction%. Said his grip was like a vice, and then he made a sound, so he ran off. Such nonsense, but he looked spooked as all hell.",t="昨夜、酔っ払ったゴミ漁りがやって来て、%direction% に%distance%で死人の手から宝石で包まれた武器を引き抜こうとしたと話してた。 彼の握力は万力のようで、そして声を上げたから、彼は逃げ出した。 そんな馬鹿なって話だが、奴はひどく怯えてたよ。"},
        {b="There's lots of talk about the dead walking the earth again. %randomname% says there's some to the %direction% of here. Sounds like hogwash to me.",t="死者が再び地上を歩いているという話はたくさんある。 %randomname%はここの%direction%でもそうだと言ってるよ。 僕には馬鹿げた話に聞こえるけどね。"},
        {b="Supposedly a bunch of graves %direction% of here are turning up empty. Someone said graverobbers were looking for a famed shield buried there. Strangely, nobody's actually seen those graverobbers, so maybe it's all hogwash.",t="おそらくここから%direction%にある墓の多くは空になってる。 墓荒らし共がそこに埋められた有名な盾を探していると誰かが言ってたのさ。 不思議なことに、誰も実際にその墓荒らし共を見たことがないから、多分全部デタラメなんだろうな。"},
        {b="So I watched over the steward's books and came across old maps that depicted an ancient noble burial ground %terrain% %distance% from here. However, nobody was able to find it yet. Well, some things are just not meant to be found, I suppose.",t="執事の書物に目を通し、ここから%distance%の%terrain%で古代の貴族の埋葬地が描かれた古い地図を見つけたのだ。 しかし、まだ誰も見つけることができなかった。 まぁ、見つかるはずのないものもあるのだろうな。"},
        {b="So %terrain% %direction% of here is supposedly the last resting place of a mystical piece of armor. Don't know the name myself, I just know a lot of adventurers go there and don't come back. Dunno why I told you, really. I like your business.",t="ここの%direction%の%terrain%には、神秘的な鎧の永眠の地があるらしいんだ。 私には名前はわからないけど、多くの冒険者達がそこに向かって戻ってこなかったことは知っている。 なぜ君に言ったのかわからないな、本当に。 君の仕事が好きだからかな。"},
        {b="You heard of %location%? Ask anyone around here, it's been haunting %townname% since before I was born. Folks say some armor from the gods is sealed there for all time, back from when man first settled here.",t="%location%について聞いたことがあるか？ この辺りの人に聞いてみてくれ、私が生まれる前からずっと%townname%は取り憑かれてる。 ヒトが最初にこの地に定住したときから、神々からの鎧がずっとそこに封印されていると人々は言うんだ。"}]
};
t["PayTavernRumorsIntro"]<-{rumors= [{b="The patrons shout your name as they clink their cups. The drink loosens their tongues.",t="常連客はカップをチリンと鳴らしながら君の名前を叫ぶ。 酒が彼らの舌を緩ませる。"},
        {b="The patrons nod approvingly.",t="常連客は納得したように頷く。"},
        {b="People raise their mugs in appreciation.",t="人々は感謝の気持ちでマグカップを掲げる。"},
        {b="The people murmur approvingly.",t="人々は納得した様子で呟く。"},
        {b="The innkeeper rings a bell to let everyone know the next round is on you.",t="宿屋の主人はベルを鳴らし、次のラウンドが君にあることを皆に知らせる。"}]
};
t["RumorsSnowSettlement"]<-{rumors= [{b="The best remedy against biting winds and freezing cold can be found right here: Beer and mead!",t="厳しい風や凍えるような寒さに対する最高の特効薬がここにある：ビールと蜂蜜酒だ！"},
        {b="A fortnight ago %randomname% went missing on the way home from the tavern. Found him frozen rock solid the next morning. Could have sold him to some fancy noble as a statue, haha!",t="2週間前、酒場から帰る途中で%randomname%が行方不明になったんだ。 翌朝、固い岩みたいにに凍り付いているのが見つかった。 銅像としてどこかの高級貴族に売ることもできただろうな、ハハ！"},
        {b="There are tales of figures shifting in snowstorms and unearthly howls that mix with the winds... but I wouldn't want to unsettle you with the common folk's farytales.",t="吹雪の中で動く人影や、風に混じって聞こえる得体の知れない遠吠えの話もある...が、私は庶民のおとぎ話で貴方を不安にさせたくはない。"},
        {b="I've been told that a long time ago this land was all green with many proud castles and awe-inspiring towers. Most of them have crumbled to ruins by now and are covered with snow. But they'll have to be out there somewhere...",t="大昔、この地は緑に覆われ、誇り高き城や畏敬の念を抱かせる塔が数多くあったと言われている。 今やそれらのほとんどは崩れ去り、雪に覆われている。 しかし、どこかにあるはずなのだ..."},
        {b="Four winters. Four winters since I saw a chance for quick coin and raided a roadside chapel. Put the iron to a holy man that tried to hold me back; now no amount of crowns can repay the debt that my spirit owes.",t="4つの冬。 手っ取り早く小銭を稼げるチャンスと思って道端の礼拝堂を襲ってから4年の冬が過ぎた。 俺を引き留めようとした聖職者を手に掛けたんだ。今じゃいくらクラウンを積んでも俺の心が負った借りは返せない。"}]
};
t["RumorsItemsNomads"]<-{rumorsitems= [{b="The nomads take what they want and hide out in the desert. The guards have been looking for them %terrain% %direction% of here. I think they're %distance%.",t="遊牧民は欲しいものを手に入れて、砂漠に身を隠す。 警備隊は%direction%の%terrain%で彼等を探していたようだな。私は %distance%だと思うよ。"},
        {b="The days here in the south are as bright as the nights are dark. I must have stumbled and lost my precious weapon %distance% to the %direction%, but I gave up looking for it.",t="ここ南方の日は夜が暗いのと同じくらい明るい。 %direction%の%distance%でつまずいたときに貴重な武器を失くしたに違いないが、探すのは諦めた。"},
        {b="The craftsmen of the ancient times really knew how to make remarkable weapons. Rumors has it such a weapon is with a nomad tribe hiding out in the %direction%, but who should take it from them - me? Ha!",t="古代の職人たちは驚くべき武器の作り方を本当に知っていたのさ。 噂によると、そのような武器を%direction%に潜伏している遊牧民の部族が持っているということだ、だが誰がそれを彼らから奪うべきかね - 私？ ハハ！"},
        {b="A shield reflecting the sunlight like a mirror, more blinding than the midday in the desert! Where I saw that? Some Nomads had it in the %direction% %distance% from here, if I recall correctly.",t="鏡のように太陽の光を反射する盾で、砂漠の正午よりも目が眩むんだ！ どこで見たかって？ 記憶が正しければ、ここから%direction%へ%distance%にいた遊牧民達が持ってたよ。"},
        {b="All my life I've been hunting nomdas across the borders %terrain%, but I never saw one wield a shield like this one before. It was %distance% to the %direction% at one of their camps.",t="私はこれまでずっと国境の%terrain%を越えて遊牧民達を狩っていたが、あんな盾を持つ者は初めて見た。 彼らの野営地から%direction%へ%distance%だ。"},
        {b="Nomads do not only take from the living but from the dead as well! Word has it they plundered the so-called %item% from a tomb %direction% of here where they have their camp still. They really do not have any decency.",t="遊牧民は生者からだけでなく死者からも奪うのさ！ 噂によると、連中がまだ野営してるところの%direction%の墓から%item%と呼ばれるものを略奪したらしい。 あいつらは本当に良識ってもんを持ってないな。"},
        {b="I used to be first quartermaster to a Vizier. When the famed armor I ordered for a guest of honor did not arrive, I lost my position. The caravan with it was ambushed by nomads, I later learned, %direction% of here.",t="私はかつて宰相様の筆頭侍従でした。 主賓のために注文した有名な鎧が到着しなかったとき、私は地位を失いました。 それを持った隊商は遊牧民に待ち伏せを受けたんです、後で知りましたが、ここから%direction%ですよ。"},
        {b="An oppulent armor is said to be hidden out %terrain% %direction% from here. Many treasure seekers failed to claim it so far but maybe you have more luck?",t="豪華な鎧がここから%direction%の%terrain%に隠されていると言われている。 これまで多くの宝探しがこの宝を手に入れることが出来なかったが、もしかするとアンタは他より運があるかもな？"},
        {b="The most skilled armorsmith around, who happens to be a friend of mine, got tricked by those damned nomads and they made off with one of his prize armors. If you come across any nomads %direction% of here, search their bodies thoroughly!",t="この辺りで最も腕利きの鎧職人は、たまたま私の友人だったんだが、あの忌々しい遊牧民に騙されて見事な鎧の1つを持ち逃げされたんだよ。 ここの%direction%で遊牧民に出くわしたら、奴等の身体を徹底的に調べてくれ！"}]
};
t["PayTavernRoundIntro"]<-{rumors= [{b="The men cheer your name as they drink.",t="部下たちは飲みながら君の名前に乾杯する。"},
        {b="The men drink to fallen comrades.",t="部下たちは倒れた仲間のために乾杯する。"},
        {b="The men cheer the company name as they drink.",t="部下たちは飲みながら傭兵団の名前に乾杯する。"},
        {b="The men drink to women and their bosoms.",t="部下たちは女とその胸に乾杯する。"},
        {b="The men drink to the loyal wardogs.",t="部下たちは忠実な軍用犬に乾杯する。"},
        {b="Laughter and light-hearted stories fills the tavern as your men drink.",t="部下たちが飲むと、酒場を笑いと軽妙な話が埋め尽くす。"},
        {b="Hard mercenary life takes a rest as the men share stories of their past lives and enjoy themselves.",t="過酷な傭兵暮らしでは、部下たちが過去の人生を語り合い、楽しむことで休息をとる。"},
        {b="'Huzzah to the commander!', the men shout.",t="「司令官、万歳！」と部下達が叫ぶ。"},
        {b="Your men boast with their accomplishments as they drink.",t="君の部下は酒を飲みながら自分の功績を自慢している。"},
        {b="The strong drinks blur the horrors of combat for a while.",t="強い酒はしばらくの間戦闘の恐怖をぼやけさせる。"},
        {b="Your men cheer and toast to riches and a long life.",t="君の部下は歓声を上げ、富と長寿を祝って乾杯する。"},
        {b="The beer makes the hardships of the day disappear.",t="ビールはその日の苦労を忘れさせてくれる。"}]
};
t["RumorsItemsGoblins"]<-{rumorsitems= [{b="A really pissed-off nobleman told me the other day that some stunty greenskins made off with his family heirloom after poisoning his trusted guard dogs. He swears they hid %terrain% somewhere %distance% from here, but I don't think he ever convinced anyone to retrieve it for him. Certainly not me.",t="先日、本当に腹を立てた貴族が、グリーンスキン共が信頼していた番犬を毒殺して一族の家宝を持ち逃げした、と教えてくれたんだ。 奴等はここから%distance%の%terrain%のどこかにそれを隠したと彼は誓ったんだが、彼は誰かにそれを取り戻すように説得したことはないと思うよ。 もちろん私にもね。"},
        {b="Afraid of greenskins? Some real beaten up soldiers passed down through here the other day. Said they wanted to wrestle a well-known weapon from goblins %direction% of here, but it sure looked like it didn't go down as planned and they had to pull back. Guess their prize is still up for the taking.",t="グリーンスキンが怖いかい？ この間、本当にボロボロになった兵士達がここを通ったんだ。 ここから%direction%のゴブリン共から有名な武器を奪取すると言ってたんだが、計画通りにいかなかったらしくて、撤退せざるを得なかったみたいだね。 その武器はまだ残っていると思うよ。"},
        {b="A farmer from up %direction% told me he saw some small, sinister creatures on his land carrying a large, shiny shield and making devilish noises. He says it was goblins, but I say he got pranked by some youngsters!",t="%direction%の農夫が、自分の土地で小さくて不吉な怪物達が大きくて光沢のある盾を持って悪魔のような声を上げているのを見たと言ってたぞ。 彼はそれがゴブリンだったって言うんだが、俺は若者達にいたずらされたんだと言ってやったよ！"},
        {b="They found the best shieldmaker in the whole region dead with a dart sticking out of his neck %direction% of here. People said they saw little creatures running off with half his wares.",t="この周辺では最高の盾職人が、ここの%direction%で首にダーツを突き刺されて死んでいるのが見つかったんだと。 人々は、小さな化け物共が彼の商品の半分を持って走り去るのを見たと言ってる。"},
        {b="Somewhere %direction% of here be some goblins. The only reason I know it is because every swinging dick that comes this way talks about how they just barely got away with their life. One even claims he lost his mastercrafted shield when legging it.",t="ここの%direction%のどこかにゴブリン達がいる。 俺がそれを知っている唯一の理由は、この道から来る男達みんながどうやって奴等から生命からがら逃げたか語るからだよ。 ある者は、逃げ出すときに傑作の盾を失ったとも言ってたな。"},
        {b="Word has it that some overpriced and overvalued piece of armor  was stolen from the guardhouse by some small devil creatures that hauled it to the %direction%. %randomname% said it must've been goblins, but no one here really knows what they look like.",t="噂によるとだな、高値で取引されてる鎧のひとつが小さな悪魔のようなバケモン共に衛兵所から盗まれて、ソレは%direction%に運ばれたらしいぜ。 %randomname%はそいつらがゴブリンだったに違ぇねぇって言ってたが、ゴブリンがどんな姿をしてるのかここじゃ誰も知らねぇのさ。"},
        {b="It's said that kobolds and goblins take a special interest in everything shiny. I never believed this to be true myself, but I repeatedly saw something glissening in the sun %terrain% %direction% from here and heard strange stories about short and stubby creatures roaming that area.",t="コボルドやゴブリンは、光る物全てに特別な興味を示すと言われています。 私自身はこれが本当だとは思ってなかったんですが、ここから%direction%の%terrain%で太陽の下で何かが光るのを何度も見ましたし、背が低くてずんぐりした生き物がその辺りを彷徨いているという奇妙な話を聞きましたよ。"},
        {b="You may be interested to learn that our old herbalist outside of town got robbed last night just as a wealthy knight payed him a visit. The assailants, he claims it was small creatures looking like deformed kids, killed the knight and made off to %terrain% in the %direction%.",t="町外れにいる年老いた薬草医が昨夜、裕福な騎士が彼を訪ねてきたところを強盗に襲われたことを聞きたいんだろ。 それをやった犯人達は、奇形児みたいな小さな生き物で、騎士を殺して%direction%の%terrain%に向かったんだそうだ。"}]
};
t["RumorsItemsOrcs"]<-{rumorsitems= [{b="A caravan transporting some valuable ceremonial weapon has been raided %direction% of here. Rumor is the victims had every single bone broken, and a terrible stench hangs in the air.",t="貴重な儀式用の武器を輸送していたキャラバンがここから%direction%で襲撃されたそうだ。 噂によると、犠牲者は全身の骨を砕かれ、ひどい悪臭が漂ってるらしいぞ。"},
        {b="A patron recently spoke of some weapon called the %item% he wanted to sell. Said he got spooked by some greenskinned beasts on his way to town and abandoned it %terrain% %direction% from here.",t="常連客のひとりが、売りたいと思っていた%item%と呼ばれるいくつかの武器について話してたのさ。 彼が町に行く途中で緑皮の獣達に怯えて、ここから%direction%の%terrain%にそれを捨てて来たと言ってた。"},
        {b="A traveler told me the other day that he saw the biggest man alive wielding what he called %item% with his own eyes. Sounds like hogwash to me, but if you're interested the guy left here towards the %direction%.",t="先日、ある旅行者が、%item%と呼ばれるものを振るう大男がいるのを見たと話してた。 俺には戯言みたいに聞こえるが、興味があるならソイツは%direction%に向かって去っていったそうだぜ。"},
        {b="Big cocked adventurer with a pretty face came by here a few nights ago. He headed %direction% of here looking to slay some greenskins. Wore a fancy shield on his back, looked like some type o' knight, but told me he wasn't.",t="数日前、かわいらしい顔をしたアレのデカい冒険家がここにやって来たんだ。 彼はグリーンスキン共を殺すためにここから%direction%に向かったよ。 背中に派手な盾を背負っててな、どこかの騎士みたいに見えたんだが、そうじゃないと言ってた。"},
        {b="They say that some famous shield, I forgot what it was called, once stopped a boulder from rolling down a hill and crushing a camp. Sounds like shite to me. Not that we'll ever find out if it's true that it's an orc war trophy now, hidden somewhere %distance% to the %direction% of here.",t="何て名前だったかは忘れちまったが、ある有名な盾が、丘から転がり落ちて野営地を押し潰そうとする巨石を止めたことがあるんだと。 馬鹿げた話に聞こえるがな。 ここから%direction%の方へ%distance%にあるどこかに隠されてるって話なんだが、そいつがオークからの戦利品だって話が本当かどうかはもうわかんねぇよ。"},
        {b="Don't take my word for it, but supposedly some big green oafs %direction% of here are toting around with an incredible shield simply called %item%. How they might've gotten it is beyond me.",t="私の言葉を鵜呑みにしないでほしいんだが、おそらくここから%direction%にいるある大きな緑色の大男達は%item%と呼ばれる信じられないような盾を持って歩き回ってる。 彼らがどうやってそれを手に入れたのかはわからない。"},
        {b="Some nobleman's manor got raided by greenskins a few days ago. They made off with some famous shield or relic. Supposedly those greenskinned bastards are holed up somewhere %direction% of here.",t="ある貴族の邸宅が数日前にグリーンスキン達に襲われたんだ。 奴等は有名な盾や遺物を持ち去った。 多分だけど、それらの緑色の肌のロクデナシ共はここから%direction%のどこかに隠れてるよ。"},
        {b="Familiar with orcs? Massive beasts and strong as oxen! A mercenary band that called themselves %randommercenarycompany% came through and headed %direction% to hunt them down some weeks ago. They never returned, but their leader wore the most impressive armor I've ever seen in my life!",t="オークを知ってますか？ 巨大な獣で牛のように強いんだ！ 何週間か前に%randommercenarycompany%と名乗る傭兵団がやって来て、奴等を狩るために%direction%に向かったんだよ。 彼らは二度と戻ってこなかったんだが、彼等のリーダーは今まで見た中で最も印象的な鎧を着ていたよ！"},
        {b="Oh, have you heard of %item%? It's said to have been stolen ages ago during the last orc invasion. There were sightings of it reported %direction% of here, but me, I don't know any details. I didn't mean to get your hopes up about it.",t="ああ、%item%を知ってるかい？ 何年も前のオークの侵攻の際に盗まれたと言われてる。 ここの%direction%で目撃されたっていう報告があったんだが、詳しいことは知らないんだよ。 期待させるつもりはなかったんだけどね。"},
        {b="Some famed armorsmith got slain a few days ago. Rumor has it orcs ransacked his place and ran off with his masterpiece to somewhere %direction% from here. Maybe someone else can tell you more.",t="ある有名な鎧職人が数日前に殺されたんだ。 噂によると、オークは彼の家を荒らし回り彼の傑作を持ってここから%direction%のどこかに逃げたんだってさ。 多分誰か他の人が詳しいことを知ってると思うよ。"},
        {b="Word has it %randomnoble% got forever put to sleep by a band of greenskins %direction% of here. He was well known for abusing all his servants so you won't find anyone crying for him 'round here. Just a shame for the mastercrafted armor he used to boast, that one could buy us a lot of pigs and cows. And chickens!",t="噂によるとだな、%randomnoble%がここから%direction%でグリーンスキンの一団によって永遠の眠りにつかされちまったんだそうだ。 奴は使用人達を酷使してたことで有名だったからな、ここで奴のために泣いている人は誰もいねぇよ。 ただ、奴が自慢してた傑作の鎧でたくさんの豚や牛を買うことができたのは残念だったよ。 鶏もな！"}]
};
t["RumorsSteppeSettlement"]<-{rumors= [{b="You men must be sweating like pigs under all that armor. Maybe you should travel when the moon is out?",t="貴方の部下は皆鎧の下で豚のように汗をかいているに違いないよ。 月が出ているときに動いた方がいいんじゃないかい？"},
        {b="Let me tell you, the southern wine is the best you can find in all the lands. But you better start bashing in some heads or whatever it is you do so you can afford the good stuff, because it doesn't come cheap.",t="言わせてくれ、南方のワインは貴方がこの世で見つけられる最高のものだ。 しかし安くはないから、いいものを買う余裕があるように、何人かをクビにするとかそういったことを始めた方がいい。"},
        {b="A trader from the north got lost in the steppe the other week. He made it back but did not stop fantasizing about some lake he discovered surrounded by lush plants and strange animals.",t="先週北方から来た商人が草原で道に迷った。 彼は戻って来たが、緑豊かな植物や奇妙な動物に囲まれた湖を発見したときの空想は止まらなかった。"},
        {b="Tell your men to keep their mitts off of the innkeeper's daughter. The last lover boy who tried something had his nose cut right off.",t="宿屋の主人の娘に手を出さないように部下に言っておけ。 最後に何かをしようとした恋人の少年は鼻を切り落とされたぞ。"},
        {b="I'm from up north originally, moved to %townname% just some years ago. Never could stand the cold; snow and wind, day in and out. So one day I just said to myself, %randomname%, I said, go where the sun warms the earth and you're not shivering every time you go out to collect fire wood. And so I did. Didn't regret it since.",t="僕はもともと北方の出身で、数年前に%townname%に引っ越してきた。 寒さに耐えることができなかったんだ、雪と風が毎日毎日吹いていたから。 だからある日僕は自分にこう言ったんだ、%randomname%、太陽が地球を暖め、薪を集めに行く度に震えることのない場所に行け、ってね。 それでそうした。 それ以来後悔はしてないよ。"}]
};