::Const.Strings.Difficulty.push("Legendary");

::Const.Strings.FootprintsType.push("Basilisks");

::Const.Strings.ShipNames = [
	"Summer Daze",
	"Merry Mist",
	"Howl of the Sea",
	"Coral Secret",
	"Sandy Bay",
	"Lady of the Sea",
	"Solitaire",
	"Brunhild",
	"Mathilda",
	"Comet",
	"Tetrarch",
	"Lofjord",
	"Autumn Wind",
	"Poundmaker",
	"Brakel",
	"Seven Stars",
	"Dark Omen",
	"Concord",
	"Albatros",
	"Golden Horse",
	"Sea Nymph",
	"Twisted Fate",
	"King\'s Bounty",
	"Bald Monk",
	"Golden Sun",
	"Vanity",
	"Brazen",
	"Tiger\'s Claw",
	"Sycamore",
	"Noble Runner",
	"Bleak Moon",
	"Clansman",
	"Whale\'s Voyage",
	"Quickmatch",
	"Blackfly",
	"Ejnar Erikson",
	"Lindwurm",
	"Supreme",
	"Griffon",
	"Axford",
	"Bertha",
	"Seagull",
	"Belzebub",
	"Wanderlust",
	"Kelvin",
	"The Aldenham",
	"Dauntless",
	"The Upright",
	"Admiral Adam",
	"Seaskipper",
	"Indomitable",
	"Loyal Express",
	"Madam Alberta",
	"Tancred",
	"Mimic",
	"Prosperity",
	"Waukin",
	"Final Saga",
	"Gilded Oars",
	"Cheerful Sturgeon",
	"Mistpiercer",
	"Pequod",
	"Oceanroad"
];

::Const.Strings.MercenaryCompanyNames = [
	"Iron Ravens",
	"Golden Order",
	"Swords of the South",
	"Wolves of Bleak Forest",
	"Black Shields",
	"Iron Crown Company",
	"Radobrecht\'s Swords",
	"Whistling Arrows",
	"Azure Boars",
	"Fang and Coin",
	"Red Legion",
	"Hungry Hounds",
	"Crimson Daggers",
	"King\'s End Company",
	"Black Company",
	"Second Sons",
	"Walther\'s Fellowship",
	"Grudgebringers",
	"Bernhard\'s Bears",
	"Silver Claw",
	"Iron Brotherhood",
	"Orcbane Company",
	"Iron Covenant",
	"Unbroken Third",
	"Dogs of War",
	"Falkenberg\'s Legion",
	"Free Men",
	"Lords of War",
	"Northern Company",
	"Forsaken Returned",
	"White Company",
	"Widowmakers",
	"Cold Hearts Company",
	"Burning Sun Company",
	"Chosen Few",
	"Dead Men",
	"Bronzeheads",
	"Markland Pikes",
	"Hammerguard",
	"Crowntakers",
	"Silverreach Spears",
	"Iron Pact",
	"Blood Bound",
	"Bulwark",
	"Dawn\'s March",
	"Sons of Winter",
	"Company of the River House",
	"Flaming Comet Company",
	"Grand Company",
	"Rightful Ravagers",
	"Forsaken Brigade",
	"Battle\'s Chosen",
	"Bringers of Peace",
	"Shields of the Night",
	"Mongrels",
	"Bone Wardens",
	"Lost Legion",
	"Only Ones",
	"Volk\'s Vipers",
	"Bock\'s Band",
	"Clapping Gauntlets",
	"Singing Spears",
	"Crowned Stag Company",
	"Diamond Claw Company",
	"Endermen",
	"Swiftblades",
	"Red Crown Mint",
	"Rocktower Host",
	"Golden Handshake",
	"Blood Covenant",
	"Swords of Silas",
	"Terror From Steel",
	"We Faithful Few",
	"Armed and Unbroken",
	"Young and the Bold",
	"Stormwolves",
	"Bonebiters",
	"Wicked Champions",
	"Law of the Land",
	"Highcloak Company",
	"Raging Thunder",
	"Nightforge Company",
	"Thunderwell",
	"Highguards",
	"Broken Brigade",
	"Dawnhorns",
	"Blessed Boys",
	"Prime Order",
	"Crimson Contract",
	"Trusty Troops",
	"Red Regiment",
	"Invincibles",
	"Order of the Fist",
	"The Swiftshards",
	"The Bulwark",
	"The Youngbloods",
	"Iron Hands",
	"Hagbane Company",
	"Silver Hands",
	"Kingslayer Company",
	"The Lucky Few",
	"Crypt Keepers",
	"Mossy Men",
	"Children of the Stones",
	"Might and Mayhem",
	"The Black Mothers",
	"The Last Men"
];
::Const.Strings.NobleHouseNames = [
	"Grimmund",
	"Weilburg",
	"Armsberg",
	"Gota",
	"Eisenstein",
	"Grauwall",
	"Rabenholt",
	"Sommerwein",
	"Winterhall",
	"Ruhmolt",
	"Adelreich",
	"Perowinger",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Horn",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Kaltenborn",
	"Steinwall",
	"Harkon",
	"Osten",
	"Boswell",
	"Olfer",
	"Frankenmuth",
	"Koll",
	"Grunndig",
	"Hochsten",
	"Harper",
	"Haringey",
	"Rottling",
	"Highwater",
	"Brackenbury",
	"Silvertree",
	"Colter",
	"Blackbridge",
	"Goodburne",
	"Kasbaum",
	"Von Fisk",
	"Roth",
	"Dimer",
	"Moldenhauer",
	"Kraus",
	"Brandt",
	"Sauer",
	"Schult",
	"Vegman",
	"Scharnbock",
	"Osterholz",
	"Moers",
	"Recklinghausen",
	"Graf",
	"Frey",
	"Ulbrich",
	"Mandred",
	"Leitdorf",
	"Ludenhof",
	"Gausser",
	"Raukov",
	"Hertwig",
	"Haupt",
	"Feuerbach",
	"Aldrech",
	"Franz",
	"Gelt",
	"Bogenberg",
	"Bohrn",
	"Andechs",
	"Absberg",
	"Ascania",
	"Augustenberg",
	"Babenberg",
	"Bassewitz",
	"Battenberg",
	"Below",
	"Bentheim",
	"Berenberg",
	"Berg",
	"Biron",
	"Bleichroder",
	"Brunoids",
	"Boeslager",
	"Brunswick",
	"Buxhoeveden",
	"Castel",
	"Cirksena",
	"Conradines",
	"Dassel",
	"Decken",
	"Ekkehardiner",
	"Eltz",
	"Erbach",
	"Erlanger",
	"Essen",
	"Etichonid",
	"Ezzonid",
	"Falkenhausen",
	"Flemming",
	"Fugger",
	"Furstenberg",
	"Glucksburg",
	"Gutternberg",
	"Hanover",
	"Hardenberg",
	"Hattonid",
	"Henckel",
	"Henneberg",
	"Hohenlohe",
	"Hohenstaufen",
	"Hatzfield",
	"Humbolt",
	"Hunfidings",
	"Isenberg",
	"Kalckreuth",
	"Kleist",
	"Knuth",
	"Leiningen",
	"Leuchtenberg",
	"Leyen",
	"Lichnowsky",
	"Limburg",
	"Lippe",
	"Lowenstein",
	"Luddendorff",
	"Luneberg",
	"Maiziere",
	"Maltzahn",
	"Mansfeld",
	"Marck",
	"Marwitz",
	"Matfriding",
	"Mechlenburg",
	"Mengden",
	"Merode",
	"Metternich",
	"Moltke",
	"Nassau",
	"Oettingen",
	"Opel",
	"Ottonian",
	"Plettenberg",
	"Puttkamer",
	"Raabs",
	"Rantzau",
	"Rauch",
	"Reginar",
	"Reuss",
	"Reventlow",
	"Ribbentrop",
	"Richthofen",
	"Salian",
	"Salm",
	"Saxe",
	"Schack",
	"Schauenberg",
	"Schirach",
	"Schleswig",
	"Schmitt",
	"Schonaich",
	"Schonburg",
	"Schwarzburg",
	"Schulenburg",
	"Schwerin",
	"Solms",
	"Sponheim",
	"Stackelberg",
	"Stein",
	"Stolberg",
	"Torney",
	"Straus",
	"Supplinburger",
	"Tassis",
	"Varnhagen",
	"Vianden",
	"Waldberg",
	"Waldeck",
	"Walderdorff",
	"Wassenberg",
	"Wedel",
	"Welf",
	"Horstmann",
	"Helbrass",
	"Niederlitz",
	"Weiltraub",
	"Baern",
	"Oldenhaller",
	"Valgeir",
	"Draken",
	"Teugenheim",
	"Helmuth",
	"Scheinmeier",
	"Gruber",
	"Bischof",
	"Weissberg",
	"Heller",
	"Lohner",
	"Kerevald",
	"Stross",
	"Baer",
	"Toddbringer",
	"Schaffer",
	"Erkstein",
	"Berenstein",
	"Widmann",
	"Kenzig",
	"Scheidt",
	"Selzberg",
	"Freundlich",
	"Sheinfeld",
	"Wernicke",
	"Stahlberg",
	"Bidhofen",
	"Sierck",
	"Eggert",
	"Goetz",
	"Dieter",
	"Grimm",
	"Black",
	"Eisenhorn",
	"Gunn",
	"Drachen",
	"Talana",
	"Von Rosen",
	"Krieger",
	"Glaw",
	"Soth",
	"Blueblood",
	"Silverhand",
	"Falken",
	"Hagen",
	"Crownguard",
	"Moon",
	"Von Schmitt",
	"Steiner",
	"Strauss",
	"Kruger",
	"Draco",
	"Helmuth",
	"Talon",
	"Von Kanitz",
	"Morgana",
	"Blade",
	"Lance",
	"Raven",
	"Wolfe",
	"Cairn",
	"Swan",
	"Everwinter",
	"Ironcrest",
	"Montclair",
	"Blackwood",
	"Fairchild",
	"Sterling",
	"Windermere",
	"Goldheart",
	"Cresseau",
	"Montare",
	"Chavalet",
	"Pellellac",
	"Vellane",
	"Aguelon",
	"Amber",
	"Troyes",
	"Darkwater",
	"FitzRoy",
	"Glotka",
	"Kingfisher",
	"Griffin",
	"Beaumont",
	"Grey",
	"Delacroix",
	"La Fayette",
	"Winslow",
	"Fairfax",
	"van Amstel",
	"Godwin",
	"Karlov",
	"Luci",
	"Vandermere",
	"Trante",
	"Slate",
	"Mallister",
	"Cerwyn",
	"Pyke",
	"de Frissac",
	"Redcliff",
	"Saulx",
	"Sturm",
	"Talbot",
	"Chass",
	"Sondar",
	"Steel",
	"de Avalos",
	"Mara"
];
::Const.Strings.CityStateNames = [
	"Dahab",
	"Kabira",
	"Ras Sanan",
	"Tanwir",
	"Azim Shab",
	"Tarwa",
	"Hakim Al Ramal",
	"Karrakan",
	"Al-Hazred",
	"Al-Hazif",
	"Quadim",
	"Hikma",
	"El-Hadet",
	"Al-Anwar",
	"Hadiqat Musawara",
	"Fakhar Jildur",
	"Sharie",
	"Biwatiqa",
	"Sahat Almaerakat",
	"Sanaruk",
	"Makan Muqadas",
	"Zula",
	"Nuqtat Alnakhas",
	"Ghalumsandis",
	"Lashiek",
	"Copher",
	"Numas",
	"Al Rahem",
	"Asad",
	"Ka-Sabar",
	"Bakar",
	"Al-Haikk",
	"Bani-Al-Akhtar",
	"Dhi-B",
	"Ghutani",
	"Kaheid",
	"Malaluk",
	"Zandri",
	"El-Kalabad",
	"Muktarhin",
	"Muzil",
	"Nasr",
	"Nazir",
	"Qurashi",
	"Turjuk",
	"Tayif",
	"Zamesi",
	"Aiir",
	"Amhabal",
	"Barrakeesh",
	"Djambiya",
	"El-Khabbath",
	"Qadira",
	"Kust",
	"Maknes",
	"Ras Karim",
	"Sadiz",
	"Sanaa",
	"Sud",
	"Teshert",
	"Akhaba",
	"Madinat Alzamard"
];
::Const.Strings.Tactical.TerrainDescription = [
	"None",
	"A dirt road originating from constant use by humans and animals.",
	"A primitive road consisting of tamped clay.",
	"A cobblestone road used for carriages and larger vehicles.",
	"Short grass on flat and solid ground.",
	"Bare and flat earth with barely any vegetation.",
	"Forest ground covered in a thick and soft mossy layer.",
	"Dark and muddy earth.",
	"Mostly firm ground covered in tall and soft grass.",
	"Shallow, murky water covering a soft and muddy ground.",
	"Flat and firm ground covered with dry and shriveled grass.",
	"Hard patches of earth completely dried out by sun and heat.",
	"Flat and arid ground covered in rough grasses and weeds.",
	"Frozen ground covered in a thick layer of snow.",
	"Frozen ground covered in a light layer of snow.",
	"Smooth stone ground granting a good footing.",
	"Rough stone ground.",
	"Burning hot desert sand.",
	"Clear and shallow water."
];
::Const.Strings.Terrain = [
	"",
	"in the ocean",
	"on the plains",
	"in the swamps",
	"on the hills",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the mountains",
	"",
	"",
	"in the snow",
	"in the wastelands",
	"in the tundra",
	"in the steppe",
	"on the shore",
	"in the desert",
	"in the wetlands",
	"",
	""
];
::Const.Strings.TerrainAlternative = [
	"",
	"",
	"on plains",
	"in the swamp",
	"on a hill",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"on a mountain",
	"on plains",
	"on plains",
	"in the snow",
	"",
	"in the tundra",
	"on steppe",
	"",
	"in the desert",
	"in wetlands",
	"",
	""
];
::Const.Strings.TerrainShort = [
	"",
	"bay",
	"plains",
	"swamp",
	"hills",
	"forest",
	"forest",
	"forest",
	"forest",
	"mountain",
	"",
	"",
	"snow",
	"wastelands",
	"tundra",
	"steppe",
	"shore",
	"",
	"desert",
	"hills",
	"wetlands",
	"",
	""
];
::Const.Strings.TerrainRegionNames = [
	[],
	[
		"Stormy Sea",
		"Kraken\'s Refuge",
		"White Horses Sea",
		"Thousand Gulls Sea",
		"Deep Depths",
		"Rainy Ocean",
		"Unbound Ocean",
		"Tempest Ocean",
		"Thunder Sea",
		"Great Sea",
		"Surging Sea",
		"Pearl Sea",
		"Howling Sea",
		"Cruel Sea",
		"Arching Tides Ocean",
		"Whispering Waves Sea",
		"Soft Ripple Sea",
		"Green Sea",
		"Sea of Turning Tides",
		"Wailing Ocean",
		"Foamy Shallows",
		"Murky Tide Ocean",
		"Shimmering Expanse",
		"Azure Expanse",
		"The Raging Gulf",
		"The Shimmering Depths",
		"The Still Deep",
		"The Crashing Main",
		"Darkwater",
		"Deepwater",
		"Coldwater",
		"The Sea of Secrets",
		"The Mariner\'s Doom",
		"Ancient Deeps",
		"The Bright Currents",
		"Saltbrine Straits",
		"Haunted Waves",
		"Grog of the Giants",
		"Thresher Bay",
		"Swirling Sea",
		"Black Reef",
		"Biting Waters",
		"The Gulf of Masks",
		"Devil\'s Deep",
		"The Screaming Ocean",
		"Sea of Baldur",
		"The Tunvald Bight",
		"The Far Sea",
		"The Bitter Sea",
		"The Far Sea",
		"The Boiling Sea",
		"Sea of Dusk",
		"Sea of Dread",
		"Sea of Beasts",
		"Sea of Claws",
		"The Depths",
		"Grey waters",
		"Blue Depths",
		"Crying Deep",
		"Deadman Deep",
		"Siren Sea",
		"Swirling Sea",
		"Gulf of Monsters",
		"Wide Bay",
		"Bluewater",
		"Greenwater",
		"Greywater",
		"Blackwater",
		"Broad Sea",
		"Never Depths",
		"Evertide",
		"Calling Sound",
		"Shouting Deeps",
		"Widow\'s Bay",
		"Sailor\'s End",
		"Lost Anchor Bay",
		"Stormwater",
		"Gentle Bay",
		"Gull\'s Sea",
		"Seal Ocean",
		"Whale Sea",
		"Hungry Sea",
		"Yearning Gulf",
		"Quiet Expanse",
		"Foggy Bay",
		"The Endless Ocean",
		"Decker\'s Sound"
	],
	[
		"Vendland",
		"Speedwell Fields",
		"Plainshire",
		"Vinland",
		"Lowlands",
		"Windlands",
		"Wide Watch",
		"Glaucious Domain",
		"Rich Meadows",
		"Markland",
		"Fast Clouds County",
		"Fairdale",
		"Fleetfeet\'s Range",
		"Wanderer\'s Boon",
		"Valeshire",
		"Ridland",
		"Greenfold",
		"Hogfolk",
		"Durum",
		"Shallowford",
		"Two Fields",
		"Kingmill",
		"Minceacre",
		"Glendale",
		"Brillfold",
		"Kindon",
		"Greenmere",
		"Mooseridge",
		"Altmark",
		"Neumark",
		"Fair Range",
		"Middlemark",
		"Grasslands",
		"Moss Valley",
		"Wideacre",
		"Southbloom",
		"Dawnland",
		"Oak Wood Meadows",
		"Southwind Acres",
		"Meadowcove",
		"Willow\'s Fields",
		"Grand View Pastures",
		"Nightingale Valley",
		"Silversage Fields",
		"Heartsong\'s Range",
		"The Open Howl",
		"Felden Broad",
		"Crossvale",
		"Broadacre",
		"Westfield",
		"Lyston",
		"Meathcote",
		"The Slang",
		"Priestfield",
		"Nightmeadow",
		"Hanging Field",
		"Frontfield",
		"Cloverdale",
		"Forge Fields",
		"Blackwatch",
		"The Haggard",
		"Goldcrown",
		"Lapwing",
		"The Lunch",
		"Gibbet",
		"Green Valley",
		"Downway",
		"The Butts",
		"Bellrope Meadow",
		"Wanderfold",
		"Chimney Gill",
		"Onetree",
		"Breakheart",
		"Somerford",
		"Broadchalke",
		"Cat Meadow",
		"Hop Hedge County",
		"Homer\'s Furlong",
		"Snarebush Range",
		"Longhorse Pasture"
	],
	[
		"Black Marshes",
		"Dead Ponds",
		"Tar Fields",
		"Peatfold",
		"Suffocating Bog",
		"Eerie Marshes",
		"Black Morass",
		"Sticky Wallow",
		"Dreaded Mire",
		"Murky Swamplands",
		"Mortun",
		"Blackfan",
		"Gallowsbog",
		"Dungslump",
		"Houndsmarsh",
		"Shipreath Marsh",
		"Cursed Lands",
		"Grimdowns",
		"The Reeds",
		"Froghold",
		"Spidergrove",
		"Duke\'s Demise",
		"Bottomless Pits",
		"Poisonbreath Marshes",
		"Froglickers Grove",
		"Deadbottom",
		"The Wetlands",
		"The Marshlands",
		"Black Mud",
		"Desolate Moor",
		"Black Fumes Polder",
		"Endless Polder",
		"Peat Basin",
		"Riverland Glades",
		"Southland Bowels",
		"Azure Marsh",
		"Thousand Mirrors Bog",
		"The Narrow Quag",
		"Glades of Decay",
		"Ashen Wetlands",
		"Savage Bog",
		"Mire of the Whisp",
		"Forbidden Waters",
		"Dreadmoor",
		"The Black Bog",
		"Graywater",
		"Downbody Bog",
		"Slow Marsh",
		"The Underbog",
		"Mikkelswamp",
		"Crow\'s Rest Swamp",
		"The Cruel Mire",
		"Swallowing Fens",
		"Sludgemaw",
		"Dead Man\'s Marsh",
		"The Sinking Fen",
		"The Hungry Pits",
		"Ghostmoor",
		"Blackmoss",
		"Grey Fen",
		"Mudmoss",
		"Wraithmud",
		"Boneslop",
		"Stink Mire",
		"Clawing mud",
		"Fenlands",
		"Puddlestomp",
		"Footrot",
		"Bogmoor",
		"The Muck",
		"Rotten Fen",
		"Dark Ponds",
		"Peaty Narrows",
		"General\'s End",
		"Stankfoot bog",
		"Mudfolk burrows",
		"Plashy Moor",
		"Mud Glade",
		"Wetland Hollow",
		"Toad Hole",
		"Croaking Marsh",
		"Burping Marsh",
		"Neverfound",
		"Lost Boot Mire",
		"Acrid Bog",
		"The Stinking Swamp",
		"The Lost Bog",
		"The Grimwalk"
	],
	[
		"Bonefold Barrow",
		"Knight\'s Axe Hills",
		"Skullsbreath Mound",
		"Ancient Knolls",
		"Oldlock Hills",
		"The Hummocks",
		"Knowesfold",
		"Ancient Cairns",
		"Humming Hills",
		"Sharp Rocks",
		"Misty Barrows",
		"Boulderhills",
		"Scree Barrows",
		"Bed Load Knolls",
		"Ghost Hills",
		"Banshee Mounds",
		"Shinglehumps",
		"Earthwatch Hills",
		"Giant\'s Pebbles",
		"Buried Snake Hills",
		"Skullslide Hills",
		"Rustcave Hills",
		"Witchmount Hills",
		"Juniper Hills",
		"White Goat Mounds",
		"Barum",
		"The Reach",
		"Whispering Hills",
		"The Bronze Hills",
		"Willowshire Hillside",
		"The Scarlet Hills",
		"Giant\'s Slopes",
		"The Gloomy Hills",
		"The Collapsing Hills",
		"Cavehill",
		"Whispering Rise",
		"Hangman\'s Hills",
		"Ned Hill",
		"Skeleton Hill",
		"The Crying Hills",
		"Picking Hills",
		"Moaning Barrow",
		"Helmann\'s Climb",
		"The Rise",
		"Jinx Hill",
		"Witch\'s Hill",
		"Softslopes",
		"Runehills"
	],
	[
		"Bleak Forest",
		"Dire Woods",
		"Dismal Woods",
		"Dusky Forest",
		"Scoundrels\' Forest",
		"Boar Woods",
		"Bandit\'s Rest",
		"Splinterdale",
		"Spiderwood",
		"Tickbrake",
		"Druid\'s Grove",
		"Brittle Branch Woods",
		"White Wolf\'s Home",
		"Ravenhold",
		"Needlegrove",
		"Rustling Thicket",
		"Mossy Pine Woods",
		"Crows Nest",
		"Black Forest",
		"Prowlers Woods",
		"Gloomy Woods",
		"Wolfwood",
		"Black Woods",
		"Murmuring Woods",
		"Dark Thorn Wilds",
		"Hedgehog Thicket",
		"Misty Covert",
		"Borderdale",
		"Temple Grove",
		"Wretched Woods",
		"Elder Woods",
		"Deep Covert",
		"Macaw Woods",
		"Hexenwald",
		"Crackbarks",
		"Sharptooth Woods",
		"Stalkwood",
		"Feywood",
		"Wolf Grove",
		"Ghostwood",
		"Mistwood",
		"Sapper\'s Covert",
		"Wicked Woods",
		"Jagged Grove",
		"Digwood",
		"Laughing Woods",
		"Brokengrove",
		"Catwood",
		"Hollow Wilds",
		"Narrow Wilds",
		"Ebonwood",
		"Shadowood"
	],
	[],
	[
		"Ancient Forest",
		"Ranger\'s Rest",
		"Valley of the Deer",
		"Oldgrowth",
		"Rampants",
		"Ironoak Grove",
		"Hunter\'s Bosk",
		"Royal Grounds",
		"Sylvan Woods",
		"Fox and Hare Woods",
		"Snapping Twig Forest",
		"Antlerfold",
		"Old Forest",
		"Greenwood Forest",
		"Mossy Woods",
		"Misty Woods",
		"The Sea of Trees",
		"Timberland",
		"Whispering Groves",
		"Grand Hare Woods",
		"Chestnut Grove",
		"Snake\'s Covert",
		"Blackwood Forest",
		"Stormy Woods",
		"Rustling Thicket",
		"Wicked Woods",
		"Gray Toad Woodlands",
		"Treewalker Woodlands",
		"Jagged Woods",
		"Stag\'s Grounds",
		"Crowned Oak Forest",
		"Elderberry Woods",
		"Elm Grove",
		"Black Mole Woods",
		"Brookwood",
		"Springwood",
		"Everwoods",
		"Glistening Woods",
		"Buckthorn Woodlands",
		"Talloak Wood",
		"Venomwood",
		"Verdantwood",
		"Hissing Forests",
		"The Eagledown Wood",
		"Wise Spruce Woods"
	],
	[
		"Red Worm Woods",
		"Fiery Woods",
		"Smoldering Woods",
		"Ember Forest",
		"Vibrant Grove",
		"Foxfold Forest",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Blood Woods",
		"Blazing Forest",
		"Vermillion Woods",
		"Crimson Forest",
		"Auburn Woods",
		"Redwood",
		"Badger\'s Covert",
		"Birch Timberland",
		"Waterwood Forest",
		"Pyrewood",
		"Beatroot Wilds",
		"Bogwood Grove",
		"Yellowleaf\'s Range",
		"Bloodbloom Woods",
		"Redbark Forest",
		"Firerock Grove",
		"Crimson Covert",
		"The Sparkleaves"
	],
	[
		"Spine of the World",
		"Sleeping Giants Back",
		"Jagged Spires",
		"Wall of the Gods",
		"Dreaded Rocks",
		"Rocky Ridge",
		"Jagged Summit",
		"Silver Ridge",
		"Misty Summit",
		"Iron Mountains",
		"Goathorns",
		"Dragonteeth",
		"Highrise",
		"Eagleflight",
		"Grimroof",
		"Dunspike",
		"Dreadhorn",
		"Ravensbeak",
		"Mount Bulkhead",
		"Bulwark",
		"Cloddheads",
		"Browslopes",
		"Hero\'s Fall",
		"Yawning Gaps",
		"Mammothshoulders",
		"Swellpike Heights",
		"Bald Crown",
		"Cloudcrest",
		"Evermist Mountains",
		"Slaughtermount",
		"The Rift",
		"The Thundering Peaks",
		"Decayed Heights",
		"The Glistening Heights",
		"Deserted Rise",
		"The Vast Rise",
		"Moonlit Peaks",
		"The Ashen Pinnacle",
		"The Bare Peaks",
		"The Shadow Mountains",
		"Grimestone Peaks",
		"Brimstone Shoulders",
		"Iron Peaks",
		"Crackrock Peaks",
		"Giant\'s Castles",
		"Deadstone Peaks",
		"Narrowfoot Tops",
		"Thunderstruck Summit",
		"The Chincliffs",
		"Neverending Ridge",
		"The Moaning Mountains",
		"Savage Summit",
		"Snapback Mountains",
		"Weston Range",
		"Cloud Heights",
		"The Cristies",
		"Karwinn Peak",
		"Goldmist Rise",
		"Topteeth",
		"Hightooth Peaks",
		"Whitestone Highlands",
		"Mount Rigid",
		"Sky Hunt Slopes",
		"Whitebear Rise",
		"Arngeir\'s Apex",
		"The Coldspear Tips",
		"The Powdered Crown",
		"Sharpdrop Ridge",
		"The Totos",
		"Mount Rake",
		"Tempest\'s Rest",
		"Mount Knotstone",
		"Gray Fangs",
		"Devil\'s Claws",
		"Kilgore Range",
		"Cloudmaker"
	],
	[],
	[],
	[
		"White Waste",
		"Frozen Plains",
		"Sea of Snow",
		"White Wilderness",
		"Silver Plains",
		"Howling Wastes",
		"Silver Flats",
		"Everwinter",
		"Frozen North",
		"World\'s Rim",
		"Coldend",
		"Wintermore",
		"Icemark",
		"Spikewind",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank",
		"Whitegrave",
		"The Hoary Desert",
		"Edge of the World",
		"Heart of Winter",
		"The Eye of the Cold",
		"Chittering Wastes",
		"Sharpwind Wilds",
		"The Skadi",
		"Icehowl",
		"Hardwater Plains",
		"The Great Whitewater",
		"The Sliding Plains",
		"The Crystal Flats",
		"The Ghostly Polar",
		"Bonechill Hold",
		"Grandfather Glacier",
		"Permafrost",
		"The Shimmering Wilderness",
		"The Skyless Tundra",
		"Winterman\'s Home",
		"Icebound Expanse",
		"The Wailing Icelands",
		"Accursed Iceplains"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Northern Reaches",
		"Ragwilds",
		"Barrens",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens",
		"Frostfire",
		"Frostheart",
		"Outer Heavens",
		"Herfiligrheimr",
		"Issfold",
		"Snarehold",
		"Grimaland",
		"Overland Freehold",
		"Longbone Flats",
		"Endaheimr",
		"Brightmoon",
		"Irongardr",
		"Efstland",
		"Bitterfields",
		"Ancestor\'s Counsel",
		"The Whitewalk",
		"Augaland",
		"Radknott",
		"The Runfold",
		"Edgeguard",
		"Littvegr",
		"Fjalsbjott",
		"Kappfold"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands",
		"The Ashwild",
		"Sanguine Frontier",
		"The Sly Barrens",
		"Glassreach",
		"Hackenborne",
		"Ash Flats",
		"Croakstone",
		"Craterhold",
		"Gizzarden",
		"Outwood",
		"Barrelweeds",
		"Sunsteppe Way",
		"Rork\'s Grift",
		"Stirges Valley",
		"Downmesa",
		"The Tan"
	],
	[],
	[
		"Silver Sands",
		"Dead Sands",
		"Golden Flats",
		"Timeless Sands",
		"Glittering Sands",
		"Scorching Desert",
		"The Emptiness",
		"The Burning Barrens",
		"Southern Sands",
		"Dusty Desert",
		"Sea of Sand",
		"Land of the Sun",
		"The Great Desert",
		"Neverending Sands",
		"Southern Reach",
		"Mumbling Sands",
		"Whispering Sands",
		"Shifting Sands",
		"Moaning Sands",
		"Sparkling Sands",
		"Glistening Flats",
		"Dry Wastes"
	],
	[
		"The Lost Oasis",
		"Green Shallows",
		"Emerald Bassin",
		"Pearl of the South",
		"Fruitful Shallows",
		"Springs of Life",
		"Gift of God",
		"Prophet\'s Salvation",
		"The Wetlands"
	]
];
::Const.Strings.EngageEnemyNumbers = {
	Few = [2, 3],
	Some = [4, 5],
	Several = [6, 9],
	Pack = [10, 14],
	Many = [15, 20],
	Lots = [21, 30],
	Plethora = [31, 40],
	Hordes = [41, 50],
	Throng = [51, 60],
	Swarm = [61, 80],
	Legion = [81, 100],
	Myriad = [101, 1000],
}
