::Legends.Necromancer <- {};
//can roll; brute, clubfooted, clumsy, Iron Jaw, fragile, huge, hesitant, strong, sure footing, survivor, tiny, tough, gluttonous, lucky, shortsighted, aggressive, martial, predictable, lumbering.
::Legends.Necromancer.excludedTraits <- @() [ //only including naturally occouring or obtainable traits.
	::Legends.Traits.getID(::Legends.Trait.Ailing), 
	::Legends.Traits.getID(::Legends.Trait.Asthmatic),
	::Legends.Traits.getID(::Legends.Trait.Bleeder),
	::Legends.Traits.getID(::Legends.Trait.Bloodthirsty),
	::Legends.Traits.getID(::Legends.Trait.Brave),
	::Legends.Traits.getID(::Legends.Trait.Bright),
	::Legends.Traits.getID(::Legends.Trait.Cocky),
	::Legends.Traits.getID(::Legends.Trait.Craven),
	::Legends.Traits.getID(::Legends.Trait.Dastard),
	::Legends.Traits.getID(::Legends.Trait.Deathwish),
	::Legends.Traits.getID(::Legends.Trait.Determined),
	::Legends.Traits.getID(::Legends.Trait.Dexterous),
	::Legends.Traits.getID(::Legends.Trait.Disloyal),
	::Legends.Traits.getID(::Legends.Trait.Drunkard),
	::Legends.Traits.getID(::Legends.Trait.Dumb),
	::Legends.Traits.getID(::Legends.Trait.Fainthearted),
	::Legends.Traits.getID(::Legends.Trait.Fat),
	::Legends.Traits.getID(::Legends.Trait.FearUndead),
	::Legends.Traits.getID(::Legends.Trait.FearGreenskins),
	::Legends.Traits.getID(::Legends.Trait.FearBeasts),
	::Legends.Traits.getID(::Legends.Trait.Fearless),
	::Legends.Traits.getID(::Legends.Trait.EagleEyes),
	::Legends.Traits.getID(::Legends.Trait.Greedy),
	::Legends.Traits.getID(::Legends.Trait.HateUndead),
	::Legends.Traits.getID(::Legends.Trait.HateBeasts),
	::Legends.Traits.getID(::Legends.Trait.HateGreenskins),
	::Legends.Traits.getID(::Legends.Trait.Impatient),
	::Legends.Traits.getID(::Legends.Trait.Insecure),
	::Legends.Traits.getID(::Legends.Trait.IronLungs),
	::Legends.Traits.getID(::Legends.Trait.Irrational),
	::Legends.Traits.getID(::Legends.Trait.Loyal),
	::Legends.Traits.getID(::Legends.Trait.NightOwl),
	::Legends.Traits.getID(::Legends.Trait.NightBlind),
	::Legends.Traits.getID(::Legends.Trait.Optimist),
	::Legends.Traits.getID(::Legends.Trait.Paranoid),
	::Legends.Traits.getID(::Legends.Trait.Pessimist),
	::Legends.Traits.getID(::Legends.Trait.Quick),
	::Legends.Traits.getID(::Legends.Trait.Spartan),
	::Legends.Traits.getID(::Legends.Trait.Superstitious),
	::Legends.Traits.getID(::Legends.Trait.Swift),
	::Legends.Traits.getID(::Legends.Trait.Teamplayer),
	::Legends.Traits.getID(::Legends.Trait.Weasel),
	
	//legend traits
	::Legends.Traits.getID(::Legends.Trait.LegendAmbitious),
	::Legends.Traits.getID(::Legends.Trait.LegendFearNobles),
	::Legends.Traits.getID(::Legends.Trait.LegendHateNobles),
	//::Legends.Traits.getID(::Legends.Trait.LegendCannibalistic),
	::Legends.Traits.getID(::Legends.Trait.LegendSteadyHands),
	::Legends.Traits.getID(::Legends.Trait.LegendPragmatic),
	::Legends.Traits.getID(::Legends.Trait.LegendUnpredictable),
	::Legends.Traits.getID(::Legends.Trait.LegendSlack),
	::Legends.Traits.getID(::Legends.Trait.LegendSureshot),
	::Legends.Traits.getID(::Legends.Trait.LegendDoubleTongued),
	::Legends.Traits.getID(::Legends.Trait.LegendGiftOfPeople),
	::Legends.Traits.getID(::Legends.Trait.LegendSeductive),
	::Legends.Traits.getID(::Legends.Trait.LegendTalented),
];

::Legends.Necromancer.ExcludedInjures <- [
//perma injuries must be managed in actor.nut, NOT here!
//	"injury.traumatized",
//	"injury.brain_damage",
//	"injury.missing_nose",
//	"injury.weakened_heart",
//	"injury.collapsed_lung_part",

//temp injuries
	"injury.cut_artery",
	"injury.cut_throat",
	"injury.deep_abdominal_cut",
	"injury.deep_chest_cut",
	"injury.exposed_ribs",
	"injury.grazed_kidney",
	"injury.grazed_neck",
	"injury.infected_wound",
	"injury.sickness",
	"injury.stabbed_guts",
	"injury.broken_nose",
	"injury.broken_ribs",
	"injury.crushed_windpipe",
	"injury.fractured_ribs",
	"injury.inhaled_flames",
	"injury.pierced_chest",
	"injury.pierced_lung",
	"injury.pierced_side"
];
